### ISSUE TITLE
Links with external protocol in "new-window" event becomes "about:blank"

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1458]
I have an embedded `webview` that contains a link, like this:
``` html
<a target="_blank" href="skype:Charlie_Hess?call"></a>
```
And am trying to handle that link externally using the `new-window` event:
``` javascript
this.wv.addEventListener('new-window', (e) => {
  shell.openExternal(e.url);
});
```
Unfortunately, `e.url` in this case is just `"about:blank"` and the source element is the `webview`. So I don't have a simple way to get at the original `href`, and all of our protocol links are dead. Would it be reasonable to modify the `new-window` event to include more information (e.g., the source link)?

**Comment by zcbenz** [comment]
It looks like a bug to me.

**Comment by saenzramiro** [comment]
I think this came up again. Can anyone confirm?

**Comment by giancarlokc** [comment]
This happens with me. My app renders google drive inside an webview. When I click on the "print" button in the document preview, I get this as url: "about:blank"

**Comment by MaxShv** [comment]
Same here. I get "about:blank" as the url.

**Comment by merliecat** [comment]
I'm also seeing this bug.

Incidentally, if the user clicks the middle mouse button (linux at least) the new-window event issued from that action has the correct url listed.
But, telling users that if the link doesn't work they have to use the middle mouse button is, of course, not acceptable, so...

As a workaround for this issue, you can do the following: -
1. Add an `onmousedown` handler for the webview element.  In the handler record the pointer x & y position, saving them to variables that you can reference from the new-window handler.  We do this because the new-window event doesn't give us the pointer position and we'll need it.
```javascript
    var clientX, clientY; // somewhere not local to the onmousedown handler

    //...

    // Inside the onmousedown handler
    clientX = event.clientX; clientY = event.clientY;
        // where 'event' is the parameter passed into the handler.
```
2. You've  receive a new-window event, so in its handler you check the url: -
    * if it's a normal URL, Hurray!, do your normal thing;
    * if it's "about:blank", Boo!, go on to step 3.
1.  The approach now is to interrogate the 'guest page' in the webview to grab the href from the link clicked by the user.  To do this you'll need: -
    * the current pointer position in your renderer page, which we handily saved to `clientX`, `clientY`;
    * the webview bounding box, so we can calculate the x & y pointer position within the guest page;
    * the magic of injecting javascript into the guest page to execute `document.elementFromPoint()`;
    * and that guys false leg (no not really).
4. So here goes: -
```javascript
    // inside (or called from) the new-window event handler.
    var wv = document.getElementById('my-webview');
    var bbox = wv.getBoundingClientRect();
    var guestPageX = clientX - bbox.left;
    var guestPageY = clientY - bbox.top;
    wv.executeJavaScript
        ("document.elementFromPoint(".concat(guestPageX, ",", guestPageY, ")['href']",
         false,
         (realURL) => {
              // do the normal thing with realURL, Hurray!
         });
```
This approach is working reliably for me, but, I need to declare here that I'm actually working in clojurescript within the re-frame framework inside electron.  So, the above is a translation of what I'm doing, and is not my actual code -- **caveat emptor**!

**Comment by fragsalat** [comment]
This is actually still a problem. I tried to get with iohook the click coordinates and the anchor clicked but this doesn't work when the page is scrollable as iohook returns screenX and screenY but elementFromPoint needs pageX and pageY. Until now I couldn't find a solution for this problem.

**Comment by matt3224** [comment]
I'm still seeing this

**Comment by AnthonyConklin** [comment]
Really need to figure out how to resolve this issue. Any updates or workarounds? My specific case is a javascript trigger window.open so i can hijack the a link
