### ISSUE TITLE
"Unhandled promise rejection" no longer shows up in the console.

### ISSUE THREAD

**Issue by bolinfest** [atom/electron#1472]
I files this as a regression in Atom: https://github.com/atom/atom/issues/6488.

It's up for debate whether the fix should be in Atom or Electron, so cross-posting here.

I don't really care who fixes it, but I'd like to be notified of any errors in my async code again, STAT!

**Comment by deepak1556** [comment]
Actually the `promiseRejectCallback` was patched to introduce the hook for io.js. [Removing](https://github.com/iojs/io.js/blob/master/src/node.cc#L990) it will restore the behaviour to chromium but you will lose the `unhandledrejection` hook. Besides the hook was provided for userland to use it and I believe its best to not add to electron, besides the process object is present on both browser and render process for use ;) Maybe add this hook behaviour to docs on process object to be clear.. Thoughts ?

/cc @zcbenz , @paulcbetts

**Comment by paulcbetts** [comment]
What happens in DevTools because of this? Do we lose all of the DevTools debugging features around promises? I'd rather have it the Chromium way than the io.js way if that's the case

**Comment by mark-hahn** [comment]
> Do we lose all of the DevTools debugging features around promises?

Pretty much.  They are a pita.

**Comment by deepak1556** [comment]
@paulcbetts nope , this is just the unhandled rejection case instead of having the chromium devtools handling it the default way like this
![screen shot 2015-04-25 at 7 07 10 am](https://cloud.githubusercontent.com/assets/964386/7330975/2880d324-eb1a-11e4-8e32-70a09a3b281f.png)

You will now have to use this hook to get the same behaviour. Not sure if we can patch to retain iojs behaviour on browser and chromium behaviour on renderer. But I am -1 on doing a destructive patch to iojs just for this case though. Besides this is some interesting discussion https://github.com/iojs/io.js/issues/830

**Comment by zcbenz** [comment]
The ideal way to deal with this is to follow how we handled `uncaughtException`: we disable the global error handler in io.js, and setup a default `window.onerror` handler to forward the error to `uncaughtException` handler if there is one. So apps can handle errors like browser if they don't have a `uncaughtException` handler, otherwise they handle errors like io.js.

Unfortunately there is no global promise rejection handler like `onerror` in browser, Chrome just prints the error message to devtools and doesn't give user a chance to handle that. But we can still setup a default `unhandledRejection` handler which just prints the error like Chrome if apps don't have a `unhandledRejection` handler, so we can achieve the same effect.

**Comment by deepak1556** [comment]
@zcbenz shouldn't that be left to the users of electron ? If we provide the handling wouldn't it be like iojs providing the hook and handling it at the same time.. That's why I was against it.

**Comment by zcbenz** [comment]
@deepak1556 We can patch io.js to make it emit `_unhandledRejection` instead of `unhandledRejection`, and in electron we handle `_unhandledRejection` and decide whether to print it to console or forward it to `process`'s `unhandledRejection` handlers.

But honestly I think we should just disable the promise rejection handler in io.js, it is just a little new feature in recent io.js and no one will be using it except for those server apps.

**Comment by deepak1556** [comment]
If there isn't much of a use case , I m in for the second option, that way we can stay on track with chromium.. Maybe they can decide to track unhandled rejection differently in future when the standard is clear..

**Comment by cdaringe** [comment]
hi all.  I'm still not clear what the best practice is.  it seems that my `process.on('unhandledRejection, ...)` in the renderer isn't being recognized in the `0.36.x`.  per @zcbenz 's mark on Apr 29, it may be disabled now?  can someone clarify?

**Comment by cdaringe** [comment]
nevermind.  the event is present and working properly.  yahoo!  was using a vendor lib that was swallowing the rejected promise unexpectedly.
