### ISSUE TITLE
Translation in Japanese

### ISSUE THREAD

**Issue by sotayamashita** [atom/electron#1496]
I would like to translate doc into Japanese. Is there any way to do it? 

Thanks in advance.

**Comment by zcbenz** [comment]
Thanks for your interests in translating the docs!

Currently we don't have a document viewer and just relies on GitHub's web interface for displaying them, so we can not simply put the translated docs in this repo, and it would be hard to make translated docs up-to-date since the docs are updating frequently. So I'm afraid the only way is to put translated docs in a separate repo or website.

**Comment by paulcbetts** [comment]
Could we just put them in a separate top-level folder? (`docs-jp`)?

**Comment by zcbenz** [comment]
I think if we want to put it in this repo, we have to make sure it is up to date, otherwise it would be quite confusing. Relying on a single contributor for this doesn't seem a good idea to me.

**Comment by sotayamashita** [comment]
@zcbenz I got it. Thanks

**Comment by yangweijie** [comment]
maybe，we can just create other branch for different language。Or put docs to a separate repo。So we can view it in gitbook。I would like to translate doc into Chinese when i have time.

**Comment by sotayamashita** [comment]
@yangweijie Thank you the idea. I think separation repo is better way to translate . It would not be confusing. 

If we start to translate it into our languages, I would like to do it in the same way.

**Comment by kevinsawicki** [comment]
@sotayamashita would you mind opening an issue on https://github.com/atom/electron.atom.io where we can talk more about this? We are currently working on a plan to host the docs on the site and having translations there would be great.

**Comment by sotayamashita** [comment]
@kevinsawicki OK. I opened the issue on https://github.com/atom/electron.atom.io
