### ISSUE TITLE
How to build with libchromiumcontent ffmpeg_branding ChromeOS?

### ISSUE THREAD

**Issue by thesabbir** [atom/electron#1595]
Currently libchromiumcontent [ffmpeg_branding](https://github.com/atom/libchromiumcontent/blob/master/chromiumcontent/chromiumcontent.gypi#L5) is chrome.
I am currently working on a app that requires more codecs support. It seems [ChromeOS](http://src.chromium.org/svn/trunk/deps/third_party/ffmpeg/ffmpeg_generated.gypi) flag does provides some additional codecs. 

I need help to link my custom libchromiumcontent to electron for a custom build.
My build system is OS X. 

Thanks :)

**Comment by deepak1556** [comment]
if you have custom libchromiumcontent built and uploaded to s3 using the script in `libchromiumcontent` then changing the url here https://github.com/atom/electron/blob/master/script/lib/config.py#L9 would just do, otherwise you need to check these config to your needs https://github.com/atom/libchromiumcontent/blob/master/script/download#L39

**Comment by thesabbir** [comment]
I don't have it on S3. Git repo.

**Comment by zcbenz** [comment]
You can specify where to download libchromiumcotnent with `--url` in bootstrap script.
