### ISSUE TITLE
The release binary is becoming larger on Windows now.

### ISSUE THREAD

**Issue by hokein** [atom/electron#1653]
I have noticed the release binary `electron.exe` is getting more larger on Windows now:

* In release v0.25.3, the size is about 75 MB, while the v0.25.2 is 61 MB.
* The current build of commit 4ca8039104c5fbb4429b7e7df8f2b5cdcd0233ce is about 81 MB.

We need figure out the reason and try to keep electron in a minimal size.

One of the possible reason between v0.25.3 and v0.25.2 is that v0.25.3 build combined the pdf and ppapi libraries in binary. However, after some investigation, I found it isnt the combined-pdf-and-ppapi reason, since in v0.25.3  the `Enable Print API` PR #1532  isn't merged. So it maybe caused by another reason. I will take a look on this.

The increasing size between commit 4ca8039104c5fbb4429b7e7df8f2b5cdcd0233ce build and v0.25.3 is caused by the `Enable Print API` PR #1532 , on Windows the `print API` requires `pdf` library. I do some tries to ship pdf.lib as shared library(pdf.dll),  and the binary back to 75 MB.

**Comment by hokein** [comment]
@zcbenz , After some deep investigation, the reason for increasing the binary size in v0.25.3 is caused by the commit 56afe4dd5d5c616e0b6a3d92f71ff93d20c19fa0. 
I verified that by adding that linking setting in v0.25.3 build, as a result, the binary is back to 61 MB. It looks a little strange, we might probably revert that commit.

**Comment by zcbenz** [comment]
> One of the possible reason between v0.25.3 and v0.25.2 is that v0.25.3 build combined the pdf and ppapi libraries in binary. However, after some investigation, I found it isnt the combined-pdf-and-ppapi reason, since in v0.25.3 the Enable Print API PR #1532 isn't merged. So it maybe caused by another reason. I will take a look on this.

v0.25.3 has already been using the libchromiumcontent that contains PDF and PPAPI libraries, see https://github.com/atom/electron/commit/a6ba0cd10751c3b051503f6eea4b312c89f07abd. But anyway compiler should strip the unused code from final binary, so I agree this might not be the root cause.

> @zcbenz , After some deep investigation, the reason for increasing the binary size in v0.25.3 is caused by the commit 56afe4d.

I'm wondering if that flag has triggered dead code stripping of the compiler, have you tried it on the master branch? All the PDF and PPAPI code are being used now so I think it doesn't matter now.

**Comment by hokein** [comment]
> I'm wondering if that flag has triggered dead code stripping of the compiler, have you tried it on the master branch? All the PDF and PPAPI code are being used now so I think it doesn't matter now.

Yes. I tried it on `v0.25.3` tag branch and current master branch 56afe4dd5d5c616e0b6a3d92f71ff93d20c19fa0.
With the flag, the binary size becomes smaller:
* `v0.25.3`: 75 MB to 61 MB
* `master`: 81 MB to 67 MB

**Comment by zcbenz** [comment]
From [the MSDN page](https://msdn.microsoft.com/en-us/library/70abkas3.aspx), the `/FORCE:MULTIPLE` flag turns off incremental linking, I guess that's why the compiler reproduces smaller binary?

This flag is quite evil so I think we should find the root cause of the big binary size and apply the correct compiler option.
