### ISSUE TITLE
<webview> width and height couldn't setting

### ISSUE THREAD

**Issue by a348730140** [atom/electron#1675]
```JavaScript
<webview id="foo" src="https://www.github.com/" style="width:640px; height:1080px"></webview>
```
width and height not change
js didn't change it 
![default](https://cloud.githubusercontent.com/assets/8408783/7610309/64276e2c-f9ae-11e4-80bb-2237008396bb.png)

**Comment by magicae** [comment]
seems using css `webview /deep/ object` is ok?

**Comment by a348730140** [comment]
sorry, idk wat u r talking about

**Comment by GeorgS** [comment]
@a348730140 wrap a div around your `webview`.

```html
<div style="width:640px; height:480px">
  <webview id="foo" src="https://www.github.com/" style="width:640px; height:480px"></webview>
</div>
```

**Comment by a348730140** [comment]
@GeorgS think you very much

**Comment by markevans** [comment]
had the same problem and that fixed it - thanks (probably because the <object> element inside the webview has height 100% which refers to the enclosing div)

However I think the docs need updating (http://electron.atom.io/docs/v0.27.0/api/web-view-tag/#example) if height and width on the <webview> element don't work

**Comment by alexey-sh** [comment]
Doesn't work
```
<div style="width:640px; height:480px">
  <webview id="foo" src="https://www.github.com/" style="width:640px; height:480px"></webview>
</div>
```

<img width="796" alt="2017-08-06 21 34 04" src="https://user-images.githubusercontent.com/1584156/29004758-0f08e352-7aef-11e7-806d-99cef01958d3.png">
