### ISSUE TITLE
Question about ASAR and file access

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#1676]
As I understand things, if I package my app using the ASAR format I will no longer be able to use the `fs` module to create files (because ASAR is essentially a static virtual directory of read-only assets).

However, I'm trying to find a solution that will enable me to manage a user's entitlements -- sort of like a product license I suppose. Ideally the app will connect to our remote server to verify credentials, and a response with the user's entitlements will be returned. The best solution would be to write that response to the filesystem... somewhere. It doesn't necessarily have to be inside the ASAR.

It seems as though I can't utilize Node's `fs` module for this (because, I think, I'm limited to the ASAR virtual directory -- plus it's read-only). I have thought about possibly [creating a C++ addon](https://nodejs.org/api/addons.html) and having the C++ code manage filesystem access, but I wanted to know if I'll run into the same issues as `fs`.

Can anyone confirm? I'd hate to waste a ton of time building the addon only to run into the same problem.

**Comment by paulcbetts** [comment]
> As I understand things, if I package my app using the ASAR format I will no longer be able to use the fs module to create files

If you use a path via `fs` that is outside the ASAR package, it'll work just like regular `fs`, including writing files. You're not stuck inside the archive!

**Comment by arthurakay** [comment]
Ok, very cool... wasn't aware of that!

I may stick to a C++ addon just to hide the location/logic involved, but good to know I can actually do this. Thanks!

**Comment by havenchyk** [comment]
@paulcbetts @arthurakay but what about files inside the asar archive? I'd like to write and then read the file in the `asar-arc/app/my-file.txt` path.

**Comment by baconface** [comment]
The ASAR will have to remain read only because of restrictions due to it's design. You have a standard cross platform solution on how to do this. This can be achieved by using node.js and not a custom C++ addon.

You can check and make a working directory if it is missing. Then copy your applications files to it and have your app work with them out of there. This is how most applications do this these days.
```require("os").homedir() + '/Documents/YourApp/';``` is pretty standard for user documents specific to your application.
```require("os").homedir() + '/.yourapp/';``` is pretty standard for configuration/core files used by your application.
Or you can make AppData specific working directories for each OS but the top two should work just fine.

This is only meant for things you might wish to be tampered with. Anything not meant to be writable should just remain in your ASAR.

An advantage to using those is they are user profile specific. So your app will have access to them and likely not have permission issues.

**Comment by paulcbetts** [comment]
Even if ASAR archives supported writing via `fs`, it would break signatures on OS X and not be possible on Linux because you're installed (assumedly) to `/usr` where only root can write to
