### ISSUE TITLE
App URL support

### ISSUE THREAD

**Issue by isaacrg** [atom/electron#1707]
Is it possible to connect an electron app to app URL schema like `my-app://view/friends`, such that websites could link to a particular section of the app.

Would this be possible with electron, and how difficult would it be to implement?

**Comment by hokein** [comment]
I think you might use [protocol](https://github.com/atom/electron/blob/master/docs/api/protocol.md) API to implement this.

**Comment by zcbenz** [comment]
Hi, the GitHub issues page is only used for feature requests and bug reports, for questions it is recommended to ask on the [`electron` category on the Atom forums](http://discuss.atom.io/category/electron).

**Comment by CharlieHess** [comment]
@isaacrg, @hokein: We just implemented something like this in Slack. I don't think the `protocol` API will be of much use here, because you need to associate your application with an external URL. On OS X, this is pretty trivial; just modify your app-info.plist:
```
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>my-app</string>
			</array>
		</dict>
	</array>
```
On Windows, it's a bit more of a project and involves writing some keys to the registry. Start [here](https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx) and you might also want this fork of `Winreg` that'll help you with writing default values: https://github.com/CharlieHess/node-winreg/tree/all. The original `Winreg` has infinity bugs, so beware.

**Comment by thomaschaaf** [comment]
@CharlieHess would you mind sharing the code for this? As there are different people trying to accomplish just this: http://atomio.discourse.org/t/custom-url-scheme/19811
