### ISSUE TITLE
additional docs on packaging

### ISSUE THREAD

**Issue by nickdesaulniers** [atom/electron#1723]
I find the docs confusing for a newbie.  For instance, how do I package my apps for distribution?  I'm aware of [this](https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md) and [this](https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md), but I was expected maybe a .dmg file for OSX or a .msi for Windows that I could host and point users to.  It's not clear to me if creating a .asar file is required, and what a user expected to do with one.  I don't have the requirement of protecting my assets, I'd just like to build something I can hand others for them to install.  In this regard, I think the docs could provide additional information for supporting this use case, if it is supported.

**Comment by sbruchmann** [comment]
There should be a link to [electron-packager](https://github.com/maxogden/electron-packager).

**Comment by nickdesaulniers** [comment]
and [electron-builder](https://github.com/loopline-systems/electron-builder)

**Comment by ThorstenHans** [comment]
True, have to agree with @sbruchmann  and @nickdesaulniers These packages should be linked.. I think that's a commen problem for people starting with electron. This may be caused by the re-brand. But it's really hard to identify all the modules and libs required to get started. ( Or let's better say to go from scratch to a final app)
