### ISSUE TITLE
No easy way to pass a buffer from the browser to the renderer, "remote buffers" are not really useful.

### ISSUE THREAD

**Issue by cronvel** [atom/electron#1756]
When accessing a buffer remotely, we get a "remote buffer". However a "remote buffer" does not contain any data: accessing any byte triggers a getter that performs IPC behind the scene. That's way too slow! So I can't figure out any use case where one may want to share a buffer between browser and renderer.

What about just copying it, so the renderer gets its own instance, like any non-object variable?

For instance, the only way to achieve that safely is to perform a `buffer.toString( 'binary' )` browser-side, then a `buffer = new Buffer( buffer , 'binary' )` renderer-side. However the Buffer's documentation specifically says that the `binary` encoding is deprecated and will be removed in the future.

Am I missing something?

**Comment by zcbenz** [comment]
Sending big data through IPC is always slow and would block your app for some time, if we serialize `Buffer` when sending it the app's whole performance would be decreased as long as there is a `Buffer` in some objects being sent.

A possible solution is to use shared memory for sending `Buffer`s, but I don't think it deserves the effort, because under most cases when you want to send a `Buffer` you are doing the wrong thing.

**Comment by cronvel** [comment]
Hi, 

I understand your point.

However "Buffer" does not always mean big data, it just means binary data.

In my case for example, the size is usually between **10 and 100 bytes**. That's a very small size, still, performing random byte access is slow, so I have to rely on a deprecated feature (`.toString('binary')`) to achieve that properly.
