### ISSUE TITLE
Zombie processes on windows ?

### ISSUE THREAD

**Issue by kuno** [atom/electron#1815]
Recently, our company are using electron to build a application on the windows.

But during the testing, we found that every time the application was launched, it will launch not 1 windows process but 2 or 3. After the application was closed, only 1 of those processes existed. Left another 1 or 2 zombie processes still "running".

Is this normal ?

The application was build with https://github.com/maxogden/electron-packager

Tested electron versions: 0.26.1, 0.27.0, 0.27.0
Tested platfrom: windows 7 64bit, windows 8 32bit

**Comment by zcbenz** [comment]
Does the default app leave with zombies? And can you use process explore to check the command line parameters of those zombies processes and past them here?

**Comment by kuno** [comment]
yes, the default app dose leave the zombies. 
The more times you open the app, more zombies.

And all zombies process point to the same location, the exe for the default app
![win7__init___running_](https://cloud.githubusercontent.com/assets/161327/7881324/568d6130-0634-11e5-9490-a0696c282a6f.png)

**Comment by kuno** [comment]
It turns out its our application's problems. Becuase If I roll back to some older code, re-build the app, it dose not has those zombie porcesses.

It launched 3 processes, one parent with two children. There are their command line and parameters.
Sorry, I hidden the real app name. :smile: 

### Good:
`"C:\Program Files (x86)\AppName\App.exe"`
* `"C:\Program Files (x86)\AppName\App.exe" --reporter-url=http://54.249.141.255:1127/post --application-name=AppName --v=1`
* `"C:\Program Files (x86)\AppName\App.exe" --type=renderer --no-sandbox --enable-deferred-image-decoding --lang=en-US --node-integration=true --device-scale-factor=1 --font-cache-shared-mem-suffix=2280 --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=1 --channel="2280.1.1526364038\707291981" /prefetch:673131151`

On the other hand, the app with bad code only launched 2 processes, one parent and one child.

__And when the app closed, the child process exisits, but the parent bacame 'zombie'.__
### Bad
`"C:\Program Files (x86)\AppName\App.exe" `
* `"C:\Program Files (x86)\AppName\App.exe" --type=renderer --no-sandbox --enable-deferred-image-decoding --lang=en-US --node-integration=true --device-scale-factor=1 --font-cache-shared-mem-suffix=1956 --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=1 --use-image-texture-target=3553 --channel="1956.1.1880340433\1487852085" /prefetch:673131151`

**Comment by kuno** [comment]
@zcbenz 

Any progress ?

**Comment by kuno** [comment]
@zcbenz 

Another thing worth to mention is that our app included a cli tool which the app used to read/write to a local sqlite db.

It possible a failure in the cli will cause those zombie processes ?

**Comment by kuno** [comment]
The logs from powershell seems also identical 

### App build with good code
```log
PS C:\Users\windows> cd 'C:\Program Files (x86)\AppNmae'
PS C:\Program Files (x86)\AppName> .\App.exe
PS C:\Program Files (x86)\AppName> [[1288:0601/112625:INFO:renderer_main.cc(200)] Renderer process started
3020:0601/112625:INFO:renderer_main.cc(200)] Renderer process started
[1412:0601/112627:ERROR:gl_surface_egl.cc(173)] eglInitialize failed with error UNKNOWN
[1412:0601/112627:ERROR:gl_surface_win.cc(152)] GLSurfaceEGL::InitializeOneOff failed.
[1412:0601/112627:ERROR:gpu_child_thread.cc(163)] Exiting GPU process due to errors during initialization
[1844:0601/112627:ERROR:browser_gpu_channel_host_factory.cc(134)] Failed to launch GPU process.
[1844:0601/112628:INFO:CONSOLE(29086)] "Download the React DevTools for a better development experience: http:
act-devtools", source: file:///C:/Program%20Files%20(x86)/AppName/resources/app/static/js/index.js (29086)
```

### App build with bad code
```
PS C:\Users\windows> cd 'C:\Program Files (x86)\AppNmae'
PS C:\Program Files (x86)\AppName> .\App.exe
PS C:\Program Files (x86)\AppName> [[1288:0601/112625:INFO:renderer_main.cc(200)] Renderer process started
3020:0601/112625:INFO:renderer_main.cc(200)] Renderer process started
[1412:0601/112627:ERROR:gl_surface_egl.cc(173)] eglInitialize failed with error UNKNOWN
[1412:0601/112627:ERROR:gl_surface_win.cc(152)] GLSurfaceEGL::InitializeOneOff failed.
[1412:0601/112627:ERROR:gpu_child_thread.cc(163)] Exiting GPU process due to errors during initialization
[1844:0601/112627:ERROR:browser_gpu_channel_host_factory.cc(134)] Failed to launch GPU process.
[1844:0601/112628:INFO:CONSOLE(29086)] "Download the React DevTools for a better development experience: http:
act-devtools", source: file:///C:/Program%20Files%20(x86)/AppName/resources/app/static/js/index.js (29086)
```

**Comment by zcbenz** [comment]
Honestly without a reproducible example I am unable to solve this or confirm it is a bug, and since there is no one else reporting the same thing, I'm afraid it is more like a bug of your app or the third party modules.

**Comment by kuno** [comment]
@zcbenz 

Found the bug in our code, sorry for bothering you.

**Comment by Rameshv** [comment]
hi @kuno i am also facing the same issue in my windows environment. It leaves the zombie process even after the `app.quit`.

Based on the above comments it seems the problem is in your code, i am suspecting some bad file system access, or a network stuff (in node) is still running in the background causing the app to sticking around.

is that the case?? could you give me some pointers on what was the issue and how you fixed it.. any inputs highly appreciated.. 

Cheers

**Comment by marwanhilmi** [comment]
@Rameshv @kuno This issue might be related #2209 - was noticing zombie processes on Windows with the crash reporter enabled.

**Comment by ArktekniK** [comment]
Came here from the related issue above. I posted on that issue just now but as it's closed I'll duplicate my comments here.

I am still experiencing this issue on v33.1, even when I am only running my app
Sometimes I am left with a zombie process after exiting my app which may or may not cause a crash. This has the added side effect that when I relaunch my app, I cannot use the IndexedDB because the previous process still has a lock on the IDB file.

I have to go into task manager and force kill electron.exe

Also, I use windows cli to launch and kill electron, passing in the path of my JS as an arg.
EG:
electron-v0.33.1-win32-x64\electron.exe Node_Event_Tool\main.js

I don't know if it's my imagination, but it seems the crash happens more frequently when the devtools have been opened.

--------------

Perhaps the cli is related as mentioned? Or perhaps I am not responding properly to a termination request. Maybe even if my app is using indexedDB and the handle is still open?

Not really sure where to look on this one
