### ISSUE TITLE
Possible to call a win32 api in windows?

### ISSUE THREAD

**Issue by mcheung63** [atom/electron#1900]
Hi, Is it possible to call a win32 api in windows?

**Comment by frankhale** [comment]
Yes, here is one way though I haven't specifically tried Edge.JS in Electron but I have in Node-Webkit. Theoretically it should work. 

http://tjanczuk.github.io/edge/

Granted using Edge.JS requires a little more effort to call directly into Win32 because you'll have to go through .NET first. If you need specific Win32 you can P/Invoke them from .NET and then call the .NET using Edge.JS from JavaScript within your app.

If you decide to try out Edge.JS and have some issues getting it to work I could probably be bothered to help since I am interested in this kind of stuff and have done some work to make it work in Node-Webkit here -> https://github.com/frankhale/nw-edge-example

Or (another way requiring a bit more effort)

There is always the option to write a Node module that provides the necessary Win32 API's wrapped up in a JS API that you can call from your app.

**Comment by paulcbetts** [comment]
Both `node-ffi` and `edge-atom-shell` will allow you to call Win32 APIs

**Comment by zcbenz** [comment]
Closing since it has been answered.

**Comment by FreezeSoul** [comment]
mark
