### ISSUE TITLE
Download attribute on link elements not working inside of webview

### ISSUE THREAD

**Issue by stefanjudis** [atom/electron#1909]
Thanks for the nice project, folks.

I'm using electron to wrap our web application in a webview and distribute this application this way.

Unfortunately we discovered that links with the `download` attribute don't work.

E.g. http://davidwalsh.name/demo/html5-download.php

Works perfectly fine in Chrome but unfortunately does not inside of the webview in electron.

I digged the issues already and couldn't find any information on this specific case.

Any ideas on this are more than welcome. :bowtie: 

Thanks. :)

**Comment by steelbrain** [comment]
I am not sure if downloads of any kind are implemented at the moment.

**Comment by stefanjudis** [comment]
Okay, is there a getting started guide out there?

If it's desired to have this behavior I might spend some time digging into it. :)

**Comment by zcbenz** [comment]
Currently you have to hook to the click event of the link and use `http` module together with `fs` to save the file to user's disk.

**Comment by straccio** [comment]
I have the same need (download a file from the renderer), i have currently implemented a download function like your suggestion using IPC in order to permit the renderer to ask to the main process to download a file by passing the URL, but the request need to be authenticated through session, there is a way to share the session? Or using one chromium Download Manager plugin?

Best regards
