### ISSUE TITLE
Are you guys planning to upgrade to the latest 2.2.1 io.js?

### ISSUE THREAD

**Issue by mcz** [atom/electron#1914]
Electron is still using 1.6.3 :( 

Thanks,
Peter

**Comment by paulcbetts** [comment]
Yep!

**Comment by mcz** [comment]
May I know when are you guys planning to do this? Thanks.

**Comment by steelbrain** [comment]
@mcz are there any remarkable new features in that version that you're excited about?

**Comment by mcz** [comment]
We are working on an awesome new kiosk terminal project and we are seeking ways to switch the entire frontend to Electron. Our current toolchain tracks almost the latest io.js and we test our native (low level hardware handler) modules against it as well. It would be nice if Electron would catch up so we don't have to switch back and forth between 1.6.3 and 2.x.

Also we want to make sure that electron is tracking the latest io.js in the long run, so we can always experiment with the latest features. It also assures us, that we can count on bugfixes in io.js being implemented in Electron as well.

Thanks so much guys.

**Comment by mcz** [comment]
Thank you guys!

**Comment by frankhale** [comment]
I'm going to add this here rather than create a new issue because this isn't really an issue as much as it is a call for help in understanding how to patch iojs for Electron.

Given the vast amounts of issues put in regarding "WHEN IS ELECTRON GOING TO UPDATE TO X.X VERSION OF IOJS?" I thought I'd throw myself into the fire and attempt to learn how to help out in this respect. 

@zcbenz, I'm attempting to wrap my head around the atom/node repository. My naive goal is to be able to merge upstream iojs into this repository so that it stays current with upstream iojs. I see that there are about 19 custom patches. Here is what I think I know so far:

1. The iojs branch is the clean branch with all iojs changes as of 2.2.1
2. The atom-iojs branch is basically the iojs branch plus the 19 custom patches
3. In order to update atom-iojs with lastest from iojs you have to:
 - fetch iojs upstream (need to add a remote for this once cloned locally)
 - merge upstream with iojs branch
 - rebase against atom-iojs branch and fix any merge conflicts

Is this the way to go about doing this? If you could explain your workflow that'd be great. I think it should be part of the build documentation for those developers that want to help out.

**Comment by zcbenz** [comment]
> Is this the way to go about doing this?

It is exactly what I did. One more thing is to tag the old `atom-iojs` branch before rebasing.

**Comment by frankhale** [comment]
Okay thank you!

**Comment by frankhale** [comment]
I just added a pull request for Atom/Node to update iojs to version 2.3.1. 

https://github.com/atom/node/pull/8

**Comment by frankhale** [comment]
The last PR I submitted to update iojs to 2.3.1 was not clean so I went back and fixed it. The new PR is at: https://github.com/atom/node/pull/9
