### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by 7immy** [atom/electron#1920]
I can't find any documentation on notifications.

Looking though the issue posts I found people using something like this

`note = new Notification('hello');`

..but this doesn't work.

I've tried to guess the required file name to go with it like..

`require('notification')`
`require('notifications')`
`require('OSX-notifications')`

but nothing

Could anyone advise or direct me to some documentation?

Thanks

**Comment by paulcbetts** [comment]
Notifications only work on OS X and sometimes Linux, no `require` needed: https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by 7immy** [comment]
Thanks @paulcbetts, 
Are native notifications not available? I've seen them floating around on here, well at least OS X notifications.

**Comment by 7immy** [comment]
Just found this npm module! https://www.npmjs.com/package/node-notifier
Its got windows, mac and linux support with a fulback to Growl if it exists.

**Comment by vinnyp** [comment]
@paulcbetts what's the issue with Windows?

I haven't tried it yet but It looks like `atom/browser/ui/win/notify_icon.cc` Implements `Shell_NotifyIcon()` and sets the balloon/notification data with `NOTIFYICONDATA`.

**Comment by paulcbetts** [comment]
@vinnyp Tray balloons are not the same as notifications, anyone using them as such should be Punished :)

**Comment by vinnyp** [comment]
@paulcbetts maybe we're mixing up terminology, can you help clarify?

Windows has two native mechanisms for displaying notifications:

1. [Notifications](https://msdn.microsoft.com/en-us/library/windows/desktop/ee330740(v=vs.85).aspx) (What you mention above as tray balloons. Supported in XP+)
![win7notifications](https://cloud.githubusercontent.com/assets/1829485/8558127/06a3580e-24b7-11e5-8213-991b9fdded2a.png)

2. [Toast Notifications](https://msdn.microsoft.com/en-us/library/windows/apps/hh465391.aspx), supported in Win8+. Only apps using the new app model (Modern) can use this.
![win8toast](https://cloud.githubusercontent.com/assets/1829485/8558218/957b3b8c-24b7-11e5-8c16-6718e26064b1.jpg)

I'm assuming what you mean by notifications is Google's desktop notifications (e.g. Slack's notifications), correct?
![googletoast](https://cloud.githubusercontent.com/assets/1829485/8558248/c146c466-24b7-11e5-9ac5-f88e83ee75fe.png)

When I hear notifications for Windows, I think of 1 & 2. I was a Program Manager on Windows for 9 years so that's what I think of :)

In what cases do you expose Balloons to developers in Electron?

**Comment by paulcbetts** [comment]
> In what cases do you expose Balloons to developers in Electron?

These are exposed on their own object called `Tray`, which lets you do everything'ish that Shell_NotifyIcon does

> Toast Notifications, supported in Win8+.

Yeah, so this is what we should add to Electron, they actually can be used from Desktop apps as well (unofficially in Win8, and officially in Win10), via the same COM / WinRT'y API. The only caveat is that you must have a shortcut in the Start Menu or else they don't show in Win8. Outlook does this for example. 

> Google's desktop notifications

Chrome's desktop notifications are actually custom-implemented and aren't in Electron (they're part of Chrome's notification system with the Bell in the tray and Google Now and stuff). 

> (e.g. Slack's notifications)

Slack's notifications are actually custom code that are _none_ of these options above! What a world!

**Comment by justinmchase** [comment]
Are there any future plans for the work @paulcbetts mentioned here? We're going to go with `node-notifier` for now probably and will track this to remove the reference when implemented in electron.
