### ISSUE TITLE
Sync calls to remote modules and setImmediate run out of order

### ISSUE THREAD

**Issue by aackerman** [atom/electron#1966]
I have an example repo here reproducing the issue in the smallest case I could come up with.

https://github.com/aackerman/electron-setImmediate-test

The gist is, when attempting to make a sync call in a 'renderer' process to a remote module in the 'browser' process, based on a reference from `remote.require`; the call doesn't block the `setImmediate` queue of tasks from being run. So the calls appear synchronous but don't completely block the run loop. 

Is this intended behavior? It really threw me when debugging an issue.

**Comment by zcbenz** [comment]
This behavior is expected with current implementation of Node.js integration, but I think we should find a way to fix it.

**Comment by zcbenz** [comment]
Related: #873.

**Comment by aackerman** [comment]
Sounds like a complicated fix. What do you think about adding some "gotcha" info to the docs in the meantime?

**Comment by CGamesPlay** [comment]
This is pretty subtle and prevalent... I stumbled upon it because my click event triggered a re-render in React, and my render function made a call to `remote.getCurrentWindow().webContents`, which triggered this `sendSync` call, which caused some pending events to run mid-render, which caused React to re-render mid-render. 

React was able to catch this and report some warnings:
```
Warning: <Unknown Component /> is being rendered by both [Unknown] and [Unknown] using the same key (null) in the same place. Currently, this means that they don't preserve state. This behavior should be very rare so we're considering deprecating it. Please contact the React team and explain your use case so that we can take that into consideration.
Warning: unmountComponentAtNode(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.
Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.
```

I was able to work around the issue by putting the actual processing for the click event into a `process.nextTick` callback.

**Comment by mkscrg** [comment]
We also hit this (#3747), by trying to `remote.getGlobal()` during a `drop` event.
