### ISSUE TITLE
Auto update fails (OSStatus error -60005.)

### ISSUE THREAD

**Issue by bostondv** [atom/electron#2005]
I'm working on an update to our Electron app that updates from Atom Shell v0.20.8 to Electron v0.27.3. Running the auto updater in app results in this error during the download:

`The operation couldn’t be completed. (OSStatus error -60005.)`

I've checked everything I could think of that's been mentioned in other updater error tickets. Code signing on old and new versions of the .app is valid, the update is successfully found on the server and have validated that the zip file is error free.

I'm not sure what `OSStatus error -60005` means, could it be an issue switching from Atom Shell to Electron? Any suggestions what I could try to fix this issue? Our past updates had worked fine.

Thanks

**Comment by zcbenz** [comment]
There were several updates of [Squirrel](https://github.com/Squirrel/Squirrel.Mac/issues) between 0.20 and 0.27, I'm not sure if it is the cause of this problem. The error code `-60005` means "The authorization was denied", I suggest posting this issue to Squirrel's repo since the error came from Squirrel and they might have a better idea of this.
