### ISSUE TITLE
process.cwd() returns '/'

### ISSUE THREAD

**Issue by maxogden** [atom/electron#2108]
Just curious if this is intended behavior, and if it should be documented. IMO `process.cwd()` should return the entrypoint of the application, so e.g. `process.resourcesPath + '/<appfolder>'`, where `<appfolder>` is whatever electron picked as the app folder (could be `app.asar`, `app` or possibly something else).

A related issue is https://github.com/atom/electron/issues/1712, which was closed when `process.resourcesPath` was proposed as a fix, but in practice that only returns the path to the electron resources root folder, which is different from the actual path where the electron app (e.g. `index.js`) is located.

Another related issue is https://github.com/maxogden/menubar/issues/29 which prompted this issue

**Comment by Ivshti** [comment]
@maxogden in UNIX systems, cwd - current working directory, means literarily the current working directory of the process, which is different from the path of the application; a process can be started in any working directory, so this is by design and not a bug of Electron

The docs of process node.js module confirm this.

**Comment by maxogden** [comment]
@Ivshti my proposal is that the `process.cwd()` should get set to the path of the application. I understand that you can spawn processes anywhere, but I am wondering what the intent of the current implementation was (if any). The fact that it's set to `/` doesn't necessarily mean it's "by design", especially if it isn't documented.

Even if process.cwd() isn't the correct API for this, there is still no way that I can see to get the path to the path to the application source folder, e.g. it will be one of these three https://github.com/atom/electron/blob/2bcf8c7bc20d7de6edd6e512044862e70c1e47e7/atom/browser/lib/init.coffee#L58-L65 and `process.resourcesPath` does not point there.

**Comment by Ivshti** [comment]
That's what I mean - most processes do not set cwd but use the one they're launched in.

IMO setting process cwd should be in the application code, and electron should expose a very convenient way to get "current app dir" - altough what is current app dir can be subjective - eg can be the dir of the executable process, or it can be the dir package.json resides in.

**Comment by maxogden** [comment]
I think the 'app dir' is very concretely defined as `path.dirname(packageJson)` where `packageJson` is the one here https://github.com/atom/electron/blob/2bcf8c7bc20d7de6edd6e512044862e70c1e47e7/atom/browser/lib/init.coffee#L62, it would be great if that was exposed.

**Comment by Ivshti** [comment]
I'm surprised it isn't - it definitely should!

**Comment by sindresorhus** [comment]
:+1: I was also surprised when I discovered this. I think making `process.cwd()` the app folder makes a lot of sense.

**Comment by zcbenz** [comment]
`process.cwd()` returns current working directory, it might be a surprise to developers that only write GUI programs, but it is super important to programs that can be invoked from command line.

Suppose `process.cwd()` returns the app directory in Atom, running the `atom file.txt` under command line will try to open a `file.txt` under `/Applications/Atom.app/.../resources/app.asar` instead of the `file.txt`  under current working directory.

I'm :+1: on providing a way to get the path of app dir though, I have created an issue for that #2127.
