### ISSUE TITLE
RequestHttpJob If do not unintercept will infinite loop

### ISSUE THREAD

**Issue by wanglong167** [atom/electron#2182]
If do not unintercept will infinite loop 
Unable to intercept http unintercept after

```javascript
var protocol = require('protocol');
   protocol.interceptProtocol('http', function(request) {
     var url = request.url;
    //  protocol.uninterceptProtocol("http")
     return new protocol.RequestHttpJob({url:url+"?dd=1"});
   });
```

**Comment by paulcbetts** [comment]
If you want to intercept HTTP requests, a Service Worker might work for your scenario

**Comment by paulcbetts** [comment]
This is still a bug! :)

**Comment by deepak1556** [comment]
@zcbenz guess we should run the `URL::Fetcher` in a new dummy request context, instead of using the existing one ?

**Comment by zcbenz** [comment]
@deepak1556 Creating a new request context for the fetch job would make the request have independent cookies, which is not expected on many cases, I think the ideal fix is to have multiple session support so users can avoid the infinite loop by passing a new session object:

```js
var session = app.createEmptySession();
protocol.interceptProtocol('http', function(request) {
  var url = request.url;
  return new protocol.RequestHttpJob({
    session: session,
    url:url+"?dd=1"
  });
});
```

But since it still needs some work to have multiple session support, I think we can allow users to specify a `null` session which creates a new request context for the fetch job:

```js
  return new protocol.RequestHttpJob({
    session: null,
    url:url+"?dd=1"
  });
```

So I think you can change your PR to accept a `session` in `RequestHttpJob`, and if it is set to `null` then create a new request context, otherwise it would reuse current request context.

**Comment by deepak1556** [comment]
> I think the ideal fix is to have multiple session support so users can avoid the infinite loop by passing a new session object

:+1: 

> if it is set to null then create a new request context, otherwise it would reuse current request context.

if the sesssion is not null, the request context provided will be from the new session object right ?

**Comment by zcbenz** [comment]
> if the sesssion is not null, the request context provided will be from the new session object right ?

The answer is yes when we have multi-session support.
