### ISSUE TITLE
Windows Dialog: How to control buttons?

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2258]
I am playing around with the native buttons in Electron 0.30 on Windows and I feel that the placement of buttons is quite random. I realize that Windows 8 shows some buttons within the dialog and some outside:

![image](https://cloud.githubusercontent.com/assets/900690/8742219/53acaa3e-2c63-11e5-814b-2f2ab70064d2.png)

Code
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
    <script>
    var remote = require("remote");
    var dialog = remote.require("dialog");
    dialog.showMessageBox(
remote.getCurrentWindow(),
    {
      type: "question",
      buttons: ["Save All", "Revert All", "Cancel"],
      title: "Shutdown",
      message: "Do you really want to quit?"
    });
      
      </script>
  </head>
  <body>
   
  </body>
</html>
```

Is this a platform thing or can we have a way to force showing the options in one place instead of two?

**Comment by zcbenz** [comment]
@bpasero There are two types of buttons in the native dialog: custom buttons like "Save All" and stock buttons like "Cancel", and there are two ways of showing them: displaying as links or buttons. Currently Electron identifies stock buttons from their labels and shows them as buttons, the other buttons are treated as custom buttons and are showed as links.

Identifying stock buttons can add some goodies to the dialog: some buttons will have accelerators associated, and they will be localized automatically. But the downside is Windows always separates stock buttons from custom buttons, even if we show custom buttons as buttons in the dialog, the sequence of buttons would become a mess.

So I chose to show custom buttons as links in Electron, and the results turned out to be quite well, for your "Shutdown" dialog as example, I think it actually matches the style of other modern Windows apps?

Or maybe I should provide options to let users have complete control of how the dialog shows? I think the safest choice is to treat all buttons as custom buttons and show them as buttons.

**Comment by OlsonDev** [comment]
Regarding @zcbenz "I think it actually matches the style of other modern Windows apps?", Microsoft encourages the behavior; on [MSDN > Dialog boxes](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742499(v=vs.85).aspx):

> - **Always provide an explicit Cancel button.** Don't use a command link for this purpose.

My vote would go to complete control. The documentation should also probably link to the aforementioned MSDN design guidelines.

**Comment by paulcbetts** [comment]
@bpasero If you want to play around with twerking this dialog, clone Electron, then have a look inside the `vendor/brightray` folder, it should be in there somewhere (just edit the code then rebuild Electron, don't try to build Brightray independently)

**Comment by bpasero** [comment]
+1 for full control. though I like the fact that you encourage people to follow OS UX guidelines I would still want to be able to choose how dialogs are shown on windows.

**Comment by paulcbetts** [comment]
>  I would still want to be able to choose how dialogs are shown on windows.

In this case I would just use `node-ffi` to invoke the Task dialog APIs directly, then you can do whatever you want

**Comment by bpasero** [comment]
@zcbenz thanks!
