### ISSUE TITLE
Kiosk mode mith multiple monitors

### ISSUE THREAD

**Issue by wmbaum** [atom/electron#2272]
Kiosk mode seems not to be disabling system keys (alt-tab, etc.) on machines with multiple displays, at least in windows.  I ran a test app in a vm with a single display and it behaved as expected, but on a machine with multiple monitors, the system keys are not disabled, and one can get to the taskbar, etc.. Fullscreen and always-on-top works, and these prevent other windows (except the task manager) from being focused on top of the app, but I need to be able to disable the system keys and the taskbar.

Is there a way to force kiosk mode to work with multiple displays? 

Alternatively, if I make additional windows on the other display(s), how can I explicitly disable the system keys (alt-tab, etc.)?

**Comment by zcbenz** [comment]
On Windows and Linux you can not make your app have real kiosk mode without making your app behave like virus, because you have to block keyboard events, disable the shell, preventing task manager to start, etc. So in Electron kiosk mode behaves the same with fullscreen mode on Windows and Linux, and this behavior won't be fixed.

But if you have full control of user's computer, you may edit the Windows registry to achieve it: https://github.com/nwjs/nw.js/issues/3318#issuecomment-89281703.
