### ISSUE TITLE
Build using entire host system tools

### ISSUE THREAD

**Issue by gustavosbarreto** [atom/electron#2367]
I'm trying to build Electron without the binary stuff (such as clang, sysroot, libchromiumcontent) provided by Electron build system using the OpemEmbedded framework. The OpemEmbedded sysroot contains these stuff, so I don't need the binary stuff from Electron build system.

As I want to build entire Electron the binary libchromiumcontent it is useless, I'll build this one, too.

Currently I have a patch to disable the download of the binary stuff passing a environment variable to the build system.

I want to do better, anyone have a better approach?

**Comment by zcbenz** [comment]
You still need to download libchromiumcontent, or you will have to build it yourself, it is an Electron specific thing so I don't think OpemEmbedded would provide it. 

I'm merging this to https://github.com/atom/electron/issues/259, because the solution to both issues is to provide a way to build Electron with pure host toolchains.
