### ISSUE TITLE
webview node integeration on & require 'module'

### ISSUE THREAD

**Issue by skandasoft** [atom/electron#2396]
I have a webrower-plus(http://atom.io/packages/browser-plus) package for atom. and I am using webview with node-integeration-on but this has problem when showing web pages which has require module...https://github.com/skandasoft/browser-plus/issues/18

**Comment by frankhale** [comment]
Looks like the node require is getting in the way. I suspect you'd need to do some sort of "intelligent" switching around to move it out of the way, eg. assigning the node require to another variable so requirejs's require could work. The "intelligent" part is magic because if you are using node-integration and loading random pages off the net that use requirejs then things are going to get ugly unless you can "know" eg parse the pages to see if they use requirejs or some other require that would break your webview. 

Having node integration turned on for a web browser plugin seems very risky unless you know exactly what and have control over the pages you are loading.

**Comment by skandasoft** [comment]
I have move away from node-integeration on for the browser-plus..I am not sure if this ticked is need to open to check the possibility for node-integeration with require module

**Comment by zcbenz** [comment]
This is a quite classic problem of browsers with node integration, see also:
https://github.com/nwjs/nw.js/wiki/faq-name-conflict
