### ISSUE TITLE
Do not force setting window icon

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2429]
When you create a shortcut to an app with a custom icon, that icon will be shown in the task bar when ever you run the app through that shortcut.
To make it clearer, here's an example screenshot where I created a shortcut to `notepad.exe` and changed it's icon to a blue smiley face:
![image 2](https://cloud.githubusercontent.com/assets/4381579/9090622/090ed0f6-3ba4-11e5-91aa-5b5a83ec7f5e.png)

When you try to do the same with Electron, the icon is ignored and the regular icon is displayed in the task bar (the icon embedded in electron.exe). I guess the issue here is that we probably explicitly set an icon, even if no icon was provided in the BrowserWindow options object and that overrides the shortcut icon.

It would be nice if we can have the native behavior. I'm working on a theme-able app where the icon is replaceable. The icons used are .ico files which are not yet supported (see #2277), so I can't pass them in the BrowserWindow options object. Changing the shortcut icon could have solved it for me, if it worked.

**Comment by zcbenz** [comment]
I think the problem is not Electron setting window icon, actually if you do not set `icon` property, Electron will not set window icon. This is caused by Electron setting application user model ID, once it is set Windows will prefer to use the exe's icon, and the window icon would be ignored.

Recent versions of Electron do not set application user model ID by default any more, so this should work now.

**Comment by soundar78** [comment]
@zcbenz ,
while using squirrel to create an installer, it sets application user model ID by default.
I think this prevents from setting custom taskbar icon.
Any workaround for this?
