### ISSUE TITLE
Embed exe inside Electron

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2438]
Is it / would it be possible to embed another exe inside an Electron application?

For a project I am working on we have built a series of Electron applications for a Games Suite that runs on Windows but because they are all separate exe's, there can be some lag when loading and focusing applications. Ideally I'd like to just load a window and then load the game inside of that. So we can have one application with many windows and mange the windows instead.

I've read on the web from various articles that you can embed an exe inside another exe... but wonder if the same can be achieved in Electron using NodeJS / Native Client in Chrome.

**Comment by etiktin** [comment]
If the other apps are electron apps, you don't need the executable, just the app folder or app.asar.
Take a look at #2415 for some ideas.
If you really want to run the multiple apps in a single app with multiple windows, I suggest that you refactor your apps so each app will be wrapped in a module with a method for creating the app window.

**Comment by iamdriz** [comment]
Not all the apps are electron apps.

**Comment by etiktin** [comment]
You can use [Enigma Virtual Box](http://enigmaprotector.com/en/aboutvb.html), to embed other executables into electron.exe and run them using the `child_process` module. If you have a choice, I think it's better to just distribute them as separate executables, both because the performance will be better and updates will be smaller (electron.exe is ~45MB).

**Comment by zcbenz** [comment]
It is possible to embed any file into an executable on Windows, but it won't have any good impact on the performance, you always have to extract the file into filesystem and then execute it.

I'm closing this since we are not going to implement it in Electron regardless of the performance, and it can be easily implemented as a Node module.

**Comment by trusktr** [comment]
> I think it's better to just distribute them as separate executables, both because the performance will be better and updates will be smaller

What if we run Electron in a kiosk mode straight from boot, and want to use it to run other apps inside of it? Is that possible? For example, other X11 apps in Linux.
