### ISSUE TITLE
Strange interactions between custom elements with createdCallback and ES6 promises

### ISSUE THREAD

**Issue by nathansobo** [atom/electron#2442]
We're attempting to convert all our Atom code to use native ES6 promises, and we're encountering a very strange bug that is blocking this effort. @maxbrunsfeld and I have boiled the issue down to the following script, which can be run in the Electron console to reproduce the problem:

```js
document.registerElement("x-element", {
  prototype: Object.create(HTMLElement.prototype, {
    createdCallback: { // problem does not occur if there's no createdCallback
      value: function() {}
    }
  })
});

// also happens with process.nextTick
window.setImmediate(function() {
  Promise.resolve().then(function() {
    console.log('this should be logged second');
    // if you breakpoint here, you'll see the custom element creation on line 20
    // above the promise resolution in the stack trace
    // debugger;
  });

  // Creating a custom element with a createdCallback causes the promise to
  // be resolved synchronously following the creation of the element.
  document.createElement("x-element");

  console.log('this should be logged first');
});
```

From what we can tell, it seems like when the browser runs the `createdCallback` during the creation of the DOM element, it also ends up resolving promises synchronously. This is creating very strange reentrant behavior when creating custom elements as a result of resolving promises.

**Comment by zcbenz** [comment]
Node's `setImmediate` and `process.nextTick` seems to deal with promise early while processing the callback, as a workaround you can use `window.setTimeout` instead, I'll keep looking into it.

**Comment by nathansobo** [comment]
In our case in Atom the promise is wrapped in a async file I/O but we wanted to keep the example simple.

**Comment by zcbenz** [comment]
I think I have found out the root cause:

`blink` performs microtask actions after reaching the microtask checkpoint, e.g. after executing a piece of JavaScript code, and during the checkpoint the Promise's callback will be called. Every time `blink` executes JavaScript the code will guarded inside a `V8RecursionScope`, and by the time code runs beyond the scope `blink` will think we have reached a microtask checkpoint.

However Electron ignores the whole `V8RecursionScope` thing when executing JavaScript, so in our example the callback passed to `setImmediate` is not guarded inside a `V8RecursionScope`, while the `document.createElement` call is. So when `document.createElement` ends `blink` thinks we have reached a microtask checkpoint, and calls the Promise's callback.

The fix is straightforward, we can simply wrap the code in `V8RecursionScope` when calling into libuv. But it needs to expose internal pieces of blink so it will take some time before I can verify whether the fix works.

**Comment by nathansobo** [comment]
Very glad to hear you figured it out! Thanks for the great explanation.

**Comment by nathansobo** [comment]
:heart:

**Comment by kevinsawicki** [comment]
Awesome investigation :mag: :+1:
