### ISSUE TITLE
No freeBSD support?

### ISSUE THREAD

**Issue by s-a** [atom/electron#2452]
Ref:
 - https://github.com/s-a/iron-node/issues/41
 - https://github.com/mafintosh/electron-prebuilt/issues/49#issuecomment-128932651

The Installation fails with ```Error: Unknown platform: freebsd```

**Comment by s-a** [comment]
Where can I find a detailed list which operating system s are supported?

**Comment by etiktin** [comment]
From what I could gather the support list seems to be: OS X 64 bit, Windows 7+ and Linux (Ubuntu is mentioned most of the time).
FreeBSD is not Linux. If you run `process.platform` on it you will get `freebsd` and not `linux`, so I guess that's why it fails and you get the error you mentioned.

If you want to hack on the code, you can probably get it to work somehow since Chromium and node.js seems to be able to work on it, but I don't think the project maintainers plan to support it.

**Comment by s-a** [comment]
Thanks for the information. I am not an expert I just thought freeBSD IS LINUX :)
So this answer closes the issue.

**Comment by s-a** [comment]
@etiktin seems that atom is running on freeBSD. 
https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md

**Comment by etiktin** [comment]
Nice to know. I wonder why there's no mention of this in Electron.
I think you should reopen this so the maintainers can clarify if FreeBSD is supported or not (e.g. maybe the support for FreeBSD was deprecated). The best outcome is that the docs will contain a "Supported Platforms" document that explains what is supported and from what version.

**Comment by paulcbetts** [comment]
I don't know that anyone is opposed to supporting FreeBSD here. If you find specific issues file bugs for it

**Comment by etiktin** [comment]
If a platform is not supported I don't see a point in opening bugs for it, it's just extra noise.
The problem is that there's no official document that says what platforms are officially supported. There's no mention of FreeBSD in Electron's docs and it doesn't seem to work (see the error in the OP), but then Stephan found a document in Atom that says you can build it on FreeBSD so it's a bit confusing.

**Comment by paulcbetts** [comment]
## THE OFFICIALLY OFFICIAL PLATFORM SUPPORT DOCUMENT

* Windows
* Linux
* OS X
* FreeBSD if we can convince people to file bugs

**Comment by etiktin** [comment]
Nice :laughing:

**Comment by s-a** [comment]
https://github.com/atom/electron/releases/latest offers a list of supported platforms plus info about 32 and/or 64 bit. Would be nice to have some more detailed information, I guess Windows version >= 7 is supported. But I do not know. More over Linux is a very large field. Here I guess it depends on the installed desktop environment.
For me it would be nice to have a document anywhere that gives a quick overview. 

However I feel I mixed up 2 questions in one issue ... Sorry for that :v:

**Comment by paulcbetts** [comment]
So here's a probably stupid question, do Linux binaries work unmodified on FreeBSD?

**Comment by s-a** [comment]
I have no idea about freeBSD but ive found this.  

> FreeBSD provides 32-bit binary compatibility with Linux®, allowing users to install and run most 32-bit Linux® binaries on a FreeBSD system without having to first modify the binary. It has even been reported that, in some situations, 32-bit Linux® binaries perform better on FreeBSD than they do on Linux®.

> However, some Linux®-specific operating system features are not supported under FreeBSD. For example, Linux® binaries will not work on FreeBSD if they overly use i386™ specific calls, such as enabling virtual 8086 mode. In addition, 64-bit Linux® binaries are not supported at this time.  

https://www.freebsd.org/doc/handbook/linuxemu.html

Performs better than on Linux  :smile:

**Comment by yonas** [comment]
I use FreeBSD for my desktop, so I'd love to see this as well.

FreeBSD has init support for 64-bit binary compatibility with Linux. More info here:

http://www.freshports.org/commit.php?message_id=201507261306.t6QD6PgG039161@repo.freebsd.org

**Comment by faust64** [comment]
@paulcbetts : regarding running linux binaries on FreeBSD, short answer, it *could* be done using "linuxulator" (as pointed out by @s-a).
Running FreeBSD, you may install centos6 or fedora10-based linux libraries, that may be used running linux binaries. One of the most common use case being flash plugins.

As far as I've seen, you need to run linux32 binaries (64 are not recognized in their latest 10.3-RELEASE, whereas 32 bits have been working fine in the last 10 years).
Having used nw.js by the past, I ended up with missing libraries - libgconf2, which is there (native) for FreeBSD, but has no equivalent running linux binaries. And I suspect gconf is only the tip of the iceberg. If anything, I'ld strongly recommend to build something native. Otherwise, you'll probably need to build additional ports shipping missing libraries, ...

Anyway, good luck figuring this out.

**Comment by lapo-luchini** [comment]
A comment 6 days ago in #3797 seems to give some hope for a native support of FreeBSD.
