### ISSUE TITLE
Unable to create status tray icon on Windows - v0.30.3 and v0.30.2

### ISSUE THREAD

**Issue by armaseg** [atom/electron#2468]
I've been trying to use a tray icon on Windows with v0.30.3 and v0.30.2 and I get the following errors: 
<code>Unable to create status tray icon.
Error setting status tray icon image.</code>

![error-win7-2](https://cloud.githubusercontent.com/assets/1028859/9176311/3845161e-3f50-11e5-9f14-b9bffc956215.JPG)

However, using v0.30.1 it works.

<code>
var appIcon = null;
var iconPlain = path.join(__dirname, 'image.png');
app.on('ready',function(){
  appIcon = new Tray(iconPlain);
</code>

**Comment by armaseg** [comment]
I got the same errors on v0.30.4

**Comment by mnemotiv** [comment]
Same here. Bump.

**Comment by shrewdlogarithm** [comment]
I'll bump this too - last seen working in 0.29.2

**Comment by hankbao** [comment]
Same here. :fearful:

**Comment by hfcorriez** [comment]
Same here.

**Comment by armaseg** [comment]
Is working again on v0.30.5
Thank you!

**Comment by shrewdlogarithm** [comment]
Certainly fixed as of 0.30.6 - thanks!

**Comment by shrewdlogarithm** [comment]
Updating this because it's stopped working - not sure exactly why, changed nothing in relation to the tray

0.30.6 and 0.31.2 both throw an "Error setting status tray icon image" error - whether the app is unpacked (app directory) or packed (app.asar)

!?!?!?

**Comment by hankbao** [comment]
This issue may need to be reopened.

**Comment by ProteusCortex** [comment]
@hankbao, I agree...

**Comment by paulcbetts** [comment]
So, after a *lot of suffering*, we've figured out that the advice we were given that culminated in #2328 (from a lead Windows OS developer!) was actually really bad for apps that use Squirrel. 

### How we _thought_ it works

When Windows creates a Tray icon preference for your app, they use your EXE's full path as the "key" to that preference. However, when Squirrel for Windows moves the EXE's location, that key no longer matches, even though it's the same App. The solution to this is (we thought!) the GUID parameter, which we initially thought would be used _in place of_ the key. Use the same GUID for every version of the app, and you're all set. To automate this, #2328 tried to take your app's App Model ID (a similar concept of being able to group different EXEs into one "App") and blit it into a GUID. 

### How it _actually_ works

When you use a GUID along with the Tray icon, it _still_ records the EXE's full path, but then proceeds to *disallow* anyone else from using that GUID. This means that as you ship updates, eventually nobody will be able to see your tray icon, because IconStreams will have marked your GUID as belonging to an old version of the app.

 All of this information is stored in the Obfuscated, Binary blob inside the `IconStreams` key in `HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify`. As far as we can tell, there is no way to remove this corrupt information using public APIs, or even undocumented APIs.

### What Slack does about it

We found about this problem way too late to be able to fix it via Electron, so we worked around it. On every startup, we run this block of code:

https://gist.github.com/paulcbetts/c4e3412262324b551dda

This parses `IconStreams` directly, looking for an entry that would break our tray icon. If it's found, we rewrite IconStreams, then kill Explorer.exe because there's no way to get it to reread this information. 

### What you _should_ do about it

This is obviously a bad approach. I'm going to remove the GUID code from Electron entirely, which will bring back the original bug (multiple entries in the tray preferences). We'll then use the C# code above to filter IconStreams on startup, but *not* kill Explorer, so while users might see one or two duplicate entries, they'll eventually clear out.

**Comment by felipecrs** [comment]
I know this issue is almost 10 years old, but I am facing this exact same problem after upgrading my application from Electron from 26 to 28.

And, as suggested by @anaisbetts, removing GUID from the tray icon indeed brings it back.

**Comment by felipecrs** [comment]
```console
[13988:0201/145554.280:WARNING:notify_icon.cc(62)] Unable to create status tray icon.
[13988:0201/145554.289:WARNING:notify_icon.cc(143)] Error setting status tray icon image
[13988:0201/145554.296:WARNING:notify_icon.cc(159)] Unable to set tooltip for status tray icon
```

**Comment by felipecrs** [comment]
I found out that if I change the GUID to something else than a previously used one by my application also soves the issue. So, I'm going to do that for now (https://github.com/felipecrs/clipboard-sync/pull/38).

**Comment by felipecrs** [comment]
Tested again with Electron 29.1.6. Same issue.
