### ISSUE TITLE
Request: Native Modal Progress Dialogs

### ISSUE THREAD

**Issue by KenPowers** [atom/electron#2470]
It would be great to have native modal progress dialogs, for example, this small screenshot I found on Google:

![image](https://cloud.githubusercontent.com/assets/174864/9176745/2a40085c-3f5b-11e5-9190-aea67eb8306f.png)

My use case would be for copying a file and showing progress while blocking the ~~application~~ UI.

**Comment by zcbenz** [comment]
This is no builtin progress dialogs on all platforms, it can only be implemented by rewriting with native components on each platform. Though I'm opposite of this, I don't think anyone would care to implement this too since you can very easily implement a much fancier one with HTML without blocking UI.

**Comment by davej** [comment]
I agree this does not need to be part of electron. Also, the [`<progress>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) element will match OS styling (at least it should, I'm not sure what chromium does) so that should do what you need.

**Comment by zcbenz** [comment]
I'm closing this as won't fix.
