### ISSUE TITLE
Documentation Request on running tests :memo:

### ISSUE THREAD

**Issue by quadrophobiac** [atom/electron#2477]
I am attempting to use electron for an exercise in prototyping an app and I am attempting to use test driven development in my learning.

On this commit I detail some of the hurdles I have encountered (https://github.com/theodi/edward-csvhands/commit/f9063980621fa85bc7fd2a2108c15c1145d33035) but it would be a great help to learn how to run the tests that are contained in this repo under spec/.

I have also used https://github.com/jprichardson/electron-mocha but when I employ that I get a message saying 0 passed, so I figure that method is not a sound way of running the specs

(using the emojis to apply some filters on this request)

**Comment by zcbenz** [comment]
Electron doesn't require or help how you run tests, it is no different from running any other browser based tests. I suggest asking the [forum](https://discuss.atom.io/c/electron) for help since many people have their own ways of running specs.

For running Electron itself's specs, you can look at the [Build instructions](https://github.com/atom/electron/blob/master/docs/development/build-instructions-mac.md) in docs.
