### ISSUE TITLE
Including some npm modules fails (in render process)

### ISSUE THREAD

**Issue by aslauris** [atom/electron#2506]
There are some npm modules which doesn't work in my Electron (v0.30.4 on OSX) app (in render process), e.g. lodash. When I try to include it using _require('lodash')_ it returns an empty object. There is the same issue with lokijs module.

I've noticed that these modules work fine if I'm using them in main (browser) process. Is there any way to use these modules in render process as well (without ipc)?

**Comment by aslauris** [comment]
I found that remote could be used as a workaround e.g.:
```
var remote = require('remote'),
loki = remote.require('lokijs');
```
Is it a good practice to use remote in this case?

**Comment by Ivshti** [comment]
@aslauris definitely not. Remote is an IPC, and using something such as lokijs through IPC defeats it's purpose and makes it a few times slower.

Please consider fixing the issue itself, which is most likely related to lokijs being confused by the presence of ``window`` global. You'll probably find it at window.lokijs (or whatever it's in-browser use case is), instead of it being returned from require.

**Comment by aslauris** [comment]
@Ivshti Thanks! You were right.
The problem was boilerplate which I'm using. It uses Require.js to include app.js (in main.html) that's why some modules were included via Require.js. Removing Require.js solved the issue.
