### ISSUE TITLE
dialog.showOpenDialog() filter : all files (*.*)

### ISSUE THREAD

**Issue by gjuchault** [atom/electron#2525]
Hi,

Looking at the `showOpenDialog`, I noticed that I can't add a `All Files (*.*)` filter.

(Edit) I did try each of theses separately :

```
filters: [
  { name: All files (*.*)' }
  { name: All files (*.*)', extensions: [] },
  { name: All files (*.*)', extensions: [ '*' ] },
  { name: All files (*.*)', extensions: [ '*.*' ] },
]
```

(none of thoses four ways works).
Is there any way to do that ?

**Comment by etiktin** [comment]
Extensions shouldn't include the `.` or the `*.` (e.g. `png` is valid extension name, but `*.png` or `.png` is not). So in your case you should use `*`, which does work (at least for me using 0.30.4 on Windows).
For example:
```javascript
function openDialogExample() {
	var remote = require('remote');
	var dialog = remote.require('dialog');

	return dialog.showOpenDialog(
	  remote.getCurrentWindow(),
	  {
		  defaultPath: 'c:/',
		  filters: [
			  { name: 'All Files', extensions: ['*'] },
			  { name: 'Images', extensions: ['jpg', 'png', 'gif'] },
			  { name: 'Movies', extensions: ['mkv', 'avi', 'mp4'] }
			],
		  properties: ['openFile']
	  }
	);
}
```

**Comment by gjuchault** [comment]
As I said, I did try the "*" filter.

In Ubuntu 15.04 this is not working

**Comment by etiktin** [comment]
Sorry about that. I misread your example.

At least now we know the issue reconstructs on Linux but not on Windows.

**Comment by gjuchault** [comment]
I did try every one of them separately; none of them seems to work. In fact; it act like if `*` was an extension
![image](https://cloud.githubusercontent.com/assets/678848/9378531/862cc5d2-4722-11e5-917a-8f5acd63332c.png)

**Comment by etiktin** [comment]
I think the issue is [this](https://github.com/atom/electron/blob/master/atom/browser/ui/file_dialog_gtk.cc#L168). It seems that no matter what the extension is, we add `'.'` to it. So instead of `'*'` you get `'.*'` which explains why it treats `*` as an actual extension and not a wildcard.
If this really is the issue, the fix should be really simple (add the `'.'` only if the extension is not `'*'`). 
I don't have access to Linux right now, do you want to try and fix it?

**Comment by gjuchault** [comment]
I did try :

```cpp
      std::string* full_extension;
      if (filter.second[j] == "*") {
          full_extension = new std::string(filter.second[j]);
      } else {
        full_extension = new std::string("." + filter.second[j]);
      }

      scoped_ptr<std::string> file_extension(full_extension);
```

which doesn't work either (did I do something wrong here ?) - even if that compile well

**Comment by etiktin** [comment]
The issue seems to be with gtk_file_filter_add_custom. According to the gtk docs you should use

gtk_file_filter_add_pattern for globs. So if the pattern is * we should use gtk_file_filter_add_pattern, for anything else use gtk_file_filter_add_custom.




The docs are at: https://developer.gnome.org/gtk2/stable/gtk2-gtkfilefilter.html#gtk-file-filter-add-pattern




Heres an example (taken from https://github.com/jwm-art-net/Petri-Foo/blob/master/gui/sample-selector.c):

  /* All files filter */

    filter = gtk_file_filter_new();
    gtk_file_filter_set_name(filter, "All files");
    gtk_file_filter_add_pattern(filter, "*");
    gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(chooser), filter);

**Comment by hokein** [comment]
I believe it's a bug on Linux. Looks like the dialog regards `*` as a normal character rather than a regex symbol

**Comment by Zhenya-Pervak** [comment]
It is possible to set file extensions only for media files?
something like as 'image/*', 'audio/*', 'video/*'
