### ISSUE TITLE
[Linux] LocalStorage not loading on subsequent runs

### ISSUE THREAD

**Issue by slothbag** [atom/electron#2526]
My app is using LocalStorage, and I know its working whilst the app is running but as soon as I shutdown the app and re-run it the LocalStorage is gone.

It appears even though the localstorage is working during a single execution lifecycle, nothing appears in the DevTools for "Resources".

I can see all the Chrome settings files, folders and DBs in the .config/app folder.

OS is Ubuntu 15.04, Electron v0.30.4 x64

Windows works fine.

**Comment by etiktin** [comment]
This might be totally off, but did you check the permissions for the folder to make sure everything looks good? You can also try to run it with sudo and see if that works. If it does, then the issue is permissions.

I may be wrong but from what I understand, Electron saves the `localStorage` to disk on exit only. So an issue with permissions or with an unclean exit (some uncaught exception), might explain why everything seems to work during execution but is not persisted to the next run.

**Comment by Imskull** [comment]
Chrome 42 mobile has a several bug:  localStorage items are lost when the
application is forced to close
<https://code.google.com/p/chromium/issues/detail?id=479767> , I don't know
if they are relative though.

**Comment by slothbag** [comment]
Strange, none of the "Resources" information was showing in the DevTools pane, so I rebooted into Windows and confirmed that it was showing all the LocalStorage in the Resources tab.. rebooted back to Linux and now LocalStorage and all the Resources information is working.

Thanks for everyones input.. Closing this issue.

**Comment by slothbag** [comment]
So looks like if you open an Electron app in linux, the first time the DevTools Resources pane works fine.  But if you close the app and re-run it again then the Resources pane is empty.

I tried loging out and logging back in again but it still would not work.

After rebooting I could see the Resources pane starts working again..

**Comment by slothbag** [comment]
Hard to pinpoint this. Closing issue for now.
