### ISSUE TITLE
A way using WebdriverIO?

### ISSUE THREAD

**Issue by LeMoussel** [atom/electron#2529]
Do you think is it possible to use [WebdriverIO](http://webdriver.io/guide.html) with Electron?

I can not find how to do, especially for manually specify how to connect chrome driver and where to find Electron's binary with WebdriverIO.

Some ideas?

**Comment by LeMoussel** [comment]
Here the solution : [WebdriverIO - Issue   #721](https://github.com/webdriverio/webdriverio/issues/721#issuecomment-133094413)

I could write documentation on on how using using Selenium and WebDriver with WebDriverIO.
But my English is poor ( I'm french :) )

**Comment by etiktin** [comment]
Glad you found a solution :) It would be cool if you add an example of how to use webdriverio to the existing selenium and webdriver document [here](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md). It would probably help someone down the road.

You might also want to check out selenium's Python bindings. Some people prefer them because you don't need to mess with callbacks and promises. There's an example of how to use the Python bindings with nw.js [here](https://github.com/nwjs/nw.js/wiki/chromedriver). I think the only thing you need to change to get it to work with Electron is to use Electron's chrome driver.

**Comment by LeMoussel** [comment]
Create PR [#2550](https://github.com/atom/electron/pull/2550)

**Comment by etiktin** [comment]
Awesome :+1:

**Comment by zcbenz** [comment]
Closed by https://github.com/atom/electron/pull/2550.
