### ISSUE TITLE
Fix inconsistent API styles

### ISSUE THREAD

**Issue by zcbenz** [atom/electron#2544]
Some APIs have inconsistent styles from the others, we should probably fix that (while keeping backward-compatibility).

Examples are:

1) `WebContents.printToPDF`

Should probably be renamed to `printToPdf`.

2) `clicked`, `right-clicked`, `double-clicked` of `tray` module

`clicked` => `click`.

3) `ipc` module on renderer

Should probably be renamed to `ipc-renderer` to avoid confusions. And in the renamed module, we can add a new `event` parameter in the event listener to make ipc APIs have same style.

**Comment by kevinsawicki** [comment]
> Should probably be renamed to printToPdf.

Atom used to use this style but then switched to a more `printToPDF` style to blend in better with DOM apis like `HTMLElement`, `CSSStyleSheet`, `documentURI`, etc. /cc @nathansobo

**Comment by etiktin** [comment]
Cheng, I agree :+1: . 
I don't think it really matters which style we use as long that it's consistent.

**Comment by nathansobo** [comment]
I'd very much prefer that we match the Atom and DOM APIs and use all capital letters for initialisms.

**Comment by zcbenz** [comment]
I'm :+1: on following Atom and DOM's conventions.

List of APIs need to change:

* autoUpdater.setFeedUrl
* BrowserWindow.loadUrl
* WebContents.loadUrl
* WebContents.getUrl
* NativeImage.createFromDataUrl
* NativeImage.toDataUrl
* webFrame.registerUrlSchemeAsSecure
* webFrame.registerUrlSchemeAsBypassingCsp

**Comment by bengotow** [comment]
If there are breaking API changes, I'd also like to see `BrowserWindow.getSize` and  `BrowserWindow.getBounds` return consistent types. (getBounds returns `{width, height, x, y}` while getSize returns `[width, height]` as an array). I think the "getSize / setSize" APIs should probably all deal with {width, height} objects.

**Comment by etiktin** [comment]
If we're talking about changing API styles for consistency, there's also the request in #2397. It talks about adding support for camelCase option names and camelCase event names everywhere. The current API is not consistent. In the `BrowserWindow` options object the keys are dashed (e.g. `min-height` instead of `minHeight`) while in other places like the `dialog` module the keys are all camelCase. The main issue with dash-case, is that it's annoying to write it in javascript because you must surround keys that contain hyphens with quotes and frankly it doesn't feel natural (see examples [here](https://github.com/atom/electron/issues/2397#issuecomment-126938500)).

We can implement support for camelCase everywhere while maintaining backward compatibility. So in the docs you will see something like:
`minHeight` (AKA `min-height`) - ...
To implement this we need something like the `cc2d` function from #2397, but for the C++ side, since we can't extend the native constructor using javascript (see #23). The function will be called once and convert the camelCase keys to dashed keys so everything will work as usual.
For events, it's probably possible to do it in the javascript/coffeescript side, since we just need to wrap the methods that pass an event name.
