### ISSUE TITLE
What is the level of ICU support?

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2563]
I am interested in using String.prototype.normalize() and noticed that this function seems to be functional in Electron 0.27.x. However when I use the related io.js version (1.6.3), normalize() seems to be a no-op. Thus, is Electron enabling ICU in io.js when building?

I am also asking because io.js 3.1.0 seems to release out of the box with small-icu enabled: https://github.com/nodejs/node/pull/2264

The level of ICU support in Electron should probably be mentioned in the docs at least.

**Comment by hokein** [comment]
Electron is using Chromium built icu, you can view the verified by running the script in https://github.com/srl295/btest402:

```
 "--------- Analysis ---------", 
 "* You have the 'Intl' object. Congratulations! You have the possibility of being EcmaScript 402 compliant.", 
 "* Klingon isn't a supported language by the date formatter. It is without honor!", 
 "* The Maltese date format text looks bad to me. Doesn't have the right month. (This data is missing from the Chromium ICU build)", 
 "* You have Intl.v8BreakIterator support. (Note: not part of ES402.)", 
 "----------------", source: /Users/hokein/Downloads/btest402.js (135)
 "SUMMARY:Have Intl, Date:no 'tlh', Date:bad 'mt', FYI: v8Brk:have 'en', ", 
```

**Comment by paulcbetts** [comment]
Priority Zero bug: Klingon not supported Electron Language. Fix or be fated to journey on the barge of the Dead towards Gre'Thor.

**Comment by jorangreef** [comment]
@bpasero normalize() will work fine in Electron as well as in the latest Node binaries.

**Comment by zcbenz** [comment]
Electron uses the icu file from Chromium, the official io.js doesn't have icu enabled by default as far as I know. For all V8 related things you can expect Electron to behave the same with Chromium instead of io.js, since Electron is using the V8 provided by Chromium instead of the one bundled by io.js.

**Comment by zcbenz** [comment]
Electron uses the icu file from Chromium, the official io.js doesn't have icu enabled by default as far as I know. For all V8 related things you can expect Electron to behave the same with Chromium instead of io.js, since Electron is using the V8 provided by Chromium instead of the one bundled by io.js.

**Comment by bpasero** [comment]
Thanks guys.
