### ISSUE TITLE
Is the source really protected with building apps with Electron?

### ISSUE THREAD

**Issue by ashking** [atom/electron#2570]
Hey guys, 

This is not entirely a bug. 

I was wondering; are the apps built with Electron protects the source? I tried JxCore and it does not protect source. How about electron? 

Cheers

**Comment by zcbenz** [comment]
No, it is very easy to get your source code even when you packaged them in `asar` archive, the V8 JavaScript engine is never designed to hide source code. NW.js does succeed to hide one file of the source code completely, but with the price of significant performance downgrade.

So if you really to want to protect your source code, you have to write them in C++ and make a native Node module.

**Comment by etiktin** [comment]
There are some options, but the level of protection they provide is limited by the reasons @zcbenz mentioned:
- You could implement some decryption logic on your own, in a C++ node addon, but it will probably still be breakable (e.g. debug the program and copy the source after decryption but before eval).
- There's also [EncloseJS](http://enclosejs.com/), that claims to compile your code for node.js/io.js, so it might work with Electron.
- [nw.js](https://github.com/nwjs/nw.js), which is a similar project, has support for v8 snapshots which provide some kind of protection (see details [here](https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot)).

Note that all of this methods, will incur some performance penalty.

**Comment by fritx** [comment]
@etiktin I'm running into this too.
Is it possible to just apply node.js code in C++ addon directly?

**Comment by etiktin** [comment]
@fritx, Node has a module called vm which can eval code. I guess you could find a way to call it or it's underlining C++ API from your addon and use that to load your code. 
Keep in mind that the user could still manage to open the developer tools and see the loaded script. Even if you manage to block that using a custom Electron build and the addon checking to see that your Electron build wasn't tampered with, the user could still see your code as a string in memory.

**Comment by fizzvr** [comment]
Sounds good protect the source! :key:

**Comment by alexis57** [comment]
Then I have a question, how closed code electron app such as GitKraken, Whatsapp or Slack can hide the code ?

**Comment by Hum4n01d** [comment]
@alexis57 I have the same question; maybe it’s just that inspect element is disabled or something

**Comment by alexis57** [comment]
Or maybe the main code comes from a C/C++ library and then they use electron just for the GUI, don't know...

**Comment by nabtron** [comment]
Would like to know how whatsapp and slack protect their source code too

**Comment by boeserwolf** [comment]
AFAIK it's simply not protected. You can extract their app.asar and access the source code. For sensitive parts of the application you usually write custom node modules in a compiled language like C/C++ as suggested above.

**Comment by nabtron** [comment]
How can we compile c++ code in it?

**Comment by boeserwolf** [comment]
See: https://nodejs.org/api/addons.html

**Comment by nabtron** [comment]
@boeserwolf thanks! :)

**Comment by vasyl-shumskyi** [comment]
Subscribed

**Comment by alexis57** [comment]
It's also possible with `node-ffi`. Electron should be used only for the UI.

**Comment by bsclifton** [comment]
It might be worth exploring writing the code in C/C++ and then using a tool like [emscripten](https://kripken.github.io/emscripten-site/) to convert it to web assembly.  This should work great with Chromium

Anything can be disassembled / unobfuscated with enough effort. Writing your code in JavaScript and having it included in the ASAR would keep the majority of people out.  Is there a reason for protecting the code that copyright / licensing doesn't cover?

**Comment by craftpip** [comment]
My 2 cents here, NW seem to solve the problem of v8 snapshots
https://nwjs.io/blog/js-src-protect-perf/

I came across this article from nwjs, "compiled binary code now run as fast as JS source code without performance overhead" which was 30% previously, and it will be turned on by default in the later release of NW.

**Comment by ConsoleTVs** [comment]
Really interested in this, I also red the article @craftpip told us and seems to be rather interesting. If electron had code protection (even if it was slower at user-end) this will make a lot of developers feel safe and confident while writting their applications. Give it a chance electron team ;)

**Comment by ianli-sc** [comment]
It's too uncomfortable for developers. Give up and switch to NW...

**Comment by baszczewski** [comment]
I would like to share other node.js project which use code protection in very elegant way: https://github.com/zeit/pkg

Maybe there is hope for source protection in Electron?

**Comment by JohnWeisz** [comment]
In addition to using C++ for some parts, you can also minify and _obfuscate_ your JavaScript source (e.g. using [javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator)).

Minification and obfuscation together will _dramatically_ increase the required effort (and thus _cost_) to "steal" your code, often up to the point that reverse-engineering your entire application from scratch easily becomes much more feasible, and there is _nothing_ you can do about that, even if you go full-native (nothing, besides seeking the law).

**Comment by rocketlaunchr-cto** [comment]
If you're not worried about hiding your source code BUT you do want to hide your secrets such as:

- OAuth credentials
- URLs not intended to be known to the public (i.e. private backend API endpoints)
- REST API credentials
- Any Keys and Secrets
- Passwords

I've created a FREE service to address this issue. I had to make it because I was making a commercial electron app and was worried about having my credentials stolen.

It works by creating a cross-platform helper application which launches your **actual** electron application IFF your application has not been tampered with. Once it launches the application, it will pass your credentials through the environment variables.

More information:

**Introduction:**
https://medium.com/@rocketlaunchr.cloud/introducing-electron-vault-d09ade2c2020

**Documentation:**
https://rocketlaunchr.github.io/electron-vault-docs/

**Comment by JohnWeisz** [comment]
@rocketlaunchr-cto 

Ambitious project, but with all due respect, this should be treated the same way as obfuscation, i.e. unsafe from a hard-security perspective. If the data is _indeed_ sensitive, I think it should be handled by a remote server.

**Comment by rocketlaunchr-cto** [comment]
@JohnWeisz 
```
If the data is indeed sensitive, I think it should be handled by a remote server.
```

How does the remote server server truly know that the client is actually your unaltered Electron App?
That's the problem I was trying to solve.

If you use OAuth with the `Client Credentials` grant type, then your `client_secret` is still baked into your application and anyone can in theory read it.

There is no 100% fool proof way to solve the problem but I believe my solution comes close.

**Comment by Geowan** [comment]
I believe this is possible by building your JS apps with webpack or SPA framework like angular2/4/6 or vuejs2. this minify your code and its painstaking even though one extracts the asar file it may be hard for them to read your code

**Comment by tulpn** [comment]
I think the issue should not just focus on the actual encryption. But on the fact, that no other application/user has tampered with the source code of the client. 

By having a signed asar archieved or similar binary from which the source code is loaded would allow electron to check the integrity of the file. Since the integrity check could be integrated in the electron binary itself, there would not be an overload in the javascript code. Basically on build the electron could get a flag --include-integrity-check, otherwise the normal way of doing it is compiled.

**Comment by JohnWeisz** [comment]
@tulpn 

 > Since the integrity check could be integrated in the electron binary itself, ~~there would not be an ...~~

-- then it's already only a matter of extracting whichever integrity-checking or encryption/decryption Electron does. I'm convinced obfuscation is the only approach you can take here (be it minification, minification+obfuscation, or native code compilation), or moving some of your app code into a remote service.

**Comment by abhikhatri** [comment]
You can encrypt your data and decrypt it on runtime and load it directly into variables like tokens or any kind of sensitive data but if you're talking about encrypting whole javascript files then it will take a toll on performance. You can give a shot to [Node C++ Addons](https://nodejs.org/api/addons.html) 

As nodejs says it:

> Node.js Addons are dynamically-linked shared objects, written in C++, that can be loaded into Node.js using the require() function, and used just as if they were an ordinary Node.js module. They are used primarily to provide an interface between JavaScript running in Node.js and C/C++ libraries.


Basically it compiles your code into binary and that way you can abstract your code and performance will be alot faster and you can hide your code to some extent.

**Comment by annymosse** [comment]
> No, it is very easy to get your source code even when you packaged them in `asar` archive, the V8 JavaScript engine is never designed to hide source code. NW.js does succeed to hide one file of the source code completely, but with the price of significant performance downgrade.
> 
> So if you really to want to protect your source code, you have to write them in C++ and make a native Node module.

how can i disable devtools from c++ addons and how can i access all of the API of electron from c++ addons and is there any plan to package an app without the devtool this may helpfull to prevent the hacks and with less size of the application (@zcbenz )

**Comment by ahmtcn123** [comment]
We all tired of our sourcecode gets published.  Im moving to nw

**Comment by martpie** [comment]
@ahmtcn123 How is your comment helping solving this problem?

You want to build apps with web techs that by essense have their source code public, so stop with that attitude.

- You can contribute to Electron to fix this problem
- You can move to another similar tech, or you can go native
- Minify / obfuscate / mangle your code
- A few other solutions has been shared here, you can trade obfuscation for performances (which is a not a so evident choice to make when we know the terrible performances/resource consumption of web techs)

cheers!

**Comment by zacharyzh** [comment]
Why not support v8snapshot?

**Comment by jayantnd** [comment]
I understand we can not completely protect the source code. but another way can be creating web service for protecting logic code and calling from electron UI through localhost.

**Comment by ourfamilygithub** [comment]
the last word

NW

**Comment by z1988hf** [comment]
why was this issue closed?

**Comment by kidandcat** [comment]
Because hidding source code has been always a controversial topic because it is considered [Security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity) a very bad method to protect your code.

If you want some protection, use more standard methods, like authentication to perform critical actions, encryption, and so on.

Sincerely, you can write your app on C and distribute binaries, we will get your source code anyway.

**Comment by turd-afk** [comment]
> """PD: you can access the source code of the big boys (whatsapp web, slack, teams, vscode) and none of them care about it, maybe you are doing something wrong."""

One can hardly make a dumber argument.

Selling software without wanting it to be reverse engineered and used in ways it's not supposed to isn't abnormal, in fact there are laws exactly for that, which doesn't stop users from still doing it.

**Comment by ConsoleTVs** [comment]
@kidandcat 

> Sincerely, you can write your app on C and distribute binaries, we will get your source code anyway.

Go on, get the source of all the top selling apps like Microsoft word, Photoshop, or even top selling games. Are you a billionaire and I'm unaware of it or what?

**Comment by kidandcat** [comment]
> @kidandcat
> 
> > Sincerely, you can write your app on C and distribute binaries, we will get your source code anyway.
> 
> Go on, get the source of all the top selling apps like Microsoft word, Photoshop, or even top selling games. Are you a billionaire and I'm unaware of it or what?

No lol, I'm not billionaire because having the source code of those programs is useless, what are you going to do with it?

**Comment by martpie** [comment]
Guys please, there are **a lot** of people in this thread who get notified for each comment, please keep in constructive.

**Comment by JohnWeisz** [comment]
To possibly summarize why having to deal with the source-code peculiarities of JavaScript isn't a deal-breaker in many cases:

 - A lot of example apps/services listed here are driven largely by their _traction_; take Twitter for example, it isn't exactly a mystery how it is working internally, but even by fully copying it and reproducing it in its entirety won't get you anywhere without the traffic, the advertising, the brand, the backing infrastructure, etc.
 - Proper obfuscation makes it extremely, _prohibitively_ difficult to access the source code in any meaningful fashion, to the point where it becomes much more feasible to simply observe the behavior of the application itself and reverse-engineer it based on that, without relying on the original source code
 - Stealing ideas and/or solutions from an application protected by copyright law is a legal question, not a technical one, and as such, protecting the implementation is a legal affair, regardless of the level of protection implemented; a fishy Chinese firm will steal your logo and app without problems, regardless of whether it was written in JavaScript or Assembly

**Comment by martpie** [comment]
@JohnWeisz said a lot of really sensible things. I will also add that if it is not enough for you, you can use WebAssembly today. In terms of protecting source code, that should be quite good.

https://developer.mozilla.org/en-US/docs/WebAssembly

**Comment by z1988hf** [comment]
> Because hidding source code has been always a controversial topic because it is considered [Security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity) a very bad method to protect your code.
> 
> If you want some protection, use more standard methods, like authentication to perform critical actions, encryption, and so on.
> 
> Sincerely, you can write your app on C and distribute binaries, we will get your source code anyway.
> 
> PD: you can access the source code of the big boys (whatsapp web, slack, teams, vscode) and none of them care about it, maybe you are doing something wrong.

Is it true? I searched on google, seems it is impossible to get source code out of binaries compiled from C/C++. At most, we can get assembly statements.  "Sincerely, you can write your app on C and distribute binaries, we will get your source code anyway."

**Comment by JohnWeisz** [comment]
@z1988hf 

 > seems it is impossible to get source code out of binaries compiled from C/C++. At most, we can get assembly statements

What that really means is that you can pretty much reverse-engineer the original source code, or something equivalent, only it's usually prohibitively difficult and thus expensive. The same can be said about obfuscated code.

**Comment by kidandcat** [comment]
> @kidandcat Is it true?"Sincerely, you can write your app on C and distribute binaries, we will get your source code anyway."
> 
> I searched on google, seems it is impossible to get source code out of binaries compiled from C/C++. At most, we can get assembly statements.
> 
> I am developing a commerical windows desktop software. Code logic is key competence. These logic has to run on client side but I don't want my competitors to get it. So code protection is deal breaker in my case.

Also assembly is code mate, your logic will be there. You will need to do more things to protect your code than just compiling it. (but as @JohnWeisz said, reverse engineering software is very expensive, so you will not need to worry if your competitors are not interested in throwing some thousands of dollars just to try it)

**Comment by yourfavorite** [comment]
For those that are referencing apps like Slack as not caring about source code protection, that’s not the best comparison for all apps. Slack is a service that lives online and their electron app is just a shell for displaying their web app. The majority of the secret sauce of apps like slack lives on web servers.

**Comment by annymosse** [comment]
> For those that are referencing apps like Slack as not caring about source code protection, that’s not the best comparison for all apps. Slack is a service that lives online and their electron app is just a shell for displaying their web app. The majority of the secret sauce of apps like slack lives on web servers.

how about spotify !!!,we know what do you mean but how about the offline apps??

**Comment by yourfavorite** [comment]
@annymosse Spotify's secret sauce is not their app. If someone stole the Spotify app source, it wouldn't really matter. The app is good enough. The real reason people use and pay for Spotify is because of the content offering and the convenience of streaming music. There are some UX details that are probably preferred to alternatives by many of Spotify's customers but competitors don't really need the source code to copy that. Additionally, I haven't attempted to look at Spotify's source code, but I'd imagine they have some sort of protection built into the app somewhere. Likely some solid obfuscation as well as native C addons. I think this would be a requirement for them due to DRM.

**Comment by annymosse** [comment]
@yourfavorite just take a look at them source ,put in your mind sometimes we're not hidding our source for commercial apps , we do that to prevent our services far than hackers which they get some weak lines,anyway we just need this feature if there's an ability to do that ,at least some method to pass the `asar files` and the `package.json` and `*.js`

**Comment by yourfavorite** [comment]
I’m not arguing against source code protection, but rather that Slack and Spotify likely aren’t the best comparisons for what most people are doing with electron. Additionally,  if source code protection is critical for your product, then perhaps electron is not the best fit at this time.

And to be clear, I’m in favor of source code protection of some kind coming to electron.

**Comment by 1c7** [comment]
let me provide a use case here:
I am trying to build a translation software base on Google Translate API。
User drag a .srt/.ass subtitle file into the software, and the software would use Google Translate API to translate every single line.

Problem: If source code is easy to get. apparently attacker could get my API key&secret. and abuse it. and I would get a massive bill from Google.

**Comment by lvkins** [comment]
@1c7 

Well, perhaps you should be using some external protection to achieve this. I could easily grap your API key from a C++ software as well, no problem. So this is not really an electron specific issue.

**Comment by 1c7** [comment]
@lvkins  oh I see. I didn't know C++ software have this problem too. I am not familiar with this language.
Thanks for the tips!

**Comment by lvkins** [comment]
Basically every programming language can be reverse engineered. It always was a big concern. True that any protection is better than no protection, but still; we need to put some extra effort to protect the sensitive data.

**Comment by 1c7** [comment]
@lvkins You are replying to me right?
Thanks for the suggestion. I would investigate into this.

I want to use Electron.js because I want this translation software to be able to run on both Mac & Windows.

Seem like Electron.js + some C++ could protect my API key&secret

Thanks @lvkins

**Comment by lvkins** [comment]
Indeed 😃

Start here: https://nodejs.org/api/addons.html

If electron's total lack of security concerns you, you could also give NW.js a try.

Good luck!

**Comment by annymosse** [comment]
@1c7 and why not Linux?!! i think it's same code-base to all the platforms right??!

**Comment by 1c7** [comment]
@annymosse I just forgot to mention Linux, nothing against Linux

**Comment by annymosse** [comment]
i had a plan to create i18n & Yandex translator API but coz of the same problem i canceled the project , then on Linux most of the newer users haven't a confidence of the programs which they think it's not exist in Linux or there's no alternative so if you create that project and your users targets only translate the media they can use any Linux disto or my preferred distribution deepin (Chinese Linux distro), hope the best to you and all the Linux users.

**Comment by paulovitorjp** [comment]
Your API keys & secret should never be in a published app. Instead have
them on your APIs/backend, abd protect them with some type of
authentication/throtling. Then have your app consume your APIs.

Em dom, 20 de out de 2019 10:22, Cheng Zheng <notifications@github.com>
escreveu:

**Comment by dotbloup** [comment]
There is a library called bytenode which allows you to convert your Javascript files into binary files so that noone can read it.

[](https://www.npmjs.com/package/bytenode
)
First install bytenode on your server and in your folder:

```
>npm i -g bytenode
>npm i bytenode
```
Create a normal nodeJS file with the following code in it. Let's imagine we name the following code: ok.js

`>console.log('bytenode works!);`
Then, compile your javascript code. The command will create a .JSC file with the same name than your file.

`user@machine:~$ bytenode -c ok.js
Then, in a main JS file, you will call your binary, let's call it test.js:

```
const bytenode = require('bytenode'); 
const myFile=require('./ok.jsc'); 
myFile;
```
Save it.

Then, you will call test.js: node test.js to test it. Do a "cat ok.jsc" to see that it is really a binary and that nobody can't see your code. You can move your original plain test js file to another location.

**Comment by JohnWeisz** [comment]
> There is a library called bytenode which allows you to convert your Javascript files into binary files **so that noone can read it.**

No one will be able to read the original source, that's true (just as with obfuscation or even minification), but you still can't store any app secrets or other sensitive data in your code, because it can still be reverse engineered and/or extracted just the same, it's only a matter of time.

If you want to make it harder to inspect or "steal" parts of your source code, this is a great tool to make it _harder_ (and in many cases, prohibitively difficult). However, do not use it for any sort of real security.

**Comment by dotbloup** [comment]
@JohnWeisz 
I would love to see a proof of someone breaking the code of a V8 bytecode binary file. I have developped an application with nwjs and i converted the engine in a bin file using nwjc which is exactly the same as bytenode. This application is the Sitecozy broken link checker and it is available on the microsoft store for free. 

I propose a challenge. 
If anyone can break the code of the bin file of my app and send me the functions & the methods of my bin file, I would give you 150 euros. No need to recreate the code to provide the same effect, No need to show me my variables or my JSON messages, I am not stupid. 

you can write to me at        stepsahe AT hotmail DOT com

**Comment by JohnWeisz** [comment]
@dotbloup 

I mean people usually break copy protection systems in machine code compiled from C++ in a matter of weeks usually, and for decades now. Point is, if the piece of information is there for the machine, it'll be there for the user to break it open as well.

The only way to securely store app secrets is a sealed system, such as a backend service.

**Comment by MelerEcckmanLawler** [comment]
> ### Problem
> If source code is easy to get. apparently attacker could get my API key&secret. and abuse it. and I would get a massive bill from Google. ($500? $1000? $10000? who knows)

Your app should send text to your server, which then forwards it to Google, receives the translation, and sends that back to the app.

You should have your own server acting as a middleman between your customers and Google's translation service, and only your server should have your API key.  

It's probably against Google's terms of use to share your API key anyway.

**Comment by annymosse** [comment]
> > ### Problem
> > If source code is easy to get. apparently attacker could get my API key&secret. and abuse it. and I would get a massive bill from Google. ($500? $1000? $10000? who knows)
> 
> Your app should send text to your server, which then forwards it to Google, receives the translation, and sends that back to the app.
> 
> You should have your own server acting as a middleman between your customers and Google's translation service, and only your server should have your API key.
> 
> It's probably against Google's terms of use to share your API key anyway.

alright for commercial project, which provide a resource money to handle the service costs and its team maintenance, but we need a source protection for open source projects such tools , at least to keep it hard to debug it and make some black hacks.

**Comment by m4heshd** [comment]
Gave up on Electron for a while thinking that this issue would be solved years back. Still no solution? Very disappointing. I wish i had the time to put in so i can come up with my own solution for this. 😟

**Comment by ahmtcn123** [comment]
> Gave up on Electron for a while thinking that this issue would be solved years back. Still no solution? Very disappointing. I wish i had the time to put in so i can come up with my own solution for this. 😟

Its impossible to hide the js code. Even if you separate every function to single file and obfuscate it, as long as files are on client computer it can be reverse engineered. But you can support your app with server

**Comment by lukaszog** [comment]
There is something news about protect source code in Electron? I'm was hearing about https://www.npmjs.com/package/bytenode anyone use this library?

**Comment by charlesr1971** [comment]
If you use Angular Electron, the Angular part is converted into Vanilla JavaScript and obfuscated, automatically. It is pretty much unreadable. :)

**Comment by m4heshd** [comment]
@charlesr1971 Meanwhile obfuscation is an option, it's not very effective. Obfuscated code is easily traceable using various tools. Speaking from experience because I constantly write mods for applications and by this point, it has become quite effortless. Heavy obfuscation however, including string encryption is very effective. But the performance hit becomes unbearable. Especially for HTML UIs since it's already very clunky. Comparing this to compiled code, it's a no-brainer that the latter is way more advantages on every aspect. Also you don't need to have Angular. Setting up obfuscation with Webpack is extremely easy.

```js
const WebpackObfuscator = require('webpack-obfuscator');

// webpack plugins array
plugins: [
    new WebpackObfuscator()
]
```

Even a beginner dev knows that the decompilation is inevitable but I think what we all looking for here is merely some protection against layman end users. I don't want my code to be exposed just because some bored YouTuber learned how to extract an `asar` file. And binary files provide that while not losing any performance too. In some scenarios improving the performance too. NW.js is a great example for that.

**Comment by charlesr1971** [comment]
> **NW.js** is a great example for that.

I had a look at **NW.js**, but I don’t quite understand what it does? It says that it allows one to use node modules in the DOM? 

But how does it protect our source code? I am using Angular with Electron. Can I integrate **NW.js** with this environment?

**Comment by charlesr1971** [comment]
@m4heshd Because of this code protection issue, I am thinking about putting my application online. I want to place **ipcMain** on the server and **ipcRenderer** will be the client. 
My question is, does the **invoke** method, which links **ipcRenderer** with **ipcMain**, use XHR? 
So, could I continue to use this protocol to connect client with server. 
Although, I have a lot of server side development experience, I haven’t used NodeJs, much. Coldfusion [cfml] is my language of choice. 
However, I don’t want to rewrite all of my **ipcMain** code, so I would like to use it as my server side application. 

Could you suggest how I can convert my Electron app into client server model? Thanks 🙏

**Comment by m4heshd** [comment]
> But how does it protect our source code?

Read [this documentation](https://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/). Electron does have something similar called "V8 snapshots" which is a part of V8 engine but it's not exactly similar. It's extremely difficult to adapt to, no useful documentation and could result in development and production state of the app behaving very differently.

> Can I integrate NW.js with this environment?

Yes you can but beware that NW.js lacks the massive and active support system Electron has. Hence the less popularity. It has to do with not having a proper, up-to-date build suite, having to deal with the pain of building native modules with `nw-gyp` and more stuff like that.

> I want to place ipcMain on the server and ipcRenderer will be the client.

Technically, you cannot "IPC" over the internet. For that kind of communication, you have to implement some kind of a REST API specific for your application. 

> does the invoke method, which links ipcRenderer with ipcMain, use XHR?

No. It's a completely different, native implementation included with Chromium.

> Could you suggest how I can convert my Electron app into client server model?

I'm sorry I can't help you with that because it completely depends on your application's structure and process.

**Comment by annymosse** [comment]
> Could you suggest how I can convert my Electron app into client server model? Thanks pray
 @charlesr1971 you should migrate your heavy code (source which you want to protect) into a server
 and connect with it through RestAPI or GraphQl or render your html from it if you wish too, or you could use native modules and load your modules from your electron (however it's not too much useful since the hacker/cracker still have your source code)and can use your modules too

**Comment by charlesr1971** [comment]
@annymosse How is a hacker going to get hold of the NodeJs code on my server? Yes. The hacker can inspect the Anguler client side code, but that is useless without the NodeJs part. 
Converting this to a client server model is definitely the way to go. 
The Electron engineers really need to implement code protection. This issue is a real disappointment. :(

**Comment by annymosse** [comment]
> How is a hacker going to get hold of the NodeJs code on my server? 

I didn't say hacker can get your code at server side, however it can if you have a bad security structure.
Electron team can't make the silver bullet, after all there's no way to eliminate the crackers (reverse engineering) even avast, Kaspersky antivirus couldn't be safe, so the solution is to keep your code between your hands at server side and provide API then invest your money to keep your servers safe against the hackers instead the crackers.
If you need as "almost of us" need extra shields to keep your source code secure and perform well against these curious newbie users is to use native add-ons through N-Api & CPP,C or Rust; then obfuscate the rest "lightweight" part of your code.
For my own prospectives I prefer to see Electron more modular , FTP(S) stand alone module, WS(S) module,.... By this way the developer can load only the required modules and ship it's heavy important part as a native part belong to electron itself and the cracker can't make a single solution to crack all electron project since they're different, and the the project will be much more light and performing so well, and for the team at first time it will be a huge hard path to walk through, however at the end the project can stand alive forever as a modules instead a single huge hard project, and they can maintain it easily and can get more contributers even the chromium team might switch into electron structure because it's more cleaner and lighter.

**Comment by annymosse** [comment]
> How is a hacker going to get hold of the NodeJs code on my server? 

I didn't say hacker can get your code at server side, however it can if you have a bad security structure.
Electron team can't make the silver bullet, after all there's no way to eliminate the crackers (reverse engineering) even avast, Kaspersky antivirus couldn't be safe, so the solution is to keep your code between your hands at server side and provide API then invest your money to keep your servers safe against the hackers instead the crackers.
If you need as "almost of us" need extra shields to keep your source code secure and perform well against these curious newbie users is to use native add-ons through N-Api & CPP,C or Rust; then obfuscate the rest "lightweight" part of your code.
For my own prospectives I prefer to see Electron more modular , FTP(S) stand alone module, WS(S) module,.... By this way the developer can load only the required modules and ship it's heavy important part as a native part belong to electron itself and the cracker can't make a single solution to crack all electron project since they're different, and the the project will be much more light and performing so well, and for the team at first time it will be a huge hard path to walk through, however at the end the project can stand alive forever as a modules instead a single huge hard project, and they can maintain it easily and can get more contributers even the chromium team might switch into electron structure because it's more cleaner and lighter.

**Comment by charlesr1971** [comment]
@annymosse Well. NW.js seem to be able to achieve full protection. Why can’t Electron implement something like this? The only reason, I won’t use nw.js, is that we have to convert all node modules to binary etc. But, this process could be automated.

**Comment by m4heshd** [comment]
@charlesr1971 As I've said earlier, decompilation and deobfuscation is inevitable. There's no actual way of completely protecting client side code. Only the means of making it harder to do so. I'll simply put it as this. If your CPU can read the instructions, so can the user. That's all there's to it. Only way to have it protected is to have as much of the functionality at server-side as possible. But users could still have access to your backend APIs. So API abuse is also something to be worried about.

**Comment by annymosse** [comment]
> NW.js seem to be able to achieve full protection.

There's no full code protection when your app become at the user end desktop, he/she can crake it and use it for free, if you're looking for a solution you should use node add-ons which much more faster smaller size then these `.bin` files , it's true that when you compile your js code using `nwjc` you don't need to use other low level language but you'll keep facing same issue "your software will be craked"

**Comment by charlesr1971** [comment]
@m4heshd Are you saying it is possible to reverse engineer compiled C++ or Java? I think this is very difficult to do and what is impossible is to reverse it to the original source code, because there is no 1:1 relation between the machine code and the source code..
So, what I am saying, why can’t the Electron team convert the JS to machine code.

**Comment by charlesr1971** [comment]
@annymosse I think what I am saying, is electron should try and provide as much protection as any piece of software that is compiled to machine code, within an executable, affords. Obviously, any piece of software can be cracked, if you throw  enough resources & expertise, at it. But, most software users, won’t try and reverse engineer machine code.

**Comment by thecutefinder** [comment]
> and why not Linux?!! i think it's same code-base to all the platforms right??!

@annymosse 

I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

**Comment by annymosse** [comment]
> > and why not Linux?!! i think it's same code-base to all the platforms right??!
> 
> @annymosse 
> 
> I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.
> 
> Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.
> 
> There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

thank you for your note, It's true that much better we use the correct name for right thing, It's fact Linux (the kernel) became the name of OS which ment to be controlled by GNU, however the alternative of Linux (monolithic) is Hurd (microkernel) which have slow development, and less contributors.
The successful key still until now the performance and stability and for this reason Electron is much more attracting developers more than other hybrid technologies (NWJs), and the current path of Electron not providing bright future compared to other projects, flutter and some new shiny rust's solutions, rust itself provide security, performance, stability and productivity so the developer can focus on securing it's project much safer without sacrificing the performance and providing modular solution, just consume what do you import, and crackers wont get same structure (libraries, folders, constant files,...), it became much harder to predict which framework, programming language....
