### ISSUE TITLE
Access ffmpeg methods?

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#2588]
With the latest release of electron I see that ffmpeg is now statically linked and no longer needs to be distributed, which is very convenient (thank you!).

On this note, is it possible for me to use electron to access ffmpeg to do jobs, e.g., invoking something like "ffmpeg -i input.mp4 output.avi"? Invoking ffmpeg with API calls rather than the command-line approach would be even better.

This would be very cool and would pave the way for some fun ideas I have

**Comment by zcbenz** [comment]
We only bundled the library version of ffmpeg, not the command line version.

**Comment by zcbenz** [comment]
Also providing JavaScript API for the bundled ffmpeg is possible, but I don't think we will ever do that because of limitation of resources.

**Comment by kirkouimet** [comment]
@zcbenz a JavaScript API for the bundled ffmpeg could be really fun - a couple of quick questions:

1. Does the library version of ffmpeg allow you to do everything the command line version can?
2. If I were to do some research into contributing code for the JavaScript API to the bundled ffmpeg, which files are my best starting point?

Thanks!

**Comment by zcbenz** [comment]
I don't have experience with ffmpeg, you can probably look into existing Node bindings of ffmpeg.

**Comment by frankhale** [comment]
A quick search of npmjs.com reveals a lot of node modules for ffmpeg. Would any of these be suitable for your needs? 

https://www.npmjs.com/search?q=ffmpeg

**Comment by cplumier** [comment]
Unfortunately no because they are based on the command line tools.

**Comment by benkaiser** [comment]
agree with @cplumier here. Would be great to have the command line tools bundled too as they are used by all the npm ffmpeg libraries!

**Comment by gabrielstuff** [comment]
Anyone know commercial project using ffmpeg and respecting all the information here:
https://www.ffmpeg.org/legal.html

**Comment by vot** [comment]
I know this is more than a year since the original question got asked but I just got around to solving this for myself.
I was looking for the answer to this a while ago and now I decided to put something together myself and thought I'd share. It's packaged as a module so you can just add it to your project as a dependency.

*Disclaimer: This is a shameless plug for [ffbinaries][1] Node module and [ffbinaries.com API][2] I created.*

I simply repackaged existing builds by other people into individual packages for consistency and uploaded to GitHub. I created an API and a [downloader module][1] to integrate this into my project. I just started this two nights ago so might be still lacking but give it a try.

You can include it in your build, it can be used from Node scripts or through CLI.

[1]: https://www.npmjs.com/package/ffbinaries
[2]: http://ffbinaries.com

**Comment by benkaiser** [comment]
@vot you are a legend! Now I can stop shipping binaries with my builds and install them at runtime for users of my software only if needed!

**Comment by tconroy** [comment]
@vot this looks great. Thank you for creating/sharing!
