### ISSUE TITLE
Rename or alias the 'ipc' modules into two different names

### ISSUE THREAD

**Issue by sedwards2009** [atom/electron#2600]
The 'ipc' module in electron is actually two different modules depending on whether it is imported from the main process or from a window/render process. When using TypeScript with electron, all of the files in an application are typically compiled at the same time by one invocation of the compiler. Having multiple and conflicting type definitions for the ipc module causes errors.

This problem can be solved by renaming the ipc module with two new names, one for the main process (i.e. 'ipc-main') and another for render processes (i.e. 'ipc-window').

**Comment by paulcbetts** [comment]
While this is unfortunate, it also is a breaking change, I'd rather create `ipc-main` and `ipc-window` and have them be aliases of `ipc` (perhaps blowing up if you use the wrong one in the wrong context)

**Comment by zcbenz** [comment]
Refs #2544.

I'm :+1: on adding new `ipc-main` and `ipc-window` modules while keeping the old `ipc` for compatibility. And in the new `ipc-window` module we can also add a dummy `event` argument when emitting events to keep consistency with `ipc-main`, it is a good chance to fix that.

Also `ipc-window` is not a very good name since webview can also use it, maybe using `ipc-renderer` instead?

**Comment by paulcbetts** [comment]
:+1: to `ipc-renderer` as long as we kill the "browser process" nomenclature in our docs, it confuses the fuck out of everyone

**Comment by sedwards2009** [comment]
Thanks for your responsiveness. Having this fixed will bring help straighten out my build. :smiley:

**Comment by sedwards2009** [comment]
excellent, thanks.
