### ISSUE TITLE
webgl textures in combination with an externalized arrayBuffer will crush electron

### ISSUE THREAD

**Issue by soliton4** [atom/electron#2601]
i am using a webgl canvas with textures in electron.

```
gl.texImage2D(gl.TEXTURE_2D, 0, gl.LUMINANCE, width, height, 0, gl.LUMINANCE, gl.UNSIGNED_BYTE, yData);
```

this works with a array buffers that were created in js.
however there is a way to create externalized array buffers in a node native module.

```
ret->Set(NanNew<v8::String>("yData"), v8::ArrayBuffer::New(v8::Isolate::GetCurrent(), (void*)pData[0], yLength));
```
the above code sets the property yData of a return object to a externalized array buffer.
i then do a new Uint8Array(yData) which works perfectly fine in js.

when i use this typed array to define the texture like in the first code example, electron crushes.

**Comment by zcbenz** [comment]
Unfortunately you can not use an ArrayBuffer created directly with V8 API in web pages, this is because blink has inserted custom C++ objects into ArrayBuffer for memory management, and it is expecting it everywhere.

This bit me deeply when upgrading io.js to v3.1.0 because io.js is also starting to do manual memory management for ArrayBuffer.

I'm not sure which version of Electron your app is using, but I suggest switching Electron to v0.31.0 and io.js to v3.1.0, and then use node::Buffer in place of v8::ArrayBuffer. In io.js v3.1.0 they have reimplemented Buffer as Uint8Array, and I have made efforts to make it work well together with blink.

Also you may want to upgrade NAN to its v2 version, which fixes compatibility issues with io.js v3.1.0.

This problem is quite unfortunate, but there is really no way to fix that, so I'm closing this as won't fix.

**Comment by mmakhalaf** [comment]
@zcbenz sorry to bring this up after such a long time. I was interested in what you did to make ArrayBuffers play nice with blink and web pages. CEF (Chromium Embedded Framework) has just added support for this, and I had a go prior to that, but the crash described here is still a problem there. This crash happens when the memory is extranalised, but a different crash also happens when it's owned by the AB. Any advice, references to docs, code or commits would be much appreciated.
