### ISSUE TITLE
Misunderstanding in the docs

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#2647]
Taking the text from [here](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md):

> In Electron's releases page you can find archives of chromedriver, there is no difference between Electron's distribution of chromedriver and upstream ones, so in order to use chromedriver together with Electron, you will need some special setup.

The two sentences disagree with each other. From what I understand `you will need some special setup` should be `you won't need some special setup`.

**Comment by zcbenz** [comment]
The chromedriver shipped in Electron is exactly the same with the upstream one, so by default it will only work for Chrome browsers instead of custom browsers like Electron. In order to use chromedriver together with Electron you have to tell it where to find Electron and makes it think Electron is Chrome browser.

Pull request to make the document clearer is welcomed.
