### ISSUE TITLE
Cannot child_process.fork() when inside ASAR

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#2708]
I am running into an issue where using `require('child_process').fork()` does not work when my app is compressed into an ASAR file (but it works fine when just deployed under regular `/app/` folder).

From what I can tell, the issue is related to the `cwd` for the child process -- because [per the Electron docs](https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md), ASAR is treated like a virtual directory. 

If I _do not_ define a `cwd` option on the call to `fork()` the my app launches but the child process never seems to do anything (but no errors are thrown). This works perfectly fine when not inside an ASAR:

    //spawn child_process
    var child = require('child_process').fork('./js/_launch.js', [], {
        // no options passed
        // I assume "cwd" is automatically set to the current directory (/app/, or /app.asar/)
    });

If I _do_ defined a `cwd`, I need to be very careful about what I pass to it -- otherwise I end up with ENOENT errors thrown (presumably because it's a virtual directory). Again, this works fine when not inside the ASAR:

    //spawn child_process
    var child = require('child_process').fork('./js/_launch.js', [], {
        cwd      : __dirname // /app/ or /app.asar/
    });

However, I did get the following working inside the ASAR:

    //spawn child_process
    var child = require('child_process').fork('app.asar/js/_launch.js', [], {
        // set cwd to one level above ASAR -- note the path to _launch.js has been updated
        cwd      : path.join(__dirname, '..')
    });

...but now I can't use this with `electron-prebuilt` because "app.asar" has not yet been generated (I do that during my build process).

Is there a better way to do this? I tried looking at this [old issue](https://github.com/atom/electron/issues/1613) but that didn't seem to solve my issue inside the ASAR.

**Comment by arthurakay** [comment]
This was my final workaround, in case anyone else hits this problem:

    if (fs.existsSync(path.join(cwd, 'app.asar'))) {
        cp_path = 'app.asar/js/_launch.js';
    }
    else {
        cp_path = './js/_launch.js';
        cwd = null;
    }
    
    //spawn child_process for backend server/license stuff
    var child = require('child_process').fork(cp_path, [], {
        cwd : cwd
    });

I would still like to know if there's a better/cleaner way to do this. I completely understand the virtual directory problem, but it seems like there should be a more elegant way to handle this.

**Comment by zcbenz** [comment]
It seems that `child_process.fork` handles relative paths differently from other modules.

**Comment by rbartholomay** [comment]
is there a solution for require('child_process').spawn available? In my app a module use this to start cscript.exe on windows. And this did not work when the script is inside an asar archive

**Comment by zcbenz** [comment]
After a closer look I'm closing this as won't fix.

The relative paths passed to `fork` are relative to _current working directory_ instead of your app's dir, so I have to assume in your app you have tried to switch cwd to your app's dir. However `app.asar` is a virtual directory and you can never switch cwd to it, your call of `process.cwd` failed silently but you are still passing `./js/_launch.js` to `fork`, which doesn't exist.

**Comment by marko-hologram** [comment]
@thiscantbeserious hey can you please elaborate more on some of these things?

> I solved the trouble and am able to keep everything besides the entryPoint.js within the app.asar now with the following code.

Does this require `node_modules` to be present next to entryPoint.js? Just looking at this code I guess it does because it requires `asar-node` on first line?

Is this the file and directory structure that you are mentioning here?
```
├── entryPoint.js
├── node_modules/
│   └── asar-node/
└── app.asar
```

Or are node_modules only in asar so it's like this?

```
├── entryPoint.js
└── app.asar/
    └── node_modules/
        └── asar-node/
```

I'm trying to wrap my head around this so any help is appreciated.
What I'm trying to do is call `child_process.fork` from Electron to spin up Express before fully starting the Electron app and obviously it's not working just like that 😄

**Comment by ecofi** [comment]
@marko-hologram did you solve your issue? I'm asking because I have the same approach, i.e. starting express from electron app in a separate process.

**Comment by marko-hologram** [comment]
> @marko-hologram did you solve your issue? I'm asking because I have the same approach, i.e. starting express from electron app in a separate process.

Sorry I cannot remember how far I got with this since it was a long time ago, but I think I didn't get it working as I wanted initially. In the end I realized I don't need to do this at all in my case. What my app had to do was load the same web UI that the web app has, but desktop app has to add few possibilities to interact with the OS. So in the end I didn't need to start a local server at all.

I did experiment with the code above, but just couldn't get my example to work. Starting the process should be easy, but accessing node_modules outside of app.asar is complicated if I remember correctly. Maybe not bundling node_modules inside app.asar is the way to go, but that makes the app larger and slower I think.

I did however had to "unpack" 7zip-bin from app.asar using `asarUnpack` property in `maker.options.json` (electron-builder config) so that I can access the binary on disk and pass it to a library to use as the binary for unzipping some files.

---

I'm guessing my case won't really help you, but I'll explain it anyway to explain what I mean when I said loading web UI with additional code.

So what I did was use `App.mainWindow.loadURL("https://example.com")` which would load my web app, but the deployed code had certain checks in code where it would be able to call functions exposed from Electron.

So I added all my custom actions to `globalThis.__MY_APP` and that would get exposed only when the Electron app is loaded, so those Electron actions would only be available in desktop app and not in the web app.

```ts
contextBridge.exposeInMainWorld("__MY_APP", desktopAppAPI);
```

This would allow me to do some checks in code and only run this in desktop app:

```ts
if (isDesktopEnvironment()) {
  globalThis.__MY_APP.doSomething();
}
```
