### ISSUE TITLE
e.preventDefault don't work on 'new-window' event?

### ISSUE THREAD

**Issue by metainfa** [atom/electron#2770]
I tested under Ubuntu 14.04 and Electron 0.31.2.
```javascript
  const win = new BrowserWindow({width: 960, height: 540});
  win.loadUrl(url);

  win.webContents.on('new-window', (e, url, frame, tab) => {
    e.preventDefault();

    console.log('URL =', url);
}
```

When i click middle mouse button, i get: new Window (e.preventDefault don't working) and url into console.

**Comment by zcbenz** [comment]
Does it work as expected if you click with left mouse button?

**Comment by metainfa** [comment]
Also don't work. 
```javascript
win.webContents.on('will-navigate', (e, url) => {
    e.preventDefault();

    console.log('URL =', url);
});
```
I click with left mouse button by link and go to  url  (e.preventDefault don't work).

**Comment by zcbenz** [comment]
Can you share a small demo app? I'm not able to reproduce with your code snippet, so I'm wondering if it is caused by other parts of your code.

**Comment by metainfa** [comment]
Ok.

**Comment by metainfa** [comment]
I make demo app this [link](https://github.com/metainfa/electron-new-window).

**Comment by zcbenz** [comment]
Calling `event.preventDefault` doesn't work in renderer process, because the callback is called asynchronously in renderer process and `event.preventDefault` has to be called synchronously. You can find detailed descriptions at http://electron.atom.io/docs/v0.32.0/api/remote/#passing-callbacks-to-the-main-process.
