### ISSUE TITLE
With BrowserWindow's fullscreen option set to 'false', the user can still make window fullscreen by pressing F11 on Windows/Linux.

### ISSUE THREAD

**Issue by ssreekanth** [atom/electron#2794]
```javascript
mainWindow = new BrowserWindow({
     width: 480,
     height: 640,
     resizable: false,
     fullscreen: false,
});
```

On Windows/Linux, fullscreen set to 'false' is not working as expected. Though the 'maximize' window button is disabled, pressing F11 toggles window fullscreen on/off.

**Comment by OlsonDev** [comment]
Try `mainWindow.setMenu(null);` after that. `F11` works because there's a menu item with a keyboard command bound to it.

**Comment by ssreekanth** [comment]
[setMenu()](http://electron.atom.io/docs/v0.32.0/api/browser-window/#win-setmenu-menu-os-x) seems to be applicable on `OS X` only, per documentation.

I did anyways try it on `Linux`, it worked, but then the entire menu was gone. I guess i need to define required menu items, and then, set the menu bar accordingly.

On a side note, with the same code,

```javascript
mainWindow = new BrowserWindow({
     width: 480,
     height: 640,
     resizable: false,
     fullscreen: false,
});
```
On `OS X`, I can't make the window fullscreen using the keyboard shortcut `Ctrl-Cmd-F`, which is expected.

Looks like there is some inconsistent behavior with respect to setting `fullscreen` option to `false`.

**Comment by OlsonDev** [comment]
`mainWindow.setMenu()` shouldn't be `OS X` only AFAIK. I think that's a typo due to confusion with  [`app.dock.setMenu()`](http://electron.atom.io/docs/v0.32.0/api/app/) (someone correct me if I'm wrong?).

Right, the entire menu was gone. Sorry if I wasn't clear enough -- there's a menu item with a keyboard command bound to it by default. So, removing the menu removes the keyboard command. You're right that you'll want to set up your own menu bar (or remove it if you so desire).

Dunno what to tell you about `Ctrl+Cmd+F`. :-\

**Comment by zcbenz** [comment]
The `fullscreen` option is not a hard limitation, you can still control the fullscreen with APIs. On Linux and Windows the `F11` is bound to call `setFullScreen` API in the default menu, if you don't want to respond to `F11`, you should set a custom menu for your app.

An example can be found at https://github.com/atom/electron/blob/master/docs/api/menu.md, what you need to do is to remove the `Toggle Full Screen` item.

**Comment by etiktin** [comment]
If you're running your app, by running `electron.exe path2App`, you are actually loading it through Electron's default_app, which has a menu, so that's why F11 works. If you instead package your app (either in the `resources\app` directory or in the `resources\app.asar` archive), the default menu won't exist so F11 won't toggle fullscreen.
