### ISSUE TITLE
BrowserWindow 'title-bar-style': 'hidden-inset' option doesn't work correctly in fullscreen

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#2810]
Origintal ticket: https://github.com/sindresorhus/caprine/issues/5

-

In fullscreen mode, instead of showing the user toolbar, it covers it up with a gray frame.

#### 1. Normal

<img width="809" alt="screen shot 2015-09-17 at 10 15 09" src="https://cloud.githubusercontent.com/assets/170270/9923990/44568378-5d25-11e5-856f-6acc83186d48.png">

#### 2. Fullscreen

<img width="1440" alt="screen shot 2015-09-17 at 10 15 37" src="https://cloud.githubusercontent.com/assets/170270/9923996/4c18668a-5d25-11e5-9bf0-c536f9622a59.png">

#### 3. Fullscreen with menubar visible

<img width="1440" alt="screen shot 2015-09-17 at 10 15 56" src="https://cloud.githubusercontent.com/assets/170270/9924004/6170e642-5d25-11e5-8fdc-d7ccdadcb82a.png">

Ideally it would show the top (covered up) web content in both 2. and 3., so my custom toolbar would be visible there.

-

OS X 10.10 and Electron 0.32.3.

-

@jaanus

**Comment by jaanus** [comment]
Yeah… this is because the hidden-inset style creates a window toolbar for styling, which is not visible in windowed mode, but is there in fullscreen mode. With a normal toolbar, there would be some buttons there (e.g look at Safari in fullscreen mode), but we just use this to inset the buttons so it contains nothing.

What do you think would be appropriate behavior? I’m thinking to just remove the toolbar for hidden-inset style in fullscreen mode, and restore the toolbar when going back from fullscreen to windowed mode. So in fullscreen case, hidden and hidden-inset styles would look the same,

**Comment by sindresorhus** [comment]
The perfect solution would be to show the top web contents in the toolbar, but I have a feeling that's too hard, so I guess your suggestion would work ok.

**Comment by jaanus** [comment]
I’d be happy to do this, but I just upgraded my toolchain to Xcode 7 now that it’s officially out, and looks like currently can’t build using this setup. So blocked by #2765 for now.

**Comment by zcbenz** [comment]
It seems that setting titlebar style is a one-way operation, once the window is set to hide the titlebar it becomes impossible to bring it back, I have pushed a commit in [hidden-inset-fullscreen branch](https://github.com/atom/electron/tree/hidden-inset-fullscreen) to show it.

To very it we can just create a NSWindow with titlebar hidden and then immediately call this:

```objc-c
NSUInteger styleMask = [window_ styleMask];
styleMask &= !NSFullSizeContentViewWindowMask;
styleMask &= !NSUnifiedTitleAndToolbarWindowMask;
[window_ setStyleMask:styleMask];
```

Instead of reverting to a normal window, the window just became a frameless window with titlebar completely removed.

**Comment by KevinMartin** [comment]
Would be great if there was an API that added custom items to the toolbar (like a search bar or buttons). And whatever is in the toolbar gets hidden and brought in using the current method.

**Comment by KevinMartin** [comment]
In the meantime, I've set `fullscreen: false` on the `BrowserWindow` constructor...

**Comment by ashokfernandez** [comment]
+1

**Comment by preco21** [comment]
+1

**Comment by ricodang** [comment]
+1

**Comment by Hum4n01d** [comment]
@sam3d Same here. Is there a way to keep the custom title bar like Safari does?

**Comment by atypicalprogrammer** [comment]
On that note, why is the title hidden when in full screen?

**Comment by nehbit** [comment]
@atypicalprogrammer you can enable the title by passing ```fullscreenWindowTitle:true``` to your browser window. 

For the expected behaviour, it would be lovely if we could get the thin full screen top bar that normal framed windows get. In the case that is impossible (which it probably is), having an inset version of the ```customButtonsOnHover``` would be great, because as far as I can see, if ```customButtonsOnHover``` is set, the full screen top bar is actually the right thin size.
