### ISSUE TITLE
Chromium crashes when cursor hovers over this link

### ISSUE THREAD

**Issue by kode54** [atom/electron#2845]
When a page containing this link is displayed, the page crashes when the cursor hovers over the link. The link is:

``` http : // example/%%30%30 ```

And a bug report of it against Chromium:

https://code.google.com/p/chromium/issues/detail?id=533361

**Comment by zcbenz** [comment]
Thanks for pasting it here, we usually don't open every Chromium issue on Electron's side unless we want to fix them ourselves, otherwise our issues tracker would be filled with Chromium's ones :smile_cat:.

For this bug, we will do an update of Chrome once Chrome releases a new version with the fix.
