### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by dvlsg** [atom/electron#2863]
I am attempting to build an app with electron, which contains the following js, included through a `<script src="file.js">` tag in the main `index.html`.

This results in `Uncaught ReferenceError: exports is not defined`:
```js
Object.defineProperty(exports, '__esModule', {
    value: true
});
exports.run = run;
function run() {}
```
If I swap both instances of `exports` to `module.exports`, then the code works as intended.

The pasted code above is from the output of babel when using the `export` syntax. Any ideas of how to get around this, short of writing my own module parser which uses `module.exports` in favor of `exports`? Is `exports` truly not supposed to be defined in electron, or am I doing something incorrect with electron?

I was originally working with browserify/babelify/etc, but ran into issues where the code from that context couldn't execute `dgram.createSocket()` correctly, so I would like to avoid that if at all possible. Currently using a workaround by using `module.exports` in my source files instead of `export ...`.

*edit*: Possible hold on this one. I can only reproduce the error sometimes. I'll see if I can come up with a minimal way of reproducing the error and post all the code here, or close the issue if I cannot.

*edit2*: Here's a [gist](https://gist.github.com/dvlsg/5428dc3d8dbdedf2f7f2) which reproduces the error for me. `script.js` is the important piece (I believe), as the other two pieces are copied from the electron quickstart. When I run `electron .` in a folder containing those 3 files, I get `script.js:2 Uncaught ReferenceError: exports is not defined`.

**Comment by zcbenz** [comment]
In Electron the modules have to be loaded with the `require` function of Node.js, modules imported by the `script` tag will run in browser's way, e.g. there is no `exports` object.

**Comment by samvloeberghs** [comment]
@zcbenz that simple comment being 1.5y old gave me a ton of insight, thanks

**Comment by lqs469** [comment]
use `target: 'electron-renderer'` instead of `target: 'electron'`.
> [target: 'electron-renderer'](https://webpack.js.org/configuration/target/)
Compile for Electron for renderer process, providing a target using JsonpTemplatePlugin, FunctionModulePlugin for browser environments and NodeTargetPlugin and ExternalsPlugin for CommonJS and Electron built-in modules.

**Comment by cawoodm** [comment]
The latest typescript version adds the following to every `.js` file:

```
Object.defineProperty(exports, "__esModule", { value: true });
```

Which is very unfortunate since electron crashes when it sees `exports`. Changing it to `module.exports` manually fixes the problem so I'm wondering (and, in parallel hassling the typescript crowd) why electron doesn't just define `exports = module.exports` and be done with it? As things stand, you can't use TypeScript compiles .js files in Electron which is a silly pity.

**Comment by newpanjing** [comment]
Modify the method to webpack：
```javascript
export const Command = function (name) {
    return '123'
}

export function Test(aa) {
    alert(aa)
}

export default {
    AA:'a'
}

```

see link:
[https://www.88cto.com/article/nsUUkb1e](https://www.88cto.com/article/nsUUkb1e)

**Comment by dnory0** [comment]
I do this:
```html
<script>var exports = {"__esModule": true};</script>
<script src="js/file.js"></script>
```

**Comment by pgherveou** [comment]
alternatively, you can also just add a noop exports to make it work 

```ts
function exports() {
  // noop
}
```

**Comment by albohlabs** [comment]
For reference:

> Require the script (second example) so it has access to the Node context

```
	<script>
		require('./index.js');
	</script>
```

source https://github.com/electron-userland/electron-compile/issues/267#issuecomment-477243045

**Comment by GitMurf** [comment]
> I do this:
> 
> ```
> <script>var exports = {"__esModule": true};</script>
> <script src="js/file.js"></script>
> ```

Is something like this still the suggested best way to use Electron with TypeScript? I simply am trying to import some custom Type definitions from my `index.d.ts` file to my renderer `index.ts` file but because of that TS adds the `Object.defineProperty(exports, "__esModule", { value: true });` to the top of my compiled JS file and then Electron spits the error of `exports is not defined` (similar to explained above in the other comments).

It just seems like this workaround is a bit "hacky" and I am surprised and wondering if this is still the best option or if the Electron team has released a "best practice" for this? Thanks!

p.s. I also assume this is all related to whether Electron will allow for ESM modules going forward. I posted about this here: https://github.com/electron/electron/issues/21457#issuecomment-1144986710
