### ISSUE TITLE
Using the File object is it possible to drag a file out of the app and into the filesystem?

### ISSUE THREAD

**Issue by alexbilbie** [atom/electron#2923]
Hello,

I want to expose a list of files on a network server inside an Electron app. A user will be able to then drag one or many files out of the Electron app into Finder/Explorer.

Is this possible with the [File object](https://github.com/atom/electron/blob/master/docs/api/file-object.md) APIs?

Thanks

**Comment by zcbenz** [comment]
This guide seems to work: http://www.thecssninja.com/javascript/gmail-dragout

**Comment by hems** [comment]
@zcbenz this guide works for images and to put images onto Finder, but this issue goes way deeper than that ( unfortunately ).

For instance when dragging an audio file into an audio application it by default won't let you "drop in" the file because it seems there is some issues on communication and the target application might not understand the kind of file that is being dragged over.

@alexbilbie which kind of file have you tried?

It seems image files does work fine, for instance dragging a JPG onto photoshop but during my tests dragging a WAV file or MP3 file into an audio application isn't working as expected. 

Anyone successfully managed to do it? Any help on this direction would be more than appreciated.

**Comment by whyboris** [comment]
@zcbenz -- could you reopen the issue? The link you provide is now a `404` and I've not found any information on this topic anywhere 😢 

Specifically, I want to drag video files from inside [my application](https://github.com/whyboris/Video-Hub-App) into _Premiere_ or _Vegas_ 🤔

**Comment by whyboris** [comment]
Relevant discussion: https://github.com/electron/electron/issues/11691 (so far no success as far as I can tell)

**Comment by hems** [comment]
would be great to get this working, but this issue is closed? :(

**Comment by whyboris** [comment]
The `gmail-dragout`link is `404` but the _demo_ is still alive here: https://ryanseddon.com/demo/gmail_dragout/

The specific implementation seems to be:
```html
<div class="container">
  <h1>Drag out any of these links to your dekstop</h1>

  <a href="Eadui.ttf" id="dragout" class="dragme" draggable="true"
    data-downloadurl="application/octet-stream:Eadui2.ttf:http://www.thecssninja.com/demo/gmail_dragout/Eadui.ttf">Font
    file</a>

  <a href="html5-cheat-sheet.pdf" id="dragout2" class="dragme" draggable="true"
    data-downloadurl="application/pdf:HTML5CheatSheet.pdf:http://www.thecssninja.com/demo/gmail_dragout/html5-cheat-sheet.pdf">PDF
    file</a>
</div>
```
JS
```js
  var files = [document.getElementById("dragout"), document.getElementById("dragout2"), document.getElementById("dragout3")],
    fileDetails = [];

  // Some forward thinking, utilise the custom data attribute to extend attributes available.
  if (typeof files[0].dataset === "undefined") {
    // Grab it the old way
    fileDetails[0] = files[0].getAttribute("data-downloadurl");
    fileDetails[1] = files[1].getAttribute("data-downloadurl");
  } else {
    fileDetails[0] = files[0].dataset.downloadurl;
    fileDetails[1] = files[1].dataset.downloadurl;
  }

  files[0].addEventListener("dragstart", function (evt) {
    evt.dataTransfer.setData("DownloadURL", fileDetails[0]);
  }, false);
  files[1].addEventListener("dragstart", function (evt) {
    evt.dataTransfer.setData("DownloadURL", fileDetails[1]);
  }, false);
```
🤷 unsure if this could work in Electron 🤷

**Comment by whyboris** [comment]
Turns out it works 🎉 thanks to https://github.com/electron/electron/pull/6333#issue-76082139
See documentation: https://www.electronjs.org/docs/tutorial/native-file-drag-drop#native-file-drag--drop

I tested just now - works in my app (dragging a video file out of my app into Vegas video editor or onto the desktop): https://github.com/whyboris/Video-Hub-App/issues/519#issuecomment-683319630
