### ISSUE TITLE
MenuItem `enabled` hook [OS X]

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#2934]
It's common convention on OS X to disable most of the MenuItem's when the active window is minimized to the dock. When using `role` this is handled for us. There should be a way to achieve this for custom MenuItem's. There are also other app actions and states that would need to change the `enabled` state of the MenuItem.

More on menu enabling: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MenuList/Articles/EnablingMenuItems.html

Maybe have the `enabled` option also accept a function which is triggered for every user event? That way the user is totally free to decide whether to enable the MenuItem or not.

```js
var item = new MenuItem({
  enabled: function () {
    return !mainWindow.isMinimized();
  }
});
```

-

Might be useful on Linux and Windows too, but I don't know how it works there.

**Comment by lipis** [comment]
Yes please! Is needed for all platforms.. not only if minimised but in general if you want to disable an item  for whatever reason.

**Comment by sindresorhus** [comment]
> not only if minimised but in general if you want to disable an item for whatever reason.

Yeah, minimized is only an example.

**Comment by paulcbetts** [comment]
Hm, I'm not super excited about this API proposal because then Electron will have to call enabled for every menu item on every "user event", since `enabled` doesn't fire any change notifications.

I think the high-level solution here is to make menus more accessible from the renderer (and more friendly to programmers in general), so that updating them yourself isn't so difficult. Something like:

```
var item = new MenuItem({
  name: 'open-file'    // This is globally unique across the entire menu, unlike id
});
```

Then make utility methods that make accessing these menus not a PITA:

```
// No more digging around in Menu arrays trying to walk a tree yourself
Menu.setEnabledFor('open-file', false);
```

**Comment by zcbenz** [comment]
You can achieve it by hacking the methods `menu.delegate`, but we don't have a public API for it yet, I'm merging this to #528.
