### ISSUE TITLE
Wrong (off by 1-pixel) window layout on multi-screen when BrowserWindow size == screen size. 

### ISSUE THREAD

**Issue by mgcrea** [atom/electron#2962]
## Environment

 Ubuntu 14.04.3LTS, discovered with electron v0.32.2, tested against v0.33.4.

## Issue

If I have a multi-screen setup, say 3*1360x768.
Without using `--fullscreen` or `--kiosk` (can't on nvidia without a BaseMosaic setup), but leveraging the `enable-larger-than-screen` option.

- If I start an electron window with fixed size of 4080x768, it will be incorrectly display only on the third screen (with a visible size of 1360x768).
- If I set the width to 4079x768, it will be properly displayed on all screens (correctly starting on the 1st one), but I get a missing 1-pixel-width-line at the end of the 3rd screen (where I can see the desktop background).

Looks like the logic determining that the wished window is larger that the total available screen space is off by 1 pixel. Any idea where this bug could come from?

**Comment by zcbenz** [comment]
It is probably because the DE turns the window into maximized state when the window size == screen size.

**Comment by akashnimare** [comment]
@zcbenz Can anyone tell me how can I contribute to electron? I would love to contribute and solve some linux related issues but I am not able to get started.

**Comment by zcbenz** [comment]
The [development](http://electron.atom.io/docs/v0.33.0/#development) section in docs should be able to get you bootstrapped, but it is also recommended to get some knowledge of [how Chromium works](http://dev.chromium.org/Home) since Electron heavily reuses Chromium's codebase.

**Comment by zcbenz** [comment]
After some investigation I'm afraid this is not something we can fix, this behavior is enforced by some desktop environments and there is no option for an app to disable that, some programs worked around it by forcing the window not to have the equal size with screen, but you will then have the 1px line offset. 

The only solution is to make users disable this feature in their desktop environments, and [there are many ways to achieve that on Google](https://www.google.com/search?client=safari&rls=en&q=linux+prevent+window+maximized&ie=UTF-8&oe=UTF-8). I'm closing this since there is no way to fix this.

**Comment by akashnimare** [comment]
@zcbenz Thanks man. Going through docs now.
