### ISSUE TITLE
OS Support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [atom/electron#2964]
I shouldn't have to go to this page:

* https://github.com/atom/electron/blob/9cdefb6069ade76854be8125e0d4c86265963a41/atom/browser/resources/win/atom.manifest

to see if XP or Vista is supported.

NW.js supports Vista and above, OSX 10.9+ and Ubuntu 12 & 14 LTS. It can (and should) be summed up in one sentence and put in the documentation.

**Comment by paulcbetts** [comment]
@TheJaredWilcurt Good point - can you submit a PR to the README? Here's the support:

* Windows - Win7 or higher
* OS X - ???? (can someone find this?)
* Linux - afaik 14.04 or higher? Maybe? 

/cc @zcbenz who might be able to answer some of these

**Comment by etiktin** [comment]
:+1: I agree.
This is related to a discussion we had a while back [here](https://github.com/atom/electron/issues/2452#issuecomment-131931426).

I think it should be in a separate "Supported Platforms" doc. That way people could add to it more specific notes for each platform. For example, instead of just saying that Ubuntu 14.04+ is supported/tested, it could list all the other distributions that users confirmed work with the binary releases, and information about distributions that will work only if you compile it yourself.

Regarding the versions Paul mentioned:
- Ubuntu 14.04 is the current LTS. Is that really the minimal version that we support? I would expect it be 12.04 or maybe even 10.04.
- The only mention I see in the issues about OS X versions is that we only support 64 bit versions. So that would suggest 10.7 Lion, which was the first version only available on 64 bit Intel CPUs.
- What about Windows Server 2008 R2+?

**Comment by johnmuhl** [comment]
https://github.com/atom/electron/blob/master/atom/browser/resources/mac/Info.plist#L21-L22 says 10.8.0 for OS X.

**Comment by paulcbetts** [comment]
> Ubuntu 14.04 is the current LTS. Is that really the minimal version that we support? I would expect it be 12.04 or maybe even 10.04.

Linux gives zero fucks about ABI/API compatibility so supporting versions that old is basically impossible

> What about Windows Server 2008 R2+?

2008 R2 is Win7

**Comment by zcbenz** [comment]
Closed with #2972.
