### ISSUE TITLE
Bootstrap: libchromiumcontent-static download: Operation timed out

### ISSUE THREAD

**Issue by dkfiresky** [atom/electron#2989]
Download of libchromiumcontent-static failed with error:

```sh
socket.error: [Errno 60] Operation timed out
```

__Download url:__ http://github-janky-artifacts.s3.amazonaws.com/libchromiumcontent/osx/x64/04523758cda2a96d2454f9056fb1fb9a1c1f95f1/libchromiumcontent-static.zip
__Electron version:__ 0.33.3

**Comment by zcbenz** [comment]
`libchromiumcontent-static` is a huge file and S3 is slow on many regions, you need to find a fast VPN or proxy server to be able to download it.

**Comment by jorangreef** [comment]
I am getting the same error.

I setup a SOCKS proxy to a nearby dedicated server with a fast connection but that still did not help, I still get the same error.

The dedicated server is able to download the file from S3, and my machine is able to download the file from there.

I think the problem lies in the download script itself, specifically around timeout handling. The timeout for the socket or read calls could be defined or set to None?
