### ISSUE TITLE
Crash Reporter should also work via mail

### ISSUE THREAD

**Issue by mnewmedia** [atom/electron#3011]
It would be very nice, when the crash reporter also could send mails instead of just sending `POST-requests`. Cause if the application crashes somewhere i need to get informed.

**Comment by hokein** [comment]
I think you can achieve it in your crash-reporter server.

**Comment by mnewmedia** [comment]
Of course, but then all people who wants to have crashes reported via mails, need to setup a server and a script.. Instead just configuring the mail options..

Was just an enhancment idea..

---- Haojian Wu schrieb ----

**Comment by thomasjo** [comment]
I agree with @hokein, this should be handled on the server side. In order to send an e-mail from a client, you'd need to specify a POP (or IMAP) server. And in order for a user's machine to be able to send via that e-mail server, it would need to be open to the world and basically without authentication (you'd need to configure this as well, so it would be readable by everyone).

In summary this is more complicated than simply configuring an a recipient e-mail address. Since this is non-trivial, and something I doubt the average Electron developer is looking for, I'm going to close this issue.
