### ISSUE TITLE
console.log outputs in main process are not printed on Windows

### ISSUE THREAD

**Issue by zcbenz** [atom/electron#3032]
Quoted from https://github.com/atom/electron/pull/2974#issuecomment-146342860:

> Keep in mind that on Windows, calls to console.* won't be printed, but they will be printed on Linux and OS X. The reason is that for Windows, console.* is implemented on top of the logging mechanism (see details here).

**Comment by etiktin** [comment]
Some thoughts:
- I think the default behavior when running without `--enable-logging` should be to not output any logs including errors, but still output `console.*` calls. The reason is that the error logs are not really informative. For example on Linux a lot of users (maybe all) get the SUID sandbox message (see screenshot at #1482). It seems pointless to show this info to app users, and developers can run with `--enable-logging` to see it.
For Windows we'll need to find a way to dynamiclly set the destination. So `console.*` will print and other direct calls to `LOG` won't print (logging_dest set to none).
- On Windows, `console.*` calls from renderers are printed to devtools and to cmd. I think it makes more sense that the render calls will print to the devtools console only, and main calls will print to cmd.
- On Windows, `console.*` calls that are printed to cmd, start with an ugly prefix (e.g. `[11188:1009/211327:INFO:CONSOLE(0)] Some text`). The prefix is due to the usage of Chromium's logging mechanism. It seems it's printed by `LogMessage::Init`. Can we override that during calls to `console.*`? If not, can we just copy the relevent parts and print the calls without a prefix. It really looks weird that when you run `electron --help` or `electron --version` the output includes that prefix.

What do you think?

**Comment by zcbenz** [comment]
I'm :+1: on all of them, the purpose of introducing `--enable-logging` was exactly to disable Chromium's logging by default and only print `console.log` outputs in the main process.

On Windows the way Node implemented `process.stdout` and `console.log` doesn't work well in Electron, so we redirected them to use Chromium's logging system, that's why we have this issue and #2390, we need to fix that to solve all the problems.

> I think the default behavior when running without --enable-logging should be to not output any logs including errors

Chromium hard-coded the logging system to always output `ERROR` logs, we have to patch Chromium to fix this.

**Comment by etiktin** [comment]
@zcbenz, I actually already started working on it (except for the `ERROR` logs). It's available at #3056.

**Comment by etiktin** [comment]
@zcbenz, what about blocking `ERROR` logs when running without `--enable-logging`, do you want it to be a separate issue or can we reopen this?

**Comment by zcbenz** [comment]
I think we can open a new issue for that, tracking too many issues in one place makes things complicated.
