### ISSUE TITLE
Taskbar icon missing on first launch of Squirrel.Windows Electron app

### ISSUE THREAD

**Issue by juturu** [atom/electron#3037]
After the install/update of Electron app (setup build using Squirrel.Windows), initial launch shows blank icon on the taskbar. Closing and relaunching the app shows the icon properly.

Electron version: 0.32.0
Squirrel version: 1.0.2

On restart of the process, icon on the Taskbar (not Tray icon) is shown properly.

I already have the following lines of code at the start of main process
var aumid = 'com.squirrel.xxxx.xxxx';
app.setAppUserModelId(aumid);

**Comment by paulcbetts** [comment]
So, my psychic debugger is saying that this won't happen on a clean machine, because this actually *isn't* the initial launch, you're running it from two places:

1. From your build location (i.e. a temp dir)
1. From the installed directory

The good news is, this is fixed in the very latest versions of both Squirrel and Electron - have the latest of both and you should be :gem:

**Comment by py09mb** [comment]
@paulcbetts I'm seeing somethign similar on first install. Packaged using electron 0.36.2 and built with grunt-electron-installer 1.2.0. Screenshots attached are from the build box but same happens on fresh machines.
 
Notice the icon in explorer
![squirrel](https://cloud.githubusercontent.com/assets/2480869/12232304/ab6d3f80-b855-11e5-8a89-1cb84e3d73b1.png)

![taskbar](https://cloud.githubusercontent.com/assets/2480869/12232305/ac77af8c-b855-11e5-92a5-0a374c03cabc.png)

Everthing is perfect when the application launches after installation.

**Comment by SumitSharma1005** [comment]
On first launch with every update, App first launch with older version and create latest version executable hive under "%AppData%". On second launch we will get updated version of app.
Can you please guide me what and where I am going wrong?
