### ISSUE TITLE
Reusing native window + packaging as DLL

### ISSUE THREAD

**Issue by distopik** [atom/electron#3044]
Some audio applications support VST, a binary-level protocol that defines "plugins" as dynamically linkable libraries (DLLs, .so's, .dylib's, ..). These plugins extend the capabilities of the audio application and are a very popular software distribution format. By using Electron, the open source plugin community could benefit greatly for the same reasons that general desktop application developers do.

To make this happen, Electron would need to:
1. be packaged as a .DLL and export a few special symbols - I think this could be handled easily at the C++ level of the code
2. allow for the host application to control the lifecycle of the plugin - the host application calls `create` and `destroy` of the audio processing context (and with it, presumably, the Electron runtime)
3. re-use a native window handler when creating a browserwindow - the host application creates a native window for the plugin and destroys it (notifying the plugin beforehand)

Are these things possible and could you post a few pointers on where one could start to support this?

**Comment by zcbenz** [comment]
Electron is not designed to be embedded by other applications, and providing such interface is no easy work. If you want to embed a browser the best choice is to use [CEF](https://bitbucket.org/chromiumembedded/cef).

If you have interests in making Electron embeddable you can start with [how Chromium works](http://dev.chromium.org/Home), since the Electron is basically a custom build of Chrome browser.
