### ISSUE TITLE
Catch full Promise error object from remote

### ISSUE THREAD

**Issue by maxcnunes** [atom/electron#3089]
Is possible to catch in the renderer process a full Promise error object thrown from a remote process?

### Example
**remote-stuff.js**
```js
exports.asyncProcess = function(success) {
  return new Promise(function (resolve, reject) {
    reject(new Error('My error'));
  });
}
```

**index.html**
```html
...
<body>
    <script>
      require('remote')
        .require('./remote-stuff')
        .asyncProcess()
        .then(null, function (err) {
          console.error(err);
        });
    </script>
  </body>
...
```
But it throws only a blank error object. With no message or stack values.
Is that really normal? Would be possible to receive the whole error object?
![electron-blank-error](https://cloud.githubusercontent.com/assets/680356/10502894/1546209a-72c7-11e5-82df-1433651fb2fd.png)

* electron-prebuilt: 0.33.8
* OS X Yosemite - version 10.10.3

**Comment by maxcnunes** [comment]
Could the problem be here [remote.coffee](https://github.com/atom/electron/blob/master/atom/renderer/api/lib/remote.coffee)? I was hopping trying to fix this bug if it is something in js/coffe but I got some problems building the project in my machine #3102.

While this is not fixed, is there a recommended approach to handle errors coming from a remote code?

**Comment by zcbenz** [comment]
Yeah the problem is in `remote` module, it seems that `Error` object is not passed with all its members. 

> While this is not fixed, is there a recommended approach to handle errors coming from a remote code?

The best approach is probably not to handle errors for remote object, using `remote` module is quite expensive, and since remote objects are not the original ones, you might encounter surprises if you use it heavily.

**Comment by maxcnunes** [comment]
Seems that the problem is during the serialization of Error to string. Properties of Error instances are non-enumerable. Which means they cannot be serialized through JSON.stringify.

May be the solution could be parse the Error object to a plain object before sending it through the remote function. Something like this:

```js
/**
 * Clone error into a plain object
 */
function toPlainError (err) {
  return Object.getOwnPropertyNames(err)
    .reduce(function (obj, key) {
      obj[key] = err[key];
      return obj;
    }, {});
}
```

**Comment by maxcnunes** [comment]
Awesome!! thanks

**Comment by lukasbestle** [comment]
Also seems to happen with `Date`.

---

BTW: I'm currently using the `remote` module because I need: 

1. a single source of truth regarding open file objects and their options.
2. to pass these file objects between windows (after a file has been opened in one window, it needs to be passed to another window that does stuff with it while the first window is closed).

Using the `remote` module solves both of these issues (all the code runs in the main process and the renderer can always grab the object from there), but it isn't perfect (see this issue) and as you wrote above, it's not performant.

What is your recommended solution for such a problem?
