### ISSUE TITLE
Chrome Push Support? 

### ISSUE THREAD

**Issue by adilanchian** [atom/electron#3095]
Hey everyone,

I have recently been trying to implement some push notifications in my app through chrome's cloud messaging service. They have some awesome write-ups online about how to implement this in the chrome browser. I assumed this should work very similar in Electron. So I tested my code in Electron (0.32.2) and unfortunately I keep getting a DOM error stating :

Unable to subscribe to push. DOMException: Registration failed - push service not available

Seems like it makes sense but, when I visit chrome://serviceworker-internals within Electron, it states my service worker is ACTIVATED and RUNNING.

Also, I have checks within my code to verify that push services and the service worker are ready to go.
After I first received this error I tried running my code within a regular chrome browser and it worked flawlessly. So, that fortifies the fact that Electron doesn't like something about Google Cloud Messaging.

If anyone could offer any sort of reasoning on to why Electron is having an issue with this implementation of push notifications, I would greatly appreciate it. Thanks in advance for the help!

-Alec

**Comment by zcbenz** [comment]
Current we don't have Google Cloud Message supported, and we probably won't in future since the work to support this is relatively heavy. Google's private services are not included in Chromium's content module, so we don't get them in Electron by default.

I'm closing this since we are not likely to fix this, however pull requests will be welcomed.

**Comment by adilanchian** [comment]
zcbenz,

Thanks for the quick reply.

-Alec

**Comment by eladnava** [comment]
For anyone still interested, and since this likely won't be supported natively in Electron, [Pushy](https://pushy.me/) has just added support for sending push notifications to Electron apps using a background MQTT connection:
[pushy-me/pushy-electron](https://github.com/pushy-me/pushy-electron)

Refer to the docs for integration steps:
https://pushy.me/docs/additional-platforms/electron

Full disclosure: Pushy is a paid product that I helped found.
