### ISSUE TITLE
[windows] 0.33.8 not allowed to write to fs, 0.33.7 works as expected

### ISSUE THREAD

**Issue by leshow** [atom/electron#3100]
using the exact same codebase, running on 0.33.7 my app runs correctly. running on 0.33.8 I get an error when writing to the filesystem.

My app checks for the existence of a file and creates it if it doesnt exists on startup, using the `require('fs')` module.

I'm writing to the `app.getPath('userData')` directory, which I should have permissions to write to. 

Curiously, when testing my app from the cmd prompt with `electron .` it has no issues (even on 0.33.8) but packaged I get a popup with a javascript error saying I am not allowed to write to the fs.

**Comment by etiktin** [comment]
What is the name and version of the OS you're using?

**Comment by zcbenz** [comment]
Can you paste the full message of the popup?

**Comment by zcbenz** [comment]
Hmm I think I have just encountered the same error, steps to reproduce:

1> Package following app into Electron

```js
console.log('test');
```

2> Execute the app by double clicking in File Explorer

3> Following error happens

<img width="506" alt="screen shot 2015-10-16 at 10 13 44 am" src="https://cloud.githubusercontent.com/assets/639601/10532249/a2d5eb48-73ee-11e5-8e01-aa6f586c66a6.png">

The same error also happens if I debug the app through Windbg.

It seems that we still have the problem with `process.stdout` on Windows when the app is run without a terminal, we probably need to revert 4e8db2c3be8f3c9a172fb87ad8739493ab3dfbb1.

**Comment by leshow** [comment]
That's it @zcbenz thanks! I assumed it was the filesystem write I was doing on startup, thanks for getting  this addressed so quickly
