### ISSUE TITLE
Few crash reports with Electron 0.26.1 on OSX 10.11 (El Capitan)

### ISSUE THREAD

**Issue by pracucci** [atom/electron#3107]
**DISCLAIMER: this is probably not an Electron issue**, but with a bug in our own add-on. I'm asking some suggestions about how to debug it in a Electron app.

We have an app in production that runs on Electron 0.26.1. We're receiving few crash reports on OSX 10.11 (El Capitan) and I'm wondering if they're known issue, maybe already fixed in recent Electron / Chromium releases. I've already searched through the issues, but I can't find any evidence.

I've attached a couple of them. May you take a quick look and give an hint? Any suggestion is welcome.

- Crash 12 https://gist.github.com/pracucci/cdf23cb1956a5c2279a1 - looks related to our add-on but a confirmation on your side is appreciated
- Crash 13 https://gist.github.com/pracucci/580e0046b2ad24712825 - looks inside drawing, but I've no clue how to investigate it
- Crash 14 https://gist.github.com/pracucci/e84d19c989ae802873e8 - looks inside drawing, any idea?

_Why we use Electron 0.26.1: I know it's a (relatively) old Electron version and we have already planned to update it, but will take more time than expected due to some issue we've with a core native add-on we're using._

Thank you for your great work (and hopefully some help),
Marco

**Comment by thomasjo** [comment]
I could be wrong here, but I think the crash "locations" might be completely random — based on the three crash dumps it looks like the problem is memory corruption of some kind. Possibly dangling pointers.

Initial gut feeling tells me this is not a problem with Electron since we've had none of these reports/issues in Atom (which up until recently was running on Electron 0.22.3). Although 0.25.0 did upgrade Chromium to v42, so not impossible the problem lies in there somewhere.

You mentioned a native library/add-on. Is it possible it's doing something that could be causing issues with changed APIs in El Capitan?

Most likely @zcbenz can shed more/better light on this than me. I'm not really familiar with the guts of Electron or Chromium.

**Comment by pracucci** [comment]
@thomasjo thanks for your prompt reply

> I could be wrong here, but I think the crash "locations" might be completely random — based on the three crash dumps it looks like the problem is memory corruption of some kind.

That's right. Locations could be totally random and the issue could be somewhere in our native add-on. I don't think the cause is related to some APIs changed in El Capitan, but El Capitan could be more susceptible to such bug.

Any suggestion / hint how to debug it?

**Comment by thomasjo** [comment]
Have you been able to reproduce the bug? It might be really hard to track down unless you can reproduce it. If it's possible to run your native code in some form of standalone mode, you might have some success using something like Valgrind's memcheck tool (or equivalent). Not sure how well it's going to behave in the context of a full-blown Electron app, but that might work as well (but will be really, really slow).

Ultimately I think you might have to run at least some of the diagnostics on an El Capitan machine in case the bug is only present on such systems.

**Comment by pracucci** [comment]
@thomasjo the native add-on has a good unit tests coverage. I've already run valgrind on tests, but it doesn't show any severe issue (just few leaks). I didn't run valgrind on El Capitan: I'm going to prepare a box with El Capitan today. Thanks for such suggestion, that actually makes much sense.

**Comment by pracucci** [comment]
After further investigations we definitely have an issue in the node add-on, caused by `uv_queue_work()` not thread-safe. Not sure it's the issue experienced with the above (random) stack dumps, but we're going to fix it and re-iterate. For this reason, I'm closing the issue.

Thanks @thomasjo for the help.
