### ISSUE TITLE
OS X native scrolling effect

### ISSUE THREAD

**Issue by evgenyzinoviev** [atom/electron#3170]
Hi. Is it possible to implement (or perfectly emulate) Mac OS X native overscrolling (when scroll bounces at the top or bottom edge) for `<div>`s? In Chrome (so in Electron) it works only for `<body>` (note that in Safari it also working with `<div>`s).

My application window is split in two parts (a list at the left and a content at the right), and I want them to behave (and to scroll) natively...

**Comment by joshaber** [comment]
This is something near and dear to my heart. WebKit does this so I'm hoping Chromium will pick it up too. Short of that, it'd require a monster patch in libchromiumcontent.

**Comment by bhazzard** [comment]
This is probably not an ideal solution, but would iframes solve this for you?

**Comment by evgenyzinoviev** [comment]
@bhazzard just checked, not works with iframes... only with main body.

**Comment by joshaber** [comment]
It'd probably be good to file an issue on Chromium, if there isn't already one.

**Comment by zcbenz** [comment]
Yeah Chromium should be the right place to file this.

**Comment by markesaaremets** [comment]
Issue on Chromium — https://code.google.com/p/chromium/issues/detail?id=546520

**Comment by atomiks** [comment]
Here is a CodePen demonstrating a JS/CSS way of achieving the effect:
https://codepen.io/anon/pen/ZadKOx?editors=1010

However, it's not 100% perfect as the translating seems to slightly glitch randomly sometimes. Also, moving the mouse stops the `wheel` event from firing, which is why there is a `transition` to put it back to the default position when the mouse moves.

Can anyone come up with a great way to achieve the rubber banding effect on a scrollable until Chromium finally implements it?
