### ISSUE TITLE
Developers console doesn't work when setting menu.

### ISSUE THREAD

**Issue by Sekhmet** [atom/electron#3201]
I've created an electron app using generator-electron. I'm using electron v0.34.1 on Ubuntu 15.04.
Developers console works great, but only until I want to create custom menu and call `Menu.setApplicationMenu(menu);` then I can't open dev console at all.

Sample code
```js
var menutpl = [];
var menu = Menu.buildFromTemplate(menutpl);
Menu.setApplicationMenu(menu);
```

No errors, not failing build. It just won't come out when I use Ctrl+Shift+I.

**Comment by etiktin** [comment]
The shortcut to open devtools was only available because your app was hosted in the default_app (that's the state your app runs in unless you package it) which creates a menu item for opening the devtools. So by adding your own menu you actually replaced the old one and lost the shortcut.
To get the shortcut back you can add it to the menu like so: https://github.com/atom/electron/blob/1896deb10eda67d8e8cb5188fe0f747fa16fdfeb/atom/browser/default_app/main.js#L109
Or if you don't want it in a menu item you can register a global shortcut (details [here](https://github.com/atom/electron/blob/1896deb10eda67d8e8cb5188fe0f747fa16fdfeb/docs/api/global-shortcut.md)).
The default_app exposes some shortcuts to help make it easier to develop/debug your app (e.g. reload, open devtools). Once you package it, it won't be available any more.

**Comment by Sekhmet** [comment]
Oh, I messed up. I saw this code and thought it opens dev tools thanks to accelerator and I forgot about click event. Thanks a lot!
