### ISSUE TITLE
Error: EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by sergiuwd** [atom/electron#3266]
Hi!
I get this error in my app:
<b>Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\Full Menu\db\main.json'</b>

The app I have is built with electron-boilerplate. I am using this function to get the path to the root of the app:
<pre>path.dirname(process.execPath)</pre>

And this is the script that writes the file:
<pre>fs.writeFile(apath + '/db/' + elem + '.json', JSON.stringify(results)</pre>

I know what the problem is: permissions. But how could I get this working without running the app as an administrator?

**Comment by paulcbetts** [comment]
Stop writing to Program Files, of course!

**Comment by sergiuwd** [comment]
Well, I am building the app on Windows using electron-boilerplate, and the NSIS installer will not allow me to choose a location for the installation.

**Comment by paulcbetts** [comment]
These don't seem to be related, why would you _have_ to write to Program Files or relative to process.execPath?

**Comment by sergiuwd** [comment]
Because the installer was automatically setting the destination path to Program Files. I kind of solved the problem by using this script:
https://gist.github.com/kevinhikaruevans/a46be6ad593e9fa3f7d2
The problem with this is that the shortcut it creates won't start the app and I have to run the installer as an administrator.

**Comment by paulcbetts** [comment]
Just copy the file somewhere else

**Comment by paulcbetts** [comment]
Oops, hit close and comment by mistake - does this work for you @sergiuwd?

**Comment by sergiuwd** [comment]
No problem. I am trying to modify the default NSIS script to allow me to choose the installation location for the app. 
<pre>InstallDir "$PROGRAMFILES\${productName}"</pre>
I have found the piece of code that chooses the location. I think I can do <i>C:\${productName}</i> by default, but there must be a more clever way to do it.

**Comment by sergiuwd** [comment]
Yep.
<pre>InstallDir "C:\${productName}"</pre>
This does it just fine. I think I'll leave it like that for the moment, because I'm only building for Windows.

**Comment by zcbenz** [comment]
I'm closing this since it is more an issue of the installer.

**Comment by idleberg** [comment]
@sergiuwd You can also use standard [NSIS parameters](http://nsis.sourceforge.net/Docs/Chapter3.html#installerusagecommon) to override the install location, e.g. `installer.exe /D=C:\my Favourite Directory`

**Comment by sergiuwd** [comment]
I didn't know that. Thanks!

**Comment by idleberg** [comment]
@sergiuwd Please use with care, [read this](https://github.com/szwacz/electron-boilerplate/issues/54https://github.com/szwacz/electron-boilerplate/issues/54)!

**Comment by sergiuwd** [comment]
Oh, yeah. That's right, the uninstaller might not read it well. I think this solution is better: 
<pre>InstallDir "C:\${productName}"</pre>

**Comment by prexj** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\pratikj\Desktop\application>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: We're super ?  excited that you'
re trying to use ES2015 syntax, but instead of making more yearly presets ? , Ba
bel now has a better preset that we recommend you use instead: npm install babel
-preset-env --save-dev. preset-env without options will compile ES2015+ down to
ES5 just like using all the presets together and thus is more future proof. It a
lso allows you to target specific browsers so that Babel can do less work and yo
u can ship native ES2015+ to user ? ! We are also in the process of releasing v7
, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and h
elp test it out in beta! Thanks so much for using Babel ?, please give us a foll
ow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/d
evelopment and help support the project at opencollective.com/babel
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated

> phantomjs-prebuilt@2.1.15 install C:\Users\pratikj\Desktop\application\node_mo
dules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantom
js-2.1.1-windows.zip
Saving to C:\Users\pratikj\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.
zip
Receiving...
  [========================================] 100%
Received 17767K total.
Extracting zip contents
Removing C:\Users\pratikj\Desktop\application\node_modules\phantomjs-prebuilt\li
b\phantom
Copying extracted folder C:\Users\pratikj\AppData\Local\Temp\phantomjs\phantomjs
-2.1.1-windows.zip-extract-1506080375835\phantomjs-2.1.1-windows -> C:\Users\pra
tikj\Desktop\application\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\pratikj\Desktop\application\node_mo
dules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
npm ERR! path C:\Users\pratikj\Desktop\application\node_modules\fsevents\node_mo
dules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Deskto
p\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Des
ktop\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\p
ratikj\\Desktop\\application\\node_modules\\fsevents\\node_modules\\dashdash\\no
de_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\pratikj\\Desktop\\application\\node_modules\\fseven
ts\\node_modules\\dashdash\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pratikj\AppData\Roaming\npm-cache\_logs\2017-09-22T11_39_4
4_353Z-debug.log

C:\Users\pratikj\Desktop\application>npm install --force
npm WARN using --force I sure hope you know what you are doing.

> fsevents@1.1.2 install C:\Users\pratikj\Desktop\application\node_modules\fseve
nts
> node install

npm notice created a lockfile as package-lock.json. You should commit this file.

added 115 packages and removed 411 packages in 71.385s

C:\Users\pratikj\Desktop\application>npm install fsevents
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","
arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pratikj\AppData\Roaming\npm-cache\_logs\2017-09-22T11_57_0
7_666Z-debug.log

C:\Users\pratikj\Desktop\application>npm install @angular/cli

> node-sass@4.5.3 install C:\Users\pratikj\Desktop\application\node_modules\node
-sass
> node scripts/install.js

Cached binary found at C:\Users\pratikj\AppData\Roaming\npm-cache\node-sass\4.5.
3\win32-ia32-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\pratikj\Desktop\application
\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.5.3 postinstall C:\Users\pratikj\Desktop\application\node_modules\
node-sass
> node scripts/build.js

Binary found at C:\Users\pratikj\Desktop\application\node_modules\node-sass\vend
or\win32-ia32-57\binding.node
Testing binary
Binary is fine
npm ERR! path C:\Users\pratikj\Desktop\application\node_modules\fsevents\node_mo
dules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Deskto
p\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Des
ktop\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\p
ratikj\\Desktop\\application\\node_modules\\fsevents\\node_modules\\dashdash\\no
de_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\pratikj\\Desktop\\application\\node_modules\\fseven
ts\\node_modules\\dashdash\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pratikj\AppData\Roaming\npm-cache\_logs\2017-09-22T12_16_5
1_459Z-debug.log

C:\Users\pratikj\Desktop\application>

now how to solve this

**Comment by prexj** [comment]
If any buddy know this error of code please give me answer. It's show below. I want to resolve this. 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Users\pratikj\Desktop\application>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: We're super ? excited that you'
re trying to use ES2015 syntax, but instead of making more yearly presets ? , Ba
bel now has a better preset that we recommend you use instead: npm install babel
-preset-env --save-dev. preset-env without options will compile ES2015+ down to
ES5 just like using all the presets together and thus is more future proof. It a
lso allows you to target specific browsers so that Babel can do less work and yo
u can ship native ES2015+ to user ? ! We are also in the process of releasing v7
, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and h
elp test it out in beta! Thanks so much for using Babel ?, please give us a foll
ow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/d
evelopment and help support the project at opencollective.com/babel
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated

phantomjs-prebuilt@2.1.15 install C:\Users\pratikj\Desktop\application\node_mo
dules\phantomjs-prebuilt
node install.js
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantom
js-2.1.1-windows.zip
Saving to C:\Users\pratikj\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.
zip
Receiving...
[========================================] 100%
Received 17767K total.
Extracting zip contents
Removing C:\Users\pratikj\Desktop\application\node_modules\phantomjs-prebuilt\li
b\phantom
Copying extracted folder C:\Users\pratikj\AppData\Local\Temp\phantomjs\phantomjs
-2.1.1-windows.zip-extract-1506080375835\phantomjs-2.1.1-windows -> C:\Users\pra
tikj\Desktop\application\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\pratikj\Desktop\application\node_mo
dules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
npm ERR! path C:\Users\pratikj\Desktop\application\node_modules\fsevents\node_mo
dules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Deskto
p\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR! { Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Des
ktop\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR! stack: 'Error: EPERM: operation not permitted, scandir 'C:\Users\p
ratikj\Desktop\application\node_modules\fsevents\node_modules\dashdash\no
de_modules'',
npm ERR! errno: -4048,
npm ERR! code: 'EPERM',
npm ERR! syscall: 'scandir',
npm ERR! path: 'C:\Users\pratikj\Desktop\application\node_modules\fseven
ts\node_modules\dashdash\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\pratikj\AppData\Roaming\npm-cache_logs\2017-09-22T11_39_4
4_353Z-debug.log

C:\Users\pratikj\Desktop\application>npm install --force
npm WARN using --force I sure hope you know what you are doing.

fsevents@1.1.2 install C:\Users\pratikj\Desktop\application\node_modules\fseve
nts
node install
npm notice created a lockfile as package-lock.json. You should commit this file.

added 115 packages and removed 411 packages in 71.385s

C:\Users\pratikj\Desktop\application>npm install fsevents
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","
arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS: darwin
npm ERR! notsup Valid Arch: any
npm ERR! notsup Actual OS: win32
npm ERR! notsup Actual Arch: ia32

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\pratikj\AppData\Roaming\npm-cache_logs\2017-09-22T11_57_0
7_666Z-debug.log

C:\Users\pratikj\Desktop\application>npm install

node-sass@4.5.3 install C:\Users\pratikj\Desktop\application\node_modules\node
-sass
node scripts/install.js
Cached binary found at C:\Users\pratikj\AppData\Roaming\npm-cache\node-sass\4.5.
3\win32-ia32-57_binding.node

uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\pratikj\Desktop\application
\node_modules\uglifyjs-webpack-plugin
node lib/post_install.js
node-sass@4.5.3 postinstall C:\Users\pratikj\Desktop\application\node_modules
node-sass
node scripts/build.js
Binary found at C:\Users\pratikj\Desktop\application\node_modules\node-sass\vend
or\win32-ia32-57\binding.node
Testing binary
Binary is fine
npm ERR! path C:\Users\pratikj\Desktop\application\node_modules\fsevents\node_mo
dules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Deskto
p\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR! { Error: EPERM: operation not permitted, scandir 'C:\Users\pratikj\Des
ktop\application\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR! stack: 'Error: EPERM: operation not permitted, scandir 'C:\Users\p
ratikj\Desktop\application\node_modules\fsevents\node_modules\dashdash\no
de_modules'',
npm ERR! errno: -4048,
npm ERR! code: 'EPERM',
npm ERR! syscall: 'scandir',
npm ERR! path: 'C:\Users\pratikj\Desktop\application\node_modules\fseven
ts\node_modules\dashdash\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\pratikj\AppData\Roaming\npm-cache_logs\2017-09-22T12_16_5
1_459Z-debug.log

C:\Users\pratikj\Desktop\application>
