### ISSUE TITLE
Geolocation should require permission request when called from webview

### ISSUE THREAD

**Issue by PalmerAL** [atom/electron#3268]
Currently, the html5 geolocation api doesn't require a permission request from the user. This makes sense when it is called from a ```browserWindow```, since the window already has node access.

The ```<webview>``` tag is meant for untrusted web content, and is supposed to be sandboxed. However, js in the ```<webview>``` tag also has access to geolocation without a permissions request - you can test this with the code below:

```
<webview src="http://html5demos.com/geo"></webview>"

```

This is a privacy issue, since any website you visit in a webview can access your precise location.  If something like a web browser is created using electron, any website visited using it could access your location.

There should be an API in Electron, that sends geolocation requests to the webview parent and allows the parent view to accept or deny geolocation requests. Something similar to the recently introduced basic authentication support (#1362) would work well:

```
app.on("geolocation-request", function(event, webviewUrl, callback) {
    //call callback() to accept the geolocation request
    //or do nothing to deny the request
});
```

**Comment by paulcbetts** [comment]
> This is a privacy issue, since any website you visit in a webview can access your precise location. If something like a web browser is created using electron, any website visited using it could access your location.

Electron isn't designed to be a web browser, Electron is a platform for writing Desktop applications, and Desktop applications can access location data

**Comment by PalmerAL** [comment]
> Desktop applications can access location data

I agree. The issue isn't that an app can access location data, the issue is that content inside a webview, which according to the docs is for untrusted content, can access location data even though the docs say that content inside it "doesn't have the same permissions as your web page".

**Comment by zcbenz** [comment]
Having this would be cool, but I don't think any of us would be interested in this since only few people care running untrusted content securely, and you can always use `preload` script to add a custom wrapper around the geolocation API, so I'm closing this issue.

However pull request to implement this is still welcomed.

**Comment by Nashorn** [comment]
does not work in Electron 6 beta

code: 3
message: Timeout expired

onPositionError @ VM130:256

**Comment by kevinvanrijn** [comment]
Since I hit this through Google and likely others will as well you can implement this functionality easily enough by writing something like:

```
const { app, BrowserWindow } = require('electron')

app.whenReady().then(() => {
	const win = new BrowserWindow({
		...
	})

	// Disallow access to microphone, camera, location, clipboard, screen recording and so on
	// Still allows images and JavaScript since they're not part of this system
	win.webContents.session.setPermissionRequestHandler((webContents, permission, callback) => {
		console.log('Denied access to "' + permission + '" permission requested by site')
		return callback(false)
	})

	win.loadURL(...)
})
```

Preload scripts were already mentioned, use those when it makes sense.

Just make sure to set up your handler before you load your urls. Your best bet is denying everything by default and making specific exceptions for the permissions that get logged. `permission === 'geolocation'` is the exact permission requested by the op.

You can read more in the [documentation for setPermissionRequestHandler](https://www.electronjs.org/docs/latest/api/session#sessetpermissionrequesthandlerhandler) and get another code sample which solves this another way.
