### ISSUE TITLE
Linux renderer processes do not inherit environment variables set by main process

### ISSUE THREAD

**Issue by joaomoreno** [atom/electron#3306]
One used to be able to do this from the main process:

```javascript
process.env['HELLO'] = 'WORLD';
```

And the `HELLO` environment variable would exist in every renderer spawned after the fact.

I was able to narrow down when the issue started to appear: `0.28.3` seems to have changed that behaviour for the Linux releases. Before that, environment inheriting worked.

**Comment by zcbenz** [comment]
This is unfortunately expected behavior on Linux, because Chromium uses a zygote process to fork renderer processes instead of forking them directly in parent process.

I tried to fix this by disabling zygote process (#1323), but it then produced more problems like #1605, so I have to bring it back (#2014).

To work around it you can probably read the env from `remote.process.env`.
