### ISSUE TITLE
Chrome switches clarification

### ISSUE THREAD

**Issue by bgSosh** [atom/electron#3342]
[This page](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md) suggests that only a small number of chrome switches are usable with electron (I assumed it was some kind of switch whitelist).  However, I've found that ones not on the list also seem to work (e.g. --in-process-gpu).  Please could you clarify what this list of switches is?  Perhaps it's switches that have been tested to work well with electron?  Are all chrome switches usable in theory?

**Comment by hokein** [comment]
You may view all chrome switches in https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/content_switches.cc. However, electron doesn't guarantee all the switches make sense since it's hard to test all these switches. The switches listed in electron's document are well tested and meet most of user requirements.

I think you can try the switch you needed, and see whether it works. If it won't, report back to the community.
