### ISSUE TITLE
Default Electron Save dialog doesn't allow saving files without extensions on windows. 

### ISSUE THREAD

**Issue by florinShm** [atom/electron#3346]
Tested with Electron 0.34.1

Repo steps: Try to download a zip file and delete file extension from Save dialog box. 
The following error is shown: "The file name is not valid".

It works as expected on OSX

**Comment by zcbenz** [comment]
Can you try v0.34.2? There was a fix on filenames in dialog.

**Comment by florinShm** [comment]
It's fixed. I had the 0.34.1 build for a while. I will switch to 0.34.2

Still comparing to Chrome, the only filter available when I save a zip file (for example) is All Files (*.*), and in Chrome I have zip Archive as well.

**Comment by dchest** [comment]
Looks like the issue is back in Electron 1.8.3. I have the following filters for `dialog.showSaveDialog`:

```
[{
   name: 'TXT File',
   extensions: [ 'txt' ]
},
{
  name: 'All Files',
  extensions: [ '*' ]
}]
```

When I select "All Files" in the save dialog, it wouldn't let me save (shows "The file name is not valid" dialog) a file without extension (e.g. "123"). When I type extension (e.g. "123.md"), it saves properly.

**Comment by hellobugme** [comment]
2.0.18 the same issue
