### ISSUE TITLE
runtime/cgo: could not obtain pthread_keys: Loading a Go module with electron

### ISSUE THREAD

**Issue by rodrigue-h** [atom/electron#3373]
Hello,
I'm trying to load with node-ffi a Go module (simple, nothing complicated).  
The same go module + js code works on **node.js** but not **electron**.
This is how I'm building the go module, (someone has a nice example of this working with node.js here: https://github.com/MrSaints/go-node-ffi):
`go build -buildmode=c-shared -o go-node-ffi.dylib`
Simple, basic electron app:

```
var app = require('app');  // Module to control application life.
var ffi = require('ffi');
[..]
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600});
  [...]
  var go = ffi.Library("gomodule", {
      "Add": ["int", ["int", "int"]]
      });
```
The exception is: 
```
runtime/cgo: could not obtain pthread_keys
	tried 0x118 0x119 0x11a 0x11b 0x11c 0x11d 0x11e 0x11f 0x120 0x121 0x122 0x123 0x124 0x125 0x126 0x127 0x128 0x129 0x12a 0x12b 0x12c 0x12d 0x12e 0x12f 0x130 0x131 0x132 0x133 0x134 0x135 0x136 0x137 0x138 [...]
```
Sounds like it should be possible to get this working on Electron, if someone can point me to the right direction, I can try and fix this and put up a pull request! 
I'm on MacOS.
Thanks,

**Comment by zcbenz** [comment]
Chromium itself is a much more complicated environment than Node.js, from [what I can find](https://groups.google.com/forum/#!msg/golang-nuts/Vy8r05reLyw/gO-wetcSAgAJ) go-lang runtime is using some hacky way to initialize the environment, which seems to conflict with Chromium's environment.

So I suggest using the module in scripts forked by `child_process.fork`, which is very similar to upstream Node's environment. The root cause is in go-lang's internals, so unless some core go-lang developer looks into this we are not able to solve it.

**Comment by cepinos** [comment]
Using child_process.fork as @zcbenz said worked for me. Thanks a lot!!!
