### ISSUE TITLE
Error when debugging Electron with node-inspector 

### ISSUE THREAD

**Issue by cyrusthegreatking** [atom/electron#3378]
When I want to open node-inspector to debug an Electron app I've got this error in opened node-inspector console:
```
Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\****\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.4\node-v46-win32-x64\debug.node
```
Node.js: 4.1.1.
Node Inspector: 0.12.3
Got this error both in electron-v0.33.7-win32-ia32 and electron-v0.34.3-win32-x64 with --debug=5858.

If use --debug-brk=5858 i've got bellow error in cmd:
```
Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
C:\Users\****\AppData\Roaming\npm\node_modules\node-inspector\lib\PageAgent.js:94
        var realBaseName = files.filter(function(filename) {
                                ^

TypeError: Cannot read property 'filter' of undefined
    at PageAgent.<anonymous> (C:\Users\****\AppData\Roaming\npm\node_modules\node-inspector\lib\PageAgent.js:94:33)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any help???

**Comment by zcbenz** [comment]
Can you try whether v0.34.0 works?

**Comment by cyrusthegreatking** [comment]
Yes. Error exist in v0.34.0.

**Comment by bluebruce** [comment]
Hello, is there any workaround for this issue? Does it mean that I can't use 'node-inspector' on windows platform?

**Comment by PauloLeal** [comment]
you can debug version ^0.30.0

**Comment by brenca** [comment]
Also exists in 35.1

**Comment by VoidVolker** [comment]
Have same problems with node 5.1 and Electron v0.35.2

Problem in file `node-inspector\lib\PageAgent.js` in function '_resolveMainAppScript > fs.readdir(dirname` - here `dirname` is path to `app.asar` and inspector can't read asar. For debug need to use unpacked application in real folder `resources/default_app` (looks like symlinks works too). But, after this we have next bug:

    Error: Cannot find module '...\node_modules\v8-debug\build\debug\v0.5.4\node-v46-win32-ia32\debug.node'

v8-debug builds are here: https://node-inspector.s3.amazonaws.com/debug/

In this case, source of bug is wrong version of installed v8-debug and b8-profiler versions. Same in linux. It can be fixed by rebuilding this 2 modules or installing or downloading correct version. 

And next we have bug with objects inspecting: 

    Runtime.getProperties failed.
    Object #0# not found

On this step I decide to find some other debugger )

**Comment by paulcbetts** [comment]
It sounds like the easiest way to get node-inspector running is to host it inside Electron itself, this would solve the ASAR and native version problems, so we'd be left with the Runtime.getProperties bug

**Comment by MathijsvVelde** [comment]
Here is som more data.
https://github.com/node-inspector/v8-debug/issues/18

I hope it helps fixing stuff

**Comment by 3y3** [comment]
I'll help to debug this problem in soon time.

**Comment by lukeapage** [comment]
Does anyone have any way to debug the electron node.js  main process javascript?
Do I understand that this page is out of date: https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md or are some people managing to debug ? Are they using node-inspector or something else? if node-inspector, are they doing something special to get it to work that isn't documented ?

**Comment by enlight** [comment]
In order to use `node-inspector` you need to:

1. Install a patched version of `node-pre-gyp` so that `node-inspector` and its dependencies can actually find the native modules built in the following step.
2. Rebuild `node-inspector` and its dependencies (specifically the native modules) to target the same Node runtime as Electron.
3. Execute `node-inspector` using Electron instead of regular Node, this can be done by setting a flag that starts Electron in "Run As Node" mode where Electron only loads the Node runtime without any of the Chromium stuff. This is important because the `fs` module in Electron is able to read files in an ASAR archive whereas plain old Node cannot, and node-inspector is going to want to read some things from the app ASAR.

This worked for me in v0.34, so hopefully it still works in more recent versions. I've got a couple of [Grunt tasks](https://github.com/debugworkbench/hydragon/tree/bf49f60ae1e9d6ded478ff3d1e591b7f568bb20f/build/tasks) to handle steps 1 & 3, and a patched version of [node-pre-gyp](https://github.com/enlight/node-pre-gyp) that probably needs to be updated with changes from upstream for v0.36 (because Node got upgraded from v4 to v5).

**Comment by lukeapage** [comment]
Thanks, I'll give it a go and contribute back to the documentation if I get it going.

**Comment by enlight** [comment]
FYI, I've just updated my `node-pre-gyp` branch from upstream, if you've cloned it blow it away and clone it again since I've force pushed the changes (I've got a PR languishing for that branch back upstream so want to keep it merge free).

**Comment by lukeapage** [comment]
Ok thanks, I've got alot closer. Here are my instructions so far

1. `npm i node-inspector`
2. `npm i git+https://git@github.com/enlight/node-pre-gyp.git#detect-electron-runtime-in-find`
3. Find the Electron Node.js runtime version (https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#native-node-module-compatibility)
4. So, for Node 5.1.1...
`node_modules/.bin/node-pre-gyp reinstall --target=5.1.1 --directory node_modules/v8-debug`
5. run node-inspector
`ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 build/develop/electron.exe node_modules/node-inspector/bin/inspector.js`
6. run electron with `--debug-brk`
7. go to the debugging URL

However, I think the node-pre-gyp reinstall step is not working as I get
```
Error: Cannot find module 'path\to\project\node_modules\v8-debug\build\debug\v0.7.0\electron-v0.36-win32-x64\debug.node'
```

When I run the node-pre-gyp I get

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.17
node-pre-gyp info using node@4.2.3 | win32 | x64
node-pre-gyp info chdir node_modules/v8-debug/
[v8-debug] Removing "path\to\project\node_modules\v8-debug\build\debug\v0.7.0\node-v47-win32-x64"
node-pre-gyp info check checked for "path\to\project\node_modules\v8-debug\build\debug\v0.7.0\node-v47-win32-x64\debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v0.7.0/node-v47-win32-x64.tar.gz
node-pre-gyp http 200 https://node-inspector.s3.amazonaws.com/debug/v0.7.0/node-v47-win32-x64.tar.gz
node-pre-gyp info install unpacking debug.node
node-pre-gyp info tarball done parsing tarball
node-pre-gyp info validate Running test command: 'C:\Program Files\nodejs\node.exe --eval 'require(\'path\to\project/node_modules/v8-debug/build/debug/v0.7.0/node-v47-win32-x64/debug.node\')''
[v8-debug] Success: "path\to\project\node_modules\v8-debug\build\debug\v0.7.0\node-v47-win32-x64\debug.node" is installed via remote
node-pre-gyp info ok
```

so I guess that instead I need to run

```
 node_modules/.bin/node-pre-gyp reinstall --target=0.36.2 --runtime=electron --directory node_modules/v8-debug/
```

which of course isn't available as a binary. I'm guessing recompiling might work but I don't have all that setup, so I tried copying the `debug.node` into the directory and got `Error: A dynamic link library (DLL) initialization routine failed.`

so I'm guessing I need to install python and ms C++ etc. and run the command above ? Am I on the right track?

**Comment by enlight** [comment]
Yes, you'll need to rebuild the native modules so MSVC needs to be installed, Python I'm not so sure about, I've had both installed since the dawn of time. As suggested in the linked tutorial I just use [electron-rebuild](https://github.com/paulcbetts/electron-rebuild) to perform steps 2-3. Keep in mind that `node-inspector` has more than one native dependency (`v8-debug`, and `v8-profiler` are the two I recall) so it's probably best to rebuild everything in `node_modules`.

**Comment by lukeapage** [comment]
I got it working eventually and made a PR for documentation - https://github.com/atom/electron/pull/4004

I tried electron-rebuild and it couldn't find my electron.exe because I used npm@3 :(

Its still a little flakey (seemed to take a couple of attempts to "latch on") but it does work.

**Comment by PauloLeal** [comment]
It's working for me on electron 36 + webstorm 11 (updated version). They fixed it on dec 23 build. Worked on vs code since electron 36 release.

**Comment by lukeapage** [comment]
@zcbenz is this really a bug? I see you added the windows label - I am on windows.
If this issue is to stick around I think it is a bug to record "Allow node-inspector to work without having to run it through electron".. any disagreement from other commentators on this bug?

**Comment by enlight** [comment]
@lukeapage I'm using NPM v3 (still on Node v4 though) along with `electron-rebuild` and `electron-prebuilt`, so I wonder what sort of issue you ran into.

**Comment by lukeapage** [comment]
@enlight it was this issue https://github.com/electronjs/electron-rebuild/issues/39
rather than include instructions on hacking electron-rebuild I changed the instructions to use node-pre-gyp because at least that way its guarenteed to work with any setup.

**Comment by zcbenz** [comment]
Since now we have a reliable way to run node-inspector, I think it is good to close this issue.
