### ISSUE TITLE
Notification on windows closes app when using icon

### ISSUE THREAD

**Issue by NitroGhost** [atom/electron#3458]
when I add an icon to the notification, it closes the app when invoked, but omitting the icon does not. I created a button and on click invokes the following:
```js
function notify() {
    new Notification("Title", {body: "test notification", icon: "file:///path/to/icon.png"});
}
```
I have tried local png file, and also a http png as well, but both result in app closure. Using electron v0.35.0 32bit on Windows 10 Pro

**Comment by felixrieseberg** [comment]
Yep, regression confirmed. We had it working a few days ago, so it can't be hard to get this back to a working state.

**Comment by felixrieseberg** [comment]
Fixed in https://github.com/atom/brightray/pull/175. Sadly, you'll have to wait for a new release...

@zcbenz: Your amazing cleanup of the toast code introduced a mini typo (and I realize that this just means that I should start thinking about ways for us to test on Windows). I'm closing this for now, it'll be all good as soon as you release v0.35.1 :zap:

**Comment by raleksandar** [comment]
I have just tested 0.35.1 on Windows 10 and this simple example crashes the app:

````html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script>
        function notify() {

            var myNotification = new Notification('Title', {
                body: 'Lorem Ipsum Dolor Sit Amet'
            });

            myNotification.onclick = function () {
                console.log('Notification clicked')
            }
        }
    </script>
</head>
<body>
<button onclick="notify()">Notify!</button>
</body>
</html>
````

Note that there is no icon used (it crashes with valid icon URI too).

This is `process.versions` output:
````js
{
    "http_parser": "2.5.0",
    "node": "4.1.1",
    "v8": "4.5.103.29",
    "uv": "1.7.4",
    "zlib": "1.2.8",
    "ares": "1.10.1-DEV",
    "modules": "46",
    "openssl": "1.0.2d",
    "electron": "0.35.1",
    "atom-shell": "0.35.1",
    "chrome": "45.0.2454.85"
}
````

**Comment by NitroGhost** [comment]
can confirm

        throw err;
          ^
Error: Cannot find module 'TimeSlice'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\aileen\obiter-app\gulpfile.js:6:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by NitroGhost** [comment]
can confirm

**Comment by felixrieseberg** [comment]
WOULD EVERYONE PLEASE STOP BREAKING THE NOTIFICATION CODE

I'll take a look and see what happened.

**Comment by felixrieseberg** [comment]
@zcbenz: [This change here](https://github.com/atom/brightray/commit/ffa69a49bf0a77efd4a04fa2b4e60a87eb1a24b4) broke notifications - the appId you're trying to retrieve is never set. Happy to help here though - why did you want to use the appId instead of the app's name? Can we roll back to the app name to get notifications working again?

Everyone: @zcbenz broke it, but Electron is his baby - so I don't want to mess with code he just merged. I'm happy to upload a working build of Electron without the breaking commit so that everyone can continue working until we have this fixed again in master.

**Comment by paulcbetts** [comment]
https://github.com/atom/brightray/issues/176 explains why we should use the explicit app model ID

**Comment by zcbenz** [comment]
Sorry for breaking this again, as workaround you can set Application User Model ID with [app.setAppUserModelId](http://electron.atom.io/docs/v0.35.0/api/app/#app-setappusermodelid-id-windows), which you should otherwise Notifications won't work on Windows 8 anyway.

I'll change the code to use application name when Application User Model ID is not available.

**Comment by felixrieseberg** [comment]
Oh dang, that makes sense - I didn't even think about that. Awesome, thank you very much :clap:!

**Comment by raleksandar** [comment]
Just to confirm that setting explicit Application User Model ID works. Notifications are displayed with and without icons, yay!. Thanks everyone!

Only thing is that in Windows 10's Action Center this AppUserModelId is shown as group title instead of a window title. I have followed the `CompanyName.ProductName.SubProduct.VersionInformation` format and this looks ugly. I guess that I can just leave `ProductName` part as AppUserModelId but this can have potential clashes with other programs and more importantly once I integrate auto-updater the AppUserModelId must have `com.squirrel.PACKAGE_ID.YOUR_EXE_WITHOUT_DOT_EXE` format.
Is there a way to set this string to the `app.getName()`?

**Comment by raleksandar** [comment]
This is what I'm talking about:
![action-centre](https://cloud.githubusercontent.com/assets/33291/11371775/85360adc-92ca-11e5-94d0-9a45f7bf859f.png)

I'd like to have `app.getName()` as a group title instead of AppModelUserId

**Comment by etiktin** [comment]
Is `AppUserModelId` only needed for displaying notification on Windows 8/8.1?
If so, we could add a condition to use it only for those versions and use the app name for Windows 10.

**Comment by raleksandar** [comment]
Well, it seems that [Group property](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.notifications.toastnotification.aspx) is available on `ToastNotification` class starting with Windows 10. While I cannot find anywhere in the MSDN confirmation I believe this is the value Windows will use for Action Center and if not available fallback to `AppUserModelId`.

**Comment by lipis** [comment]
Now we just need a new release :)
