### ISSUE TITLE
Getting tray position on multi-monitor setup

### ISSUE THREAD

**Issue by danawoodman** [atom/electron#3500]
Is there a way to get an accurate `bounds` on OSX when clicking a tray icon using multiple monitors?

I have my MBP 15" screen attached to a Thunderbolt display and am getting bounds like this from the second display (Thunderbolt):

```js
{
  x: 3560,
  y: -764
}
```

Positioning is broken on the second display because of this. Wondering if there is a work around, flag, etc.. I could use?

**Comment by bengotow** [comment]
I'd be interested in this as well. Technically, those X and Y coordinates could be valid on Mac OS X, if your primary display was arranged beneath your secondary display, but you clicked the tray in the menu bar on the secondary display:

```
NSWindow's frame is in a global coordinate system relative to the frame origin of the zero screen.
```

Just out of curiosity, what happens when you try to create a BrowserWindow at those coordinates? Also, if you move a BrowserWindow to the correct position on the screen (beneath the tray icon), and run `browserWindow.getBounds()`, what different value does it give you? I think that'll help track this down.

**Comment by zcbenz** [comment]
I agree the coordinates are actually correct, I'm closing this since there was no reply.

**Comment by okonet** [comment]
I've the same problem it seems. I have 2 monitors arranged as main on top and the secondary beneath it. I'm always get coordinates related to the secondary one (probably because I'm starting electron process using Terminal which is located on the secondary monitor?). Either way, since macOS supports multiple monitors, the `getBounds` should probably take the active tray into account?

**Comment by okonet** [comment]
Not sure why, but sometimes it's doing that and sometimes not... I'll investigate more and update this one.
