### ISSUE TITLE
Need symbols for Blink code paths

### ISSUE THREAD

**Issue by nathansobo** [atom/electron#3502]
We're trying to work with the Chrome team and debug some long layouts we're experiencing in Atom, but we don't have access to symbols for consumption by Instruments on OS X. Could we please make symbols available so we can understand what's occurring inside the render process?

/cc @zcbenz

**Comment by zcbenz** [comment]
Steps:

1. Follow http://electron.atom.io/docs/v0.35.0/development/build-instructions-osx/ to clone and bootstrap Electron
2. Build a Release version `./script/build.py -c R`
3. Use the `out/R/Electron.app` to build Atom, you can replace the `electron/Electron.app` under `atom` dir with it and then run `script/build`
4. In Instruments, do a profile of the newly built `Atom.app`
5. Open menu `File` -> `Symbols...`
6. Find the `Electron Framework` in the sidebar tree<br/>
<img width="218" alt="screen shot 2015-11-19 at 10 32 33 am" src="https://cloud.githubusercontent.com/assets/639601/11260739/de1d99e2-8ea8-11e5-9217-15efa9556f0d.png">
7. Click the `locate` button in<br/>
<img width="168" alt="screen shot 2015-11-19 at 10 33 40 am" src="https://cloud.githubusercontent.com/assets/639601/11260764/0aabc0c4-8ea9-11e5-970c-9362a31f16f4.png">
8. Load the `Electron Framework.framework.dSYM` which can be found in `out/R` under the Electron dir
9. All addresses are now symbolized

Sorry I can not upload the symbols directly since they are _huge_, I'll provide the dSYM symbols in Releases directly in future so it wouldn't be so painful.
