### ISSUE TITLE
Electron 0.34.1 on Mac 10.8.5: EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by bpasero** [atom/electron#3530]
See https://github.com/Microsoft/vscode/issues/296 for details. The stacktrace seems to be all in Electron land. Any ideas?

**Comment by zcbenz** [comment]
It is probably because we called some new APIs that not available on 10.8, but since [Chrome is ending the support for OS X 10.8](http://chrome.blogspot.ca/2015/11/updates-to-chrome-platform-support.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+blogspot/Egta+(Google+Chrome+Blog)),  I don't think we need to fix it.

**Comment by bpasero** [comment]
@zcbenz so in other words, Electron requires at least 10.9 to function?

**Comment by zcbenz** [comment]
Yeah, I think we used to support 10.8, but at some time we broke that and no one complained.

**Comment by bpasero** [comment]
Ok thanks.
