### ISSUE TITLE
Reply from notification on Mac

### ISSUE THREAD

**Issue by evgenyzinoviev** [atom/electron#3547]
Starting from Yosemite, if i'm not wrong, you can answer to messages directly from desktop notifications.
<img width="358" alt="screen shot 2015-11-22 at 2 59 17 pm" src="https://cloud.githubusercontent.com/assets/6204306/11324151/df2bac74-9129-11e5-8bb9-c132ac5279a2.png">

Is it possible to implement with Electron, and if not, are there plans to support this feature?

**Comment by bengotow** [comment]
We implemented this briefly in N1 using NodObjC, the node <=> objective-c bridge: https://github.com/nylas/N1/blob/master/src/browser/native-notification-manager.coffee. It's currently disabled because it caused intermittent crashing with Electron 0.29.2, but I think newer versions may be fine. (Registering delegates and preventing them from going away during Javascript garbage collection was a problem.)

Until recently, Electron's notifications were just the standard "Web notifications" from Chromium. I'm not sure if the recent changes to support Win10 mean they're handled in Electron now?

**Comment by paulcbetts** [comment]
> Until recently, Electron's notifications were just the standard "Web notifications" from Chromium. 

Nope, they've always been native. On OS X, we support most of the features except for the ones described above, because the HTML5 Notification class doesn't natively support it, so being able to reply means we've got to completely ditch Chromium's support for the `Notification` class and recreate our own. There are enough of these kinds of features popping up that this might be Worth It, but right now, we don't

**Comment by bengotow** [comment]
Ahh gotcha - that makes sense. When I saw it was the Chromium web Notification API I figured it came for free in Chromium. 👍

**Comment by zcbenz** [comment]
I'm merging this to #3359, since both issues would require us to provide a whole set of new notification API.
