### ISSUE TITLE
Provide and access file outside of *.exe?

### ISSUE THREAD

**Issue by intellent** [atom/electron#3581]
My situation is a follows:

My electron app is a game, which has different levels. All levels are serialized in one JSON file, which is loaded and parsed every time the app is started. However, I want the user to be able to change the level file after he/she as installed the app (Windows only).

Currently my JSON file resides within the app directory. However after having built a release on Windows and installed the app to C:\Program Files\MyApp I cannot edit the JSON anymore (since it has been packaged into the *.exe, I guess).

Is there any way to move the JSON out of the *.exe into the actual installation (or user/appdata) directory and read it from there within electron?

What’s the best way to solve and test this without having to build and install the app every time?

PS: I’m using https://github.com/szwacz/electron-boilerplate for my app.

**Comment by bengotow** [comment]
Hey @intellent — this is a great question. Since Electron uses NodeJS, you can use the `fs` module in NodeJS to access the filesystem. For your game, it might make sense to check to see if the user has a custom JSON file, and fall back to the default one in the app. Alternatively, you could copy the JSON file into /user/appdata the first time it's launched so they can see it and edit it there.

The code would look something like this:
```
var app = require('electron').app;
var fs = require('fs');
var path = require('path');

var customJSONPath = path.join(app.getPath('userData'), 'my-levels.json')

if fs.existsSync(customJSONPath)
   // load from this path
else
   // load from default path
```

**Comment by zcbenz** [comment]
You can also reference how Atom and VSCode implement their user preferences.
