### ISSUE TITLE
Tray icon tooltip doesn't show when dock icon is hidden

### ISSUE THREAD

**Issue by detj** [atom/electron#3599]
When dock icon is hidden by calling `app.dock.hide()`, the tooltip of the Tray icon stops showing despite `Tray.setToolTip()` being called correctly.

If I don't hide the dock icon, tooltip of the Tray icon shows normally.

```
let app = require('app');
let Tray = require('tray');
let appIcon = null;

app.dock.hide();

app.on('ready', () => {
  appIcon = new Tray('icon.png');
  appIcon.setToolTip('hello from tooltip');
});
```

`v0.35.0`

**Comment by zcbenz** [comment]
This seems to be an undocumented behavior of OS X, I'm afraid there is no way to fix it. :(

**Comment by niftylettuce** [comment]
Can we please document this in the Tray.md documentation under `setToolTip` so people don't go crazy?

**Comment by niftylettuce** [comment]
Also, Dropbox works without a Dock icon, all Dropbox has is a menubar and they still figured out how to make the tooltip show.  Maybe you should re-open this.

**Comment by detj** [comment]
True. Google Drive mac client does that too.

![https://cldup.com/wB2uMv7Ddk.png](https://cldup.com/wB2uMv7Ddk.png)
![https://cldup.com/6LjLiAISXS.png](https://cldup.com/6LjLiAISXS.png)

**Comment by jasongrlicky** [comment]
Hi there! Having developed several menubar-only Mac apps myself, you should know that you may need to set the `LSBackgroundOnly` and `LSUIElement` keys to `YES` in your app's `Info.plist` in order to get the tooltip to function properly without a dock icon. You can read all about it in [Apple's Launch Services Documentation](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html).

This means that in order to set these keys, you'll need to bundle your app up using [electron-packager](https://github.com/electron-userland/electron-packager) and possibly set the `Info.plist` keys yourself with scripts afterwards. Here is an excerpt of my app's `Info.plist` with these keys filled in:

```
<key>LSBackgroundOnly</key>
<true/>
<key>LSUIElement</key>
<true/>
```

Hope that helps!

**Comment by tiangolo** [comment]
For those that end up here like me and try to use @jasongrlicky's instructions, if you are using [electron-builder](https://github.com/electron-userland/electron-builder), it seems you can set the `Info.plist` configurations in your `package.json` and it will set it up for you: https://github.com/electron-userland/electron-builder/issues/1456

**Comment by nathanbuchar** [comment]
☝️ like this:

```json
"mac": {
  "extendInfo": {
    "LSBackgroundOnly": 1,
    "LSUIElement": 1
  }
}
```

**Comment by hovancik** [comment]
Hey guys, anyone here using `app.hide()` with tray tooltip? My issue is that tray tooltip wont show after `app.hide()`. I described issue at https://github.com/electron/electron/issues/9447

**Comment by nathanbuchar** [comment]
@hovancik Did the above solution not work for you? Are you using [electron-builder](https://github.com/electron-userland/electron-builder)?

**Comment by hovancik** [comment]
@nathanbuchar I use electron-builder. Your solution works but only until I use `app.hide()`. After that, no tooltip is shown.

**Comment by rocketlaunchr-cto** [comment]
@hovancik Have you tried using @MarshallOfSound advice in https://github.com/electron/electron/issues/422 to hide the dock icon.

If you use his technique, you can hide the dock icon without using `app.dock.hide()`

**Comment by hovancik** [comment]
@rocketlaunchr-cto I am not using `app.dock.hide()`, my issue is a bit different
