### ISSUE TITLE
Chrome 47

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron#3665]
Whats the schedule for upgrading to chrome 47.

**Comment by bennyn** [comment]
Would be really nice to get Chrome 47! 

Because the company I work for is building an Electron app which makes heavy usage of WebRTC and there is a WebRTC bug in Chrome 45 & 46 which has been fixed in Chrome 47+. 

So we really would like to upgrade our Electron app to Chrome 47 which is the stable release for production since yesterday: http://googlechromereleases.blogspot.de/2015/12/stable-channel-update.html

**Comment by etiktin** [comment]
Asked and answered in https://github.com/atom/electron/issues/3610#issuecomment-160538689 .

**Comment by dlmanning** [comment]
@etiktin : No, not really. They were asking about Chrome 47, not 46.

**Comment by dlmanning** [comment]
Also, this discussion could be relevant since Chrome 47 uses v8 4.7. Not sure exactly what the implications are of mixing that with v8 4.6 in Node 5.x stable.

https://github.com/nodejs/node/pull/4106

**Comment by etiktin** [comment]
@dlmanning both the OP and the issue I linked to were asking about the next update to Electron's Chromium (the linked issue was closed 3 days ago). The answer mentioned that 46 will probably be skipped due to issues with their internal build servers. On some other issues Cheng said we'll probably jump to 47 (see https://github.com/atom/electron/issues/3312#issuecomment-153632338).
So there's no official ETA, but they are working towards it.

**Comment by paulcbetts** [comment]
Like, can I lean on someone to make this happen? Can Slack sponsor the build servers? I've got a computer under my desk we can use. Anyone? @jnewland?

**Comment by zcbenz** [comment]
Fixed by #3714.

**Comment by herrmannplatz** [comment]
Faster than expected. Thanks:)
