### ISSUE TITLE
a Link in documents does not work - ipcMain -> webContents

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#3693]
on this page http://electron.atom.io/docs/v0.35.0/api/ipc-main/
the link to webContents.send doesn't work. I cannot (at a glance) see why

**Comment by xywz** [comment]
The page you want is http://electron.atom.io/docs/v0.35.0/api/web-contents/#webcontents-send-channel-arg1-arg2.

ipc-main.md is linking to `web-contents.md#webcontentssendchannel-args` instead of `web-contents.md#webcontentssendchannel-arg1-arg2-` (GitHub) or `web-contents.md#webcontentssendchannel-arg1-arg2` (Electron website). The difference is the `-` at the end.

**Comment by lukeapage** [comment]
if you look at the broken link you will see the page is broken not just the
# bookmark. will fixing the bookmark also fix the page url? thats what i
meant when i said i wasn't sure what would fix it.

**Comment by jlord** [comment]
The docs at `electron.atom.io` are slightly different than they are in their raw form in this repository. I'm going to close here and link this issue there :+1:

**Comment by lukeapage** [comment]
thanks @jlord I'll raise a PR to fix the hash part of the problem.
