### ISSUE TITLE
autoUpdater: Couldn't read PKZip signature

### ISSUE THREAD

**Issue by anovi** [atom/electron#3765]
Electron's auto-updater downloads a zip file and then i get an error:

```
2015-12-10 23:11:16.602 Electron[26260:1278592] Download completed to: file:///Users/novickova/Library/Application%20Support/com.github.electron.ShipIt/update.KsIOvUy/Optima-0.0.2.zip
{ [Error: ditto: Couldn't read PKZip signature: (null)]
  preventDefault: [Function: preventDefault],
  sender:
   EventEmitter {
     setFeedURL: [Function: setFeedURL],
     checkForUpdates: [Function: checkForUpdates],
     quitAndInstall: [Function: quitAndInstall],
     setFeedUrl: [Function],
     _events:
      { error: [Function],
        'update-available': [Function],
        'update-not-available': [Function],
        'checking-for-update': [Function],
        'update-downloaded': [Function] },
     _eventsCount: 5 } }
```

Have i missed something?

**Comment by zcbenz** [comment]
From [this blog](http://ocportal.com/site/news/view/chris_grahams_blog/problem_between_the_mac_2.htm) this is caused by Zend zip code not respecting ZIP specification, you probably want to change how the zip file is created.

If you still have more questions, I suggest posting them to https://github.com/Squirrel/Squirrel.Mac, which is the library we use for auto updating.

**Comment by develar** [comment]
Yes, it is not an electron issue. I also get this error — because I use https://github.com/GitbookIO/nuts and there is no ZIP in my github releases (so, DMG is returned and it cannot be unpacked).

**Comment by mzmousa** [comment]
@zcbenz @develar was there ever a fix for this or reason to why it happened?

**Comment by develar** [comment]
@mzmousa If I understand correctly, you use electron-builder. electron-builder creates zip for you — so, please ensure that your update server correctly returns it. Open issue in the electron-builder project.

**Comment by Daniel-Sudhindaran** [comment]
For anyone else still having this issue, it turned out I was using a bad npm script.
`"electron:build:all": "vue-cli-service electron:build -- --mac dmg --win nsis"`
Basically I was explicitly limiting the build to produce just a dmg and nsis for some reason. When I took that out and added this 
`"electron:build:all": "vue-cli-service electron:build -- --mac --win"` it works like a charm!
