### ISSUE TITLE
`globalShortcut.isRegistered` does not work

### ISSUE THREAD

**Issue by wearhere** [atom/electron#3808]
Given this code

```js
app.on('ready', function() {
  var defaultMenuBarIconShortcut = 'Cmd+Q';
  if (globalShortcut.isRegistered(defaultMenuBarIconShortcut)) {
    console.log('Can\'t register');
  } else {
    console.log(globalShortcut.register(defaultMenuBarIconShortcut, function() {
      console.log('Shortcut triggered');
    }));
  }
});
```

I would expect to see "Can't register" logged to the console. Instead, my shortcut is registered, overriding "Cmd+Q" system-wide. :grimacing: 

In addition, `globalShortcut.register` returns `true`.

**Comment by wearhere** [comment]
Ok per my understanding of [the code](https://github.com/atom/electron/blob/e5e4749eb3c592667922f87c1105981db9dd84f7/atom/browser/api/atom_api_global_shortcut.cc#L61) `isRegistered` isn't even built to check the system, but rather just the list of shortcuts registered by the current app, is that right?

If so, that's still kinda misleading IMO in that the `globalShortcut` module should check _global_ registrations, but at least that's unsurprising that it doesn't work.

_But_, `register` should still return `false`, at the least.

**Comment by wearhere** [comment]
I believe that it should be possible to make an `isRegistered` that works system-wide—I note that some of my other applications can do it:

<img width="532" alt="screen shot 2015-12-13 at 11 23 35 pm" src="https://cloud.githubusercontent.com/assets/110000/11775089/b3f0788c-a1f0-11e5-9990-78dcc79a6655.png">

**Comment by zcbenz** [comment]
Yeah this API currently only checks for the shortcuts registered by this app and I agree we should make it system-wide, but I don't think it is possible for third party apps. OS X doesn't provide a public API to check whether a shortcut is registered, and the API registering shortcuts doesn't report error when a shortcut is taken by another application, I'm sure there is some private API to achieve this, but they are not documented anywhere.

Also for the example you provided, I think it is not checking for global shortcuts, it is just checking whether a shortcut is registered by a menu item used by the same application.

I'm closing this as won't fix because it is technically unfixable, but if anyone finds out to do it, I'll reopen this issue.

**Comment by wearhere** [comment]
Ok, thanks @zcbenz. I'll note for posterity that it does appear possible to make the shortcuts truly exclusive by passing [`kEventHotKeyExclusive`](https://gist.github.com/wearhere/de49aaebb8393de0955b#file-carbonevents-h-L15424) to `RegisterEventHotKey` whereas [we currently pass 0](https://github.com/atom/electron/blob/master/chromium_src/chrome/browser/extensions/global_shortcut_listener_mac.mm#L218), in which case `register` _would_ start returning `false`, but since this would be a breaking change in terms of the API's current behavior and we still wouldn't have a way to make `isRegistered` "work" maybe best to leave as is.

**Comment by wearhere** [comment]
I suppose if non-Electron apps are using `kEventHotKeyExclusive` it could be possible for `register` to return `false` atm.
