### ISSUE TITLE
get custom url protocol params in osx

### ISSUE THREAD

**Issue by tinybug** [atom/electron#3847]
I have register a custom url protocol in my info.plist, and I can invoke my application by browser, but I can't get the parameter I pass. It dosen't like windows, I can get the parameter from command line argv. I have tried to listen 'app-finish-launching', 'open-file' and 'open-url', but it dosen't work. I have found 'kInternetEventClass' handle in 'atom_application.mm'. How can I get the parameter in js?

**Comment by zcbenz** [comment]
Can you provide an example app?

**Comment by tinybug** [comment]
@zcbenz this is my example: https://github.com/tinybug/electron-example

open 'example://i-wanna-get-this-param' in safari.

I wanna get the params behind the example protocol when I open the application.

**Comment by zcbenz** [comment]
There are two problems in your code:

First, you need to listen to the `open-url` event instead of `open-file` event, since your app is registered to  URL schemes.

Second, you also need to listen to `open-url` event __before__ the `ready` event of `app` gets emitted, that's because when OS X opens your app to handle the scheme, it will emit the `open-url` event very early. You can reference [how Atom does this](https://github.com/atom/atom/blob/master/src/browser/main.coffee#L23-L37).

**Comment by tinybug** [comment]
Great, thanks a lot.
