### ISSUE TITLE
Support for blurred transparent window

### ISSUE THREAD

**Issue by terrysahaidak** [atom/electron#3862]
Many peoples ask for a blurred transparent window.

It's really cool to have this feature. I've found some done code for that. It should work on windows and mac.

First, there is a fork of an electron where it done for mac [link](https://github.com/evgenyzinoviev/electron-vibrancy-demo/commit/7417821ad8f7ff6e9c669a3c3da35133c128f160).

Also, windows have this feature [link](http://stackoverflow.com/questions/31151539/native-aero-blur-without-glass-effect-on-borderless-wpf-window).

Why can't you do that?

**Comment by evgenyzinoviev** [comment]
Well, If you or anyone else here is interested I (maybe with someone's support, since I don't have so much time) could try to improve my fork and make some kind of API to create and inject vibrant views, but I guess that it's not so trivial to make universal API, because, for example, the user may wish to create a view with custom shape (circle view or custom-rounded-rectangle view or something else), but we could start with simple square views.

**Comment by zcbenz** [comment]
I'm merging this to #3002.
