### ISSUE TITLE
Reorganize node.js module names to avoid name collision.

### ISSUE THREAD

**Issue by pilwon** [atom/electron#387]
Please consider reorganizing node.js module names to avoid name collision:

From
```js
var app = require('app');
var BrowserWindow = require('browser-window');
var ipc = require('ipc');
var tray = require('tray');
...
```
to
```js
var app = require('atom.app');
var BrowserWindow = require('atom.browser-window');
var ipc = require('atom.ipc');
var tray = require('atom.tray');
...
```
or
```js
var app = require('atom-shell/app');
var BrowserWindow = require('atom-shell/browser-window');
var ipc = require('atom-shell/ipc');
var tray = require('atom-shell/tray');
...
```

**Comment by zcbenz** [comment]
As suggested by @kevinsawicki, we can move all APIs under one `atom-shell` module to avoid polluting module search paths:

```javascript
var atomShell = require('atom-shell');
var BrowserWindow = atomShell.BrowserWindow;
```

**Comment by bwin** [comment]
Seems like a nice idea.

**Comment by paulcbetts** [comment]
@zcbenz I'd still use the `requireNamespaceForBuiltin` method because otherwise it's a pretty big breaking change to existing code (or at least have a deprecation period)

**Comment by zcbenz** [comment]
> @zcbenz I'd still use the requireNamespaceForBuiltin method because otherwise it's a pretty big breaking change to existing code (or at least have a deprecation period where both are supported)

It makes sense to me.

**Comment by Subash** [comment]
ES6 will make that even more awesome,
```js
const { BrowserWindow } = require('atom-shell')
```

**Comment by pilwon** [comment]
When implementing...

```js
require('atom-shell').BrowserWindow
```

...please consider using [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)'s getter to lazy load modules on demand. Preloading every module would delay the initial app loading. It won't scale with tons of submodules `atom-shell` may introduce in the future too. Another approach to this anticipated issue is to give developers both options: `require('atom-shell').BrowserWindow` for preloading and `require('atom-shell/browser-window')` for lazy loading.

**Comment by kevin-smets** [comment]
Any news on this?

**Comment by paulcbetts** [comment]
Has anyone ever in practice hit a conflict between an NPM module and a builtin module? (PS: please don't just go searching NPM for name conflicts, I'm talking about someone who actually had trouble writing their Electron app because of this problem). 

I've never seen a single person file a bug where this stopped them from writing their app, only people who are worried about the theoretical possibility

**Comment by kevin-smets** [comment]
Well, we currently have a large codebase in production, with multiple (open source and homegrown) libraries, built upon Angular, **RequireJS**, etc. I can't say much more about it without checking internally if I'm allowed to disclose more, but it's corporate scale and serves over a million users.

We are currently looking into distributing our app as native apps into the appropriate OS stores, currently it's a hybrid app with Cordova but also runs as a standalone website. Integration through Cordova gives us a big advantage to tie into native features. Integration with the OS / node side with Electron is currently disabled, making it no more than a wrapped webview sadly. So this integration is right now on hold, and probably will be canceled alltogether if no clean solution can be found (so it's pretty much waiting game for now).

And as a bonus, removal / replacement of RequireJS got scrapped for the time being as well, so => sad :panda_face:

**Comment by kfranqueiro** [comment]
@paulcbetts I agree that this seems like a huge change for what seems like largely a theoretical issue (or one caused by questionable use of other tools that arguably aren't even relevant within an electron environment - e.g. I've seen someone get bitten using browserify together with electron since browserify exports empty modules for various node built-ins).

That being said, admittedly I think @mattdesl has a point, and this seems reasonable as long as it doesn't defeat the lazy-loading of modules (which it seems like it doesn't, the PR seems to have incorporated the getter idea described by @pilwon).
