### ISSUE TITLE
Won't work on Pentium 4

### ISSUE THREAD

**Issue by Cheapskate01** [atom/electron#4037]
Hey, just to let you know, the upgrade to Chrome 47 breaks electron for Linux users with Pentium 4 processors. Chrome fails to work on my system since the upgrade to 47. Chromium works, so if you want full compatibility, I can recommend switching to Chromium. I found a workaround that involves turning off a proprietary driver, but in my version of Elementary OS, the option isn't available.

**Comment by zcbenz** [comment]
The prebuilt binaries of Electron are compiled with clang binaries provided by Chromium, which is very new and doesn't seem to support your processor. As for the chromium browser, its binaries are provided by community and are usually compiled with the default compilers of the Linux distribution, I think that's why it works.

The solution is to compile Electron with your Linux distribution's compilers, and I'm merging this to #259.
