### ISSUE TITLE
overlayScrollbar of webPreference is not working in v0.36.3

### ISSUE THREAD

**Issue by princejwesley** [atom/electron#4038]
As per the release notes and [this commit](https://github.com/atom/electron/commit/c6e03f83905b6784619bc5db8404fe75df1dc4e2), `overlayScrollbar` property is enabled by default.

After upgrading electron version from `0.36.2` to `0.36.3`, `overlayScrollbar` feature doesn't seem to work.

 `0.36.3`:
![image](https://cloud.githubusercontent.com/assets/1622515/12217526/4b6cfe7c-b729-11e5-842a-135afc96aa9b.png)

 `0.36.2`:
![image](https://cloud.githubusercontent.com/assets/1622515/12217510/d78aaefa-b728-11e5-9894-60313b6b929b.png)

**Comment by zcbenz** [comment]
`overlayScrollbar` is turned on by default when it is enabled in system, in your case I think it is because your system settings disabled overlay scrollbar.

If you still want to force turning it on, you can use the new `blinkFeatures` option:

```js
new BrowserWindow({
  webPreferences: {
    blinkFeatures: 'OverlayScrollbars'
  }
});
```

I didn't know people are actually using this option, sorry for breaking this.

**Comment by flying-sheep** [comment]
@zcbenz hi, what do you mean “enabled in system”?

is it a compile option or…?
