### ISSUE TITLE
Deleted blobs in IndexedDB are never cleaned up

### ISSUE THREAD

**Issue by bensie** [atom/electron#4096]
Below is Explorer's list of blobs that were stored in IndexedDB, but have since been deleted via IndexedDB's API in the app. The files are never purged from the filesystem even though they were deleted (apparently successfully from the dev tools perspective). Closing the application and reopening does not clear them either, they seem to stick around forever. Behavior is the same on Mac and PC, Electron 0.36.3. 

![image](https://cloud.githubusercontent.com/assets/4595/12313168/fae4e5fc-ba19-11e5-818d-e4ef4cd4fd6c.png)

Thanks for your work on Electron!

**Comment by zcbenz** [comment]
I can reproduce the same problem in Chrome browser by using [MDN's example](https://mdn.mozillademos.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB$samples/Full_IndexedDB_example?revision=967085), after some search, I think it is because [Chrome just marked the data as deleted](http://stackoverflow.com/questions/15841828/why-does-empty-indexeddb-still-take-up-space) instead of deleting them immediately, until it has used too much disk space. This totally makes sense because that's how database works.

**Comment by bensie** [comment]
Thanks for looking into it @zcbenz, appreciate your time.
