### ISSUE TITLE
Disclose in documentation more details of sponsership and level of commitment

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#4104]
For the sake of larger companies looking to invest in using Electron technologies, would it be possible to disclose Githubs level of sponsership or if Microsoft pay any employees to help out ?

Does Github pay for people to be permanently on Electron? Is there any roadmap beyond 1.0 or once that is reached might Github stop that? Or is this maintained by people in their own free time?

Its clear the project has already been adopted by alot of projects, but some knowledge of the future would be good to put peoples minds at rest or prepare for the possibility of having to pay someone for support or forking the project (eek sorry it would be a last ditch possibility) some way in the future.

Thanks for anything you can share (even if its that you don't know!).

**Comment by kevinsawicki** [comment]
>  would it be possible to disclose Githubs level of sponsership or if Microsoft pay any employees to help out ?

Yes, we can definitely make it clearer that GitHub has full-time people dedicated to it and the other major companies involved.

> Does Github pay for people to be permanently on Electron?

Yes, we have a dedicated Electron team here at GitHub will multiple people on it and are growing the team as well.

This is the job posting for it: https://jobs.lever.co/github/001fe993-4d40-4379-8517-0adf25a93ddd

>  Is there any roadmap beyond 1.0 or once that is reached might Github stop that?

There isn't a firm post-1.0 roadmap yet but GitHub will be definitely be dedicated to the project post-1.0. The post-1.0 roadmap will become clearer over the next couple months and will be shared publicly.

>  Or is this maintained by people in their own free time?

There are many great contributors outside of people working at GitHub, some contribute on behalf of their company since they are building Electron apps there and some contribute in their free time as well.

Hope this helps.

**Comment by lukeapage** [comment]
Thanks, thats great and I hope if we continue to use Electron (and find something missing or broken) we'll contribute back too.

**Comment by zcbenz** [comment]
Closing since it has been answered.
