### ISSUE TITLE
Support for the Auto Save feature of OSX

### ISSUE THREAD

**Issue by erusev** [atom/electron#4229]
Most native OSX text editors take advantage of a OSX feature called "Auto Save" explained at https://support.apple.com/en-us/HT202255.

Does Electron offer support for that feature?

Thanks.

**Comment by zcbenz** [comment]
If you mean adding it in Atom, there is already some packages doing that, if you mean adding it in your Electron app, you can reference how those packages did that.

**Comment by erusev** [comment]
Thanks @zcbenz.

To be sure that I understand, do you mean that there could be a package that works with the native "Auto Save" APIs of OSX or that there could be a package that has the "Auto Save" functionality but doesn't use the APIs of OSX?

**Comment by zcbenz** [comment]
If you mean the `autosavingDelay` API of `NSDocumentController`, then it is not supported in Electron. To use it we have to adopt the whole document model into Electron, which is not likely to happen since it is too much work to provide JavaScript binding and there is no corresponding APIs on other platforms.

If you really want to use it the only choice is to write native Node module for it.

**Comment by erusev** [comment]
Thanks @zcbenz I appreciate the quick response.
