### ISSUE TITLE
Uncaught ReferenceError: echarts is not defined。

### ISSUE THREAD

**Issue by g0267** [atom/electron#4257]
I practiced 5 minutes to get started with the example of echarts3, Uncaught ReferenceError: echarts is not defined。(http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts).
when I switched to echarts 2.2.7,is ok, I do not know why?
Using the electron0.36.5, win10-64

**Comment by zcbenz** [comment]
Electron's environment is a bit different from normal browser because of the Node.js integration, you can probably follow [the FAQ](http://electron.atom.io/docs/v0.36.5/faq/electron-faq/#i-can-not-use-jquery-requirejs-meteor-angularjs-in-electron) to disable Node integration, or seek help in [the repo of charts ](https://github.com/echarts/echarts).
