### ISSUE TITLE
Electron 0.36.6: Context menu no longer works on OS X

### ISSUE THREAD

**Issue by bpasero** [atom/electron#4267]
Clicking on entries from the context menu does not work anymore. A regression with the context menu refactorings maybe?

**Comment by zcbenz** [comment]
@bpasero I added a `console.log` in the click handler of MenuItem in the source code of VS Code, I can see the message in devtools console when I clicked an menu item, so the context menu did work. It is probably because of something else caused the regression.

If this regression happens not only for v0.36.6 but for all >= v0.36.1, then it is probably caused by #3833.

**Comment by bpasero** [comment]
I will investigate further tomorrow, just wanted to file this bug as a heads up if maybe it was something obvious.

**Comment by bpasero** [comment]
@zcbenz so it looks like with the newer electron version, calling menu.popup() is no longer blocking the renderer process, so the V8 execution just continues without interrupt.

So was this changing? Then we need to adopt this new behavior.

**Comment by zcbenz** [comment]
@bpasero Before #3833, calling `menu.popup` in renderer process would still pump the message loop while the call itself is blocking, so when you click the menu item, its handler will called in renderer process before `menu.popup` ends. After the change the handler will be called after `menu.popup` ends.

**Comment by bpasero** [comment]
Yup makes sense, I am ok with that and can probably easy adopt, so I am fine closing this.

**Comment by bpasero** [comment]
Works nicely. The only down side from the previous solution is that you no longer have a way to find out if the context menu was canceled without picking an entry or not.
