### ISSUE TITLE
cookies and session not getting forwarded / persisted in webview

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#4304]
Hello,

We were testing one of my products oauth implementation. we can see a subtle change in the behavior.
Application is failing to recognize the users. but works perfectly fine in both chrome & FF browsers. We are using Webview injection to load our entry point to web page.

Ex website:
http://www.oauthlogin.com/home.php

this website could be taken as perfect example similar to our web app. In this app once logged in. loading the webpage again. will recognize user and print info. 

sample app : https://github.com/kamesh-a/electron-samples/tree/master/sessioncheck
Tested in Latest to 0.3x.x builds. Please let us know if you need more info. 

Thanks.

**Comment by kamesh-a** [comment]
Note : We can see the presence of cookies & session data available in dev console for webview injected page.. thats what i am wondering. why server application cannot collect the session information from webview injected page use it for remembering user.

**Comment by zcbenz** [comment]
I opened the app and logged in successfully with Google account, after reopening the app the website did not login automatically, but the login information of Google is remembered, so if I login with Google I only need to click once instead of refilling the passwords.

I can reproduce the exactly same behavior in Safari and Chrome, I don't see the problem here.

**Comment by kamesh-a** [comment]
Hi @zcbenz thanks for checking it.
```
if I login with Google I only need to click once instead of refilling the passwords
```
this behavior is not exhibited in Chrome or safari. Next tab if i load the same website. it just prints my user profile info. without needing to click "Login with Google". until unless i do "Log out"
```
Mac OS x Yosemite:
Safari version : 9.0.1 
Chrome 48,47,46
```

**Comment by zcbenz** [comment]
Openning a new tab is not the same with reopening the app, it is more similar to creating a new webview in Electron. You can easily reproduce by quitting Chrome and then reopening it.

This is because the website uses non persistent cookie, for more you can have a read of:
http://stackoverflow.com/questions/3869821/how-do-i-create-a-persistent-vs-a-non-persistent-cookie

**Comment by kamesh-a** [comment]
@zcbenz thanks man. my bad. sorry for wasting your time.

**Comment by loretoparisi** [comment]
@zcbenz I'm facing the same issue, but in my case I'm pretty sure that the website is using persistent cookies with no expire or long session cookies for oAuth domain. What happens in electron, is that loading that same page (over https) the oauth cookies will expire at every app loading for some reason I'm using `macOS 10.13.4`. Should I handle cookies in some different way then within electron?
