### ISSUE TITLE
Build failing for target_arch=ia32 

### ISSUE THREAD

**Issue by ritesh-pandey** [atom/electron#4399]
![screenshot from 2016-02-07 18 50 05](https://cloud.githubusercontent.com/assets/1433681/12872539/b6765f02-cdcb-11e5-90b9-4f77de338fc4.png)

Electron 0.36.7
Ubuntu 14.04

`./script/bootstrap.py -v --target_arch=ia32`
`./script/build.py`

This looks to be the culprit
`undefined reference to symbol 'clock_gettime@@GLIBC_2.2`

**Comment by ritesh-pandey** [comment]
Many folks have suggested to use -ltr in CFLAGS. How do I do that?

**Comment by zcbenz** [comment]
The `-ltr` is in `CFLAGS`, but somehow your linker can't find the symbol, you can probably try installing `clang` in your system.

I'm closing this because the toolchain system is complex between different linux distributions and we are not able to ensure Electron can build on every distribution with various build toolchains.
