### ISSUE TITLE
Windows 10 Features like Store, Cortana etc?

### ISSUE THREAD

**Issue by garfbradaz** [atom/electron#4436]
Can you submit Electron Apps via the Windows Store? I know you can build native Windows Apps using HTML5/WinJS and sell/distribute them and you can also use Project Westminister/ManifoldJS to create windows hosted UWP Apps, which allows you to light up your app to use features like Cortana, HoloLens etc - but what about Electron Apps? Is there a way of getting access to these paltform specific features?

https://microsoftedge.github.io/WebAppsDocs/en-US/win10/HWA.htm

**Comment by paulcbetts** [comment]
> Can you submit Electron Apps via the Windows Store?

No

>  Is there a way of getting access to these paltform specific features?

Most Win10 APIs are available to desktop apps, you just have to call them via a native component or via edge.js (which is what the Slack app does). A few don't work such as Live Tiles or Cortana because they're rigged to send parameters through UWP's `App.OnActivated` event which doesn't exist in desktop apps, or require an AppX manifest

**Comment by chawei** [comment]
hi @anaisbetts, is it still true that `App.OnActivated` is not available on Electron through NodeRT?
