### ISSUE TITLE
electron.exe seems to be detected as virus on windows 64bit

### ISSUE THREAD

**Issue by frozeman** [atom/electron#4485]
According to this websites, which scans files with multiple antvir softwares electron.exe is detected as virus on at least on anther program.

I noticed that because users of our Ethereum Mist Wallet were pointing it out.

https://www.virustotal.com/en/file/f7a451970fa391abd29d20ddebafb4800016a7c48087fd01fb2519955cdcf139/analysis/

**Comment by felixrieseberg** [comment]
This is most likely harmless and without any effect for the user as long as you sign your code (quote @paulcbetts: "Sign your code or bad things will happen"). As an example, the same heuristic also complains about the [PrintIsolationHost, which is part of Windows](https://www.virustotal.com/en/file/e7188e280f93f24f88e779fa4288e22e40e7ed43921fcf9b5c69189d662630d7/analysis/).

As the Microsoftie on Electron, I don't think there's any change necessary.

**Comment by baconface** [comment]
False positives are always going to come up as people will create viruses, malware, spyware, PUPs, etc in Electron and the AV's are too lazy to accurately get a signature. The issue isn't with Electron and it needs to be appealed with the AV vendor. Doing so they usually remove flag and possibly white list from future false positives. Otherwise if Electron team codes around this Bkav and other vendors can mistakenly flag it again in the future.

**Comment by zcbenz** [comment]
There is no magical way to make all anti-virus programs trust Electron, you can follow https://github.com/atom/atom/issues/3927 on how to solve this kind of problem.

**Comment by JwTheVirusDetector** [comment]
Electron is A virus, in fact, it contains a RAT Trojan.
