### ISSUE TITLE
CreateProcess: The parameter is incorrect.

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [atom/electron#4516]
Hey Team,

I am having some issues compiling from source.

I installed MSVS 2013, update 4, ran the bootstrap script, everything went well.

Then, when I run `python script\build.py`

I get:

```
ninja: Entering directory `out\R'
[8/1059] CC obj\vendor\node\deps\zlib\zlib.compress.obj
FAILED: ninja -t msvc -e environment.x86 -- "" /nologo /showIncludes /FC @obj\ve
ndor\node\deps\zlib\zlib.compress.obj.rsp /c ..\..\vendor\node\deps\zlib\compres
s.c /Foobj\vendor\node\deps\zlib\zlib.compress.obj /Fdobj\vendor\node\deps\zlib\
zlib.c.pdb
ninja: fatal: CreateProcess: The parameter is incorrect.
```

This happens about 8 or so times with different file names (See image: https://i.gyazo.com/d4a84ae0191e8555dcaebcb323b2408c.png)

Any idea what is causing this?

Thank you

**Comment by zcbenz** [comment]
There were a few similar issues in Chromium:
https://code.google.com/p/chromium/issues/detail?id=246256
https://code.google.com/p/chromium/issues/detail?id=334020

I think it is probably because something wrong happened when you installed your toolchain, I suggest just reinstalling MSVS.

I'm closing this since it is some bug of the toolchain or the build tools, and we are not able to fix it on Electron's side.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Alrighty, no probs. I'll reinstall MSVS thanks for those links as well. Thank you
