### ISSUE TITLE
Media Devices have their label set to empty string

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4613]
* Electron version: `0.36.9`
* Operating system: `Windows 10 x64`

Somewhere in the jump from electron `0.36.7` to `0.36.9` some media devices functionality broke.  All media devices no longer have the "label" attribute set correctly.

Running this code in `0.36.9` outputs a lot of *empty strings*
```js
navigator.mediaDevices.enumerateDevices()
    .then((devices) => {
        devices.forEach((device) => console.log(device.label));
    });
```

Whereas on `0.36.7` you get the correct audio output names

**Comment by MarshallOfSound** [comment]
Just confirmed issue is present in `0.36.8`

**Comment by diracdeltas** [comment]
If I'm not mistaken, the fix for this allows any site to see media labels for all devices without the user having granted permission to the site. Chrome does not show the labels until permission is granted. If this is the case, it's a huge privacy loss for Electron (since often users can be uniquely identified by their media device labels). 

To test this you can try opening https://www.webrtc-experiment.com/DetectRTC/ in an electron webview vs in Chrome.

**Comment by MarshallOfSound** [comment]
@diracdeltas Electron is not a browser and does not have a built in user-facing permission model like chrome does.

**Comment by diracdeltas** [comment]
@MarshallOfSound I'm well aware that Electron is not intended for loading remote content. However you do expose a permissions API via `ses.setPermissionRequestHandler` and it would be entirely reasonable to tie the permission to see media device labels to the `media` permission.

**Comment by MarshallOfSound** [comment]
@diracdeltas Let me look into this
