### ISSUE TITLE
Too many open files.

### ISSUE THREAD

**Issue by niknickolas** [atom/electron#4759]
If you have got this error 
[21981:0311/145655:FATAL:platform_channel_pair_posix.cc(40)] Check failed: socketpair(AF_UNIX, SOCK_STREAM, 0, fds) == 0. : Too many open files
It's error of OS.

**Comment by florianb** [comment]
As the stacktrace says: you have [`Too many open files`](http://lmgtfy.com/?q=Too+many+open+files). This occurs because you keep too much files opened at once.

You'll find a lot of answers elaborating on this issue behind the link above. A hint for future requests, let the title of your issue be more specific and check your caps-lock twice.

**Comment by niknickolas** [comment]
Is problem  either OS or Electron or vnc4server and  what kind of files are. ?
Files that are downloading or other files for example sockets, pid files .....

**Comment by 12joan** [comment]
I encountered an error like this today when building Electron from source on macOS. I know this issue is 8 years old, but it was the first thing I found when searching for "electron build too many open files", so I'll share my solution here anyway for anyone who finds this issue in the future.

As this [StackExchange answer](https://superuser.com/a/443168) explains, you can check macOS's maximum files globally and per process using `sysctl kern.maxfiles` and `sysctl kern.maxfilesperproc` respectively. In my case, both of these were much larger than the actual number of open files (measured with `sudo lsof | wc -l`), but I increased them anyway just in case.

I also increased the maximum open files for the current shell using `ulimit -S -n <big number>`, which I think is what actually fixed it.
