### ISSUE TITLE
How can I get the BrowserWindow id from a renderer process?

### ISSUE THREAD

**Issue by jviotti** [atom/electron#4790]
Is this information somehow encoded in the renderer process?

**Comment by abdihaikal** [comment]
Have you try this ?
require('electron').remote.getCurrentWindow().id

**Comment by jviotti** [comment]
@abdihaikal Cheers, I missed that from the docs :)

**Comment by tbogard** [comment]
Since Electron now has more things than 2 years ago, you can just go over the event of your IPC call and request the BrowserWindow that triggered the call:

`event.sender.getOwnerBrowserWindow()` has that. It returns a BrowserWindow Object with all the properties that it could have such: minimize(), close(), etc....
