### ISSUE TITLE
Unable to run packaged module under windows share (samba)

### ISSUE THREAD

**Issue by Enelar** [atom/electron#4823]
* Electron version:
0.36.10
* Operating system:
Windows 7 Enterprise

Electron is unable to `require` modules via `./dir/modulename`, when using asar or not, during executing through network share.

Use case:

1. Create VBox instance
2. Share packaged folder via VBox Additions
3. Navigate to \\\\VBOXSVR
4. Click on executable
5. Notice 'require module not found' through DevTools. For relative paths. (not system modules)

**Comment by felixrieseberg** [comment]
There's a difference between what you can see in Explorer.exe and Node' native fs library - just because it's in the Explorer, it sadly doesn't mean that native tools can talk to it like it's on the filesystem. That sucks, but that's sadly the case.

Given that `fs` can't read or write to `smb://`, I'm not sure that there's anything useful we can do here. If you have a usecase in which your users _have_ to run from samba, use tools like Squirrel to first copy your whole Electron app to the user's app data folder - that should solve the issue.

**Comment by Enelar** [comment]
No, i have no use case. Im just reporting issue. Following linux way: work or fork.
I thought that windows virtualize fs, like `fuse` do. Sorry if touched your feelings.
Product is great, forget that case, focus on features.
