### ISSUE TITLE
Wrong icon displayed in Unity Dock

### ISSUE THREAD

**Issue by mspl13** [atom/electron#4878]
* Electron version: 0.37.2 (from [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/package.json#L37))
* Operating system: Ubuntu 14.04.4 LTS
* *Description*: Recently I've noticed in that a wrong icon is displayed in the unity dock from Ubuntu when starting [Google Play Music Desktop Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/) (actually the very old google logo is displayed; maybe from the authentication API from google?). One strange thing is the fact that if I start the application from the terminal the wrong icon is displayed but when I launch it from the unity search everything is fine. I raised the [issue](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/590) there and the maintainer said that this is probably a bug in electron.

![screenshot from 2016-03-14 18 51 11](https://cloud.githubusercontent.com/assets/8393513/13949725/f34be708-f026-11e5-956f-684443c54413.png)

**Comment by zcbenz** [comment]
Which icon is showed in dock is purely decided by the desktop environment you use, e.g. Unity.

The binary name of google-play-music-desktop-player is "Google Play Music Desktop Player", which has spaces in it, my theory is, when you start it from terminal, Unity failed to recognized the full name and only used "Google" as app name, resulting in the icon of google being used.

I'm closing this since it is more likely a bug of Unity, I suggesting reporting it to Unity instead, but it is also possible that this bug has already been fixed in newer versions.
