### ISSUE TITLE
electron.dialog missing

### ISSUE THREAD

**Issue by stevedekorte** [atom/electron#4943]
* Electron version: Version 0.36.1 (0.36.1)
* Operating system: OSX 10.11.3 (15D21)

const dialog = require('electron').dialog;
console.log(dialog)

prints:

undefined

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting. If you're opening a dialog from the renderer process, you need to reference it as `require('electron').remote.dialog`, since it's a main thread-module.

I'm closing this issue in the meantime, but feel free to reopen if you actually referenced it correctly and it is still undefined.

**Comment by barbalex** [comment]
this helped me electron noob too, thanks

maybe add this information to https://github.com/atom/electron/blob/master/docs/api/dialog.md?
