### ISSUE TITLE
can't add to chrome

### ISSUE THREAD

**Issue by strikersix23** [atom/electron#4971]
* Electron version:latest
* Operating system:chrome
i can't add it to chrome it has all the things for except the index and manifest is unreadable!

**Comment by jlord** [comment]
Could you provide more information please, I'm not sure what you're describing. 

Are referring to ChromeOS or Chrome the browser? In either case, Electron cannot be "added" to these.

**Comment by strikersix23** [comment]
i'm trying to make it to be able to its kind of hard but i have done some
code and it seems to work a little i just need to know what leave out and
what to put in and I'm talking about both chrome os and chrome browser

**Comment by mnquintana** [comment]
Electron is a runtime for developing standalone desktop apps on top of Chromium and Node.js – it's not intended (or possible) to be used for developing Chrome extensions or Chrome OS apps – sorry for any confusion here!

**Comment by baconface** [comment]
For Chrome OS some developers have been able to run Atom on Chrome OS with modification of Chrome OS itself. It seems through a combination of building Electron for Linux and ARM processors and using [Crouton](https://github.com/dnschneid/crouton). I have never done it so I can't help out beyond this. It wouldn't be possible to build and distribute Electron apps for Chrome OS without modifying Chrome OS though. So it might not be a reasonable avenue to explore.

For Chrome and Chrome OS apps you should just not use Electron completely and write your apps for those platforms. Depending on your app and how you write it you might be able to reuse or keep the same code base. Otherwise you are going to be continually fighting an uphill battle with a duct tape and bailing wire solution.

**Comment by strikersix23** [comment]
i don't want to develop chrome apps with it i want to run it in chrome
itself

**Comment by strikersix23** [comment]
10016489@discoverers.org sent you an invitation to join MEGA.

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDEwNGJiYzY3ZTcwZWM3MzcwZDRhZDc0MzU5ZWZlNTcxYjE0ODNiNDc3ZjZmOGNkOTJjZjAwMDAwMDAxMTMxNTJkMTA5MmExNjljZTA4YTNlYWNhQHJlcGx5LmdpdGh1Yi5jb22rSpzdmfEEbw

Best regards,

Team MEGA

**Comment by strikersix23** [comment]
10016489@discoverers.org sent you an invitation to join MEGA.

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDEwNGJiYzYzZWQwODU4NmEyNWFhY2VjMzUwNTYzNTdlNzViMWE4ZWNjMDRkYTc2OTJjZjAwMDAwMDAxMTMxYWE0YTE5MmExNjljZTA4YTNlYWNhQHJlcGx5LmdpdGh1Yi5jb22Z9Z5a0iUTqg

Best regards,

Team MEGA
