### ISSUE TITLE
electron --help error

### ISSUE THREAD

**Issue by Luncher** [atom/electron#4980]
* Electron version:0.37.3
* Operating system:fedora21

[luncher@localhost LocalHolaStudio]$ electron --help
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/luncher/.nvm/versions/node/v5.8.0/lib/node_modules/electron-prebuilt/path.txt'

**Comment by Luncher** [comment]
Today I upgraded from 0.37.2 to 0.37.3

**Comment by kevinsawicki** [comment]
This looks really similar to https://github.com/electron-userland/electron-prebuilt/issues/85 so possibly try clearing `node_modules/electron-prebuilt` and reinstalling via `npm install`?

Going to close this out since this doesn't appear to be an electron issue since error points to electron-prebuilt being the issue.
