### ISSUE TITLE
Blinking / Flashing while loading

### ISSUE THREAD

**Issue by nicozimmermann94** [atom/electron#4985]
* Electron version: 0.37.3
* Operating system: Windows 10 x64

Hello, is there a way do turn off the white flash while loading a site?
![blink](https://cloud.githubusercontent.com/assets/9193934/14204320/c749f8b8-f803-11e5-9f3e-16a33da3993d.gif)

**Comment by nicozimmermann94** [comment]
Thank you very much.

**Comment by zcbenz** [comment]
@nicozimmermann94 I think I have probably misunderstood your issue, there is actually no way to remove the white flash when you do page navigations, because browser works by downloading and rendering page in the same time, so when navigation happens you will the progress of previous page getting erased and the new page getting rendered, which is the white flash you saw.

The only workaround is to avoid page navigations in your app completely, with techniques like ajax, otherwise your app will just behave like normal browsers.

**Comment by nicozimmermann94** [comment]
@zcbenz But when I visit the website with the "normal" chrome/chromium webbrowser, I do not get those white flashes. It seems like chrome waits to render it before it refreshes the view.

**Comment by diaryzhang** [comment]
@zcbenz I build a demo based on electron and nwjs separately,  I found electron still has the issue of visual flash when navigating, but nwjs does not has this issue. Does electron have the plan or date to solve this issue, or leave this issue to chromium? Nwjs is using libchromiumcontent, and electron is using Chromium, is that the reason?

**Comment by zcbenz** [comment]
@diaryzhang Electron forces the renderer process to restart for every navigation, while Chrome and nwjs only restarts the renderer process for cross-site navigations, that should be why you can see the flashing.

**Comment by nicozimmermann94** [comment]
@zcbenz is there a way to force electron to behave like chrome?

**Comment by diaryzhang** [comment]
@zcbenz can we add a option to loadUrl API to control whether force to restart the renderer process or not. I believe many devs have the visual flash issue.
