### ISSUE TITLE
Web Workers seem to have "web-security" enabled

### ISSUE THREAD

**Issue by wprater** [atom/electron#600]
Trying to make a cross origin XMLHttpRequest from within a Web Working.  Getting this type of error:

```
XMLHttpRequest cannot load http://0.0.0.0:4000/app/test.png. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'file://' is therefore not allowed access.
```

I've setup the BrowserWindow with this config, which does not seem to affect the Web Worker.
```
'web-preferences': {
  'web-security': false
}
```

**Comment by zcbenz** [comment]
Waiting Chromium to implement this is like to take forever, and I don't believe they would have any interest in it too. Since Node is also already working on a Worker solution (https://github.com/nodejs/node/pull/2133), I'm closing this as won't fix.
 
Pull requests are still welcomed if anyone is interested in contributing a patch to Chromium and then adding the feature to Electron.

**Comment by impinball** [comment]
By the way, it seems that [a fix will come in a later update, as it's been fixed in Chromium Canary](https://code.google.com/p/chromium/issues/detail?id=254993#c9).

**Comment by Shawson** [comment]
Hi- did this issue get resolved in the end?  I think I'm suffering from this problem myself.  I have web-security set to false, but fetch requests I make to other domains (bbc.co.uk for example) from within my web worker are blocked citing a cors error?
